import { FruitType } from "@prisma/client";
import { fruitMaker } from "./devil-fruit-builder";

const zoan = fruitMaker(FruitType.ZOAN);
const anc = fruitMaker(FruitType.ZOAN_ANCIENT);
const myth = fruitMaker(FruitType.ZOAN_MYTHICAL);

/** Original animal fruits (common, duplicable): the body turns into the animal, fully or in a hybrid form, with its senses and strength. */
export const INVENTED_ZOAN = [
  zoan("Kuma Kuma no Mi: Modelo Oso Pardo", "Bear-Bear Fruit: Grizzly", "UNCOMMON", "Un oso pardo: fuerza bruta, zarpazos pesados y una piel gruesa que aguanta filos flojos. Lento en terreno abierto, temible cuerpo a cuerpo.", "transformation", 16, 12, 2),
  zoan("Washi Washi no Mi: Modelo Águila", "Eagle-Eagle Fruit: Eagle", "UNCOMMON", "Un águila: vuelo alto y veloz, vista de lince y garras que atrapan desde el aire. En el agua es una presa fácil.", "mobility", 12, 4, 14),
  zoan("Gori Gori no Mi: Modelo Gorila", "Gorilla-Gorilla Fruit: Gorilla", "UNCOMMON", "Un gorila: brazos enormes, puños que rompen muros y una resistencia excelente. Pega despacio pero con mucha fuerza.", "transformation", 16, 12, 2),
  zoan("Kaba Kaba no Mi: Modelo Hipopótamo", "Hippo-Hippo Fruit: Hippo", "COMMON", "Un hipopótamo: mandíbula aplastante, piel gruesa y una embestida mucho más rápida de lo que parece; en el agua es un tanque.", "transformation", 12, 14, 4),
  zoan("Sai Sai no Mi: Modelo Rinoceronte", "Rhino-Rhino Fruit: Rhino", "COMMON", "Un rinoceronte: cuerno y embestida capaces de derribar puertas, y una piel que aguanta la mayoría de cortes normales.", "transformation", 14, 14, 2),
  zoan("Wani Wani no Mi: Modelo Cocodrilo", "Croc-Croc Fruit: Crocodile", "UNCOMMON", "Un cocodrilo: mordida de presa, vuelta mortal en el agua y emboscada desde la orilla. En seco es más torpe.", "transformation", 14, 10, 6),
  zoan("Tako Tako no Mi: Modelo Pulpo", "Octopus-Octopus Fruit: Octopus", "UNCOMMON", "Un pulpo: ocho brazos que atrapan y estrangulan, camuflaje en el terreno y una nube de tinta para huir.", "transformation", 10, 8, 8),
  zoan("Ika Ika no Mi: Modelo Calamar", "Squid-Squid Fruit: Squid", "COMMON", "Un calamar: propulsión a chorro, tentáculos ágiles y tinta cegadora. Fuera del agua pierde mucha velocidad.", "mobility", 8, 6, 12),
  zoan("Kani Kani no Mi: Modelo Cangrejo", "Crab-Crab Fruit: Crab", "COMMON", "Un cangrejo: caparazón resistente y pinzas que cortan cuerdas y cadenas; camina de lado, pero muy rápido.", "defensive", 10, 14, 4),
  zoan("Fukurō Fukurō no Mi: Modelo Búho", "Owl-Owl Fruit: Owl", "UNCOMMON", "Un búho: vuelo silencioso, ojos que ven de noche y un giro de cabeza imposible. De día rinde bastante menos.", "mobility", 8, 6, 12),
  zoan("Kōmori Kōmori no Mi: Modelo Murciélago", "Bat-Bat Fruit: Bat", "COMMON", "Un murciélago: ecolocalización perfecta, vuelo veloz en la oscuridad y chillidos que aturden. La luz del sol lo debilita.", "mobility", 8, 4, 14),
  zoan("Ari Ari no Mi: Modelo Hormiga Soldado", "Ant-Ant Fruit: Soldier Ant", "COMMON", "Una hormiga soldado: fuerza descomunal para su tamaño, mandíbulas y la capacidad de levantar hasta diez veces su peso.", "transformation", 12, 10, 6),
  zoan("Chō Chō no Mi: Modelo Mariposa", "Butterfly-Butterfly Fruit: Butterfly", "COMMON", "Una mariposa: alas de escamas que dispersan polvo somnífero, vuelo errático difícil de golpear.", "mobility", 6, 4, 14),
  zoan("Karasu Karasu no Mi: Modelo Cuervo", "Crow-Crow Fruit: Crow", "COMMON", "Un cuervo: astucia de ave inteligente, robo de objetos pequeños y una bandada de sombras que ciega.", "mobility", 8, 6, 12),
  zoan("Hyō Hyō no Mi: Modelo Pantera", "Panther-Panther Fruit: Panther", "UNCOMMON", "Una pantera negra: sigilo casi total en la oscuridad, velocidad de ataque brutal y zarpazos precisos.", "transformation", 14, 8, 14),
  zoan("Shika Shika no Mi: Modelo Ciervo", "Deer-Deer Fruit: Stag", "COMMON", "Un ciervo: cornamenta enorme, saltos largos y una embestida de cabeza que levanta a un hombre.", "mobility", 10, 8, 10),
  zoan("Rakuda Rakuda no Mi: Modelo Camello", "Camel-Camel Fruit: Camel", "COMMON", "Un camello: aguante casi infinito sin comer ni beber, andar firme en la arena y patadas que pesan.", "transformation", 8, 12, 4),
  zoan("Kitsutsuki no Mi: Modelo Pájaro Carpintero", "Woodpecker Fruit: Woodpecker", "COMMON", "Un pájaro carpintero: picotazos a ritmo de metralleta capaces de abrir madera, cuero y armadura floja.", "offensive", 12, 4, 10),
  zoan("Hachi Hachi no Mi: Modelo Oso Hormiguero", "Anteater Fruit: Giant Anteater", "COMMON", "Un oso hormiguero gigante: lengua larguísima, garras fuertes y olfato prodigioso; no soporta el frío.", "transformation", 10, 10, 4),
  zoan("Ookami Ookami no Mi: Modelo Lobo Ártico", "Wolf-Wolf Fruit: Arctic Wolf", "UNCOMMON", "Un lobo ártico: resiste el frío extremo, caza en manada con ecos y persigue sin cansarse; en el calor se agota.", "transformation", 12, 10, 12),
  anc("Ryu Ryu no Mi: Modelo Estegosaurio", "Dragon-Dragon Fruit: Stegosaurus", "RARE", "Placas óseas en el lomo y una cola con cuatro púas: su defensa es enorme y su cola es un mazo espinoso.", "defensive", 16, 20, 2),
  anc("Ryu Ryu no Mi: Modelo Tiranosaurio", "Dragon-Dragon Fruit: T-Rex", "EPIC", "El rey de los depredadores: mordida de ruina, rugido que paraliza a los débiles y una fuerza tremenda con unas patas cortas que compensa con puro peso.", "transformation", 24, 14, 6),
  anc("Ryu Ryu no Mi: Modelo Anquilosaurio", "Dragon-Dragon Fruit: Ankylosaurus", "RARE", "Un cuerpo acorazado y una cola-maza que revienta cráneos; casi nada lo atraviesa, pero se mueve como una roca.", "defensive", 14, 24, 0),
  anc("Ryu Ryu no Mi: Modelo Velociraptor", "Dragon-Dragon Fruit: Velociraptor", "RARE", "Garra en la pata, velocidad de depredador cazando en grupo y saltos que atrapan por la espalda.", "offensive", 16, 6, 16),
  anc("Ryu Ryu no Mi: Modelo Quetzalcoatlus", "Dragon-Dragon Fruit: Quetzalcoatlus", "RARE", "Un pterosaurio gigante: envergadura de barco, vuelo ancestral y picos como lanzas. Necesita altura y aire libre.", "mobility", 14, 8, 14),
  anc("Same Same no Mi: Modelo Megalodón", "Shark-Shark Fruit: Megalodon", "EPIC", "El tiburón más grande que existió: mordida capaz de partir un bote, y en el agua un depredador casi sin rival. En tierra apenas se mueve.", "transformation", 24, 12, 6),
  anc("Hebi Hebi no Mi: Modelo Titanoboa", "Snake-Snake Fruit: Titanoboa", "EPIC", "Una serpiente gigante del pantano ancestral: constricción capaz de romper huesos y un cuerpo casi sin punto débil.", "control", 18, 14, 4),
  anc("Namake Namake no Mi: Modelo Megaterio", "Sloth-Sloth Fruit: Giant Sloth", "RARE", "Un perezoso terrestre gigante: garras enormes, una fuerza descomunal y una piel de pelo grueso que amortigua los golpes.", "transformation", 18, 16, 0),
  myth("Kitsune Kitsune no Mi: Modelo Zorro de Nueve Colas", "Fox-Fox Fruit: Nine-Tailed Fox", "LEGENDARY", "El zorro mítico de nueve colas: llamas azules, ilusiones tan reales como el mundo y una inteligencia astuta; cada cola que revela es una técnica más.", "transformation", 20, 12, 14, { singleton: true, awakened: "Sus nueve colas cubren el campo de batalla de llamas zorro" }),
  myth("Tengu Tengu no Mi: Modelo Tengu", "Tengu-Tengu Fruit: Tengu", "LEGENDARY", "El espíritu del bosque alado: abanico que levanta vendavales, espada de la montaña y un vuelo imposible; no perdona a los arrogantes.", "transformation", 20, 10, 16, { singleton: true }),
  myth("Kirin Kirin no Mi: Modelo Kirin", "Kirin-Kirin Fruit: Kirin", "LEGENDARY", "La bestia sagrada del trueno y la justicia: galopa sobre el aire, brilla y derriba con un cuerno de luz a quien tenga las manos manchadas; no hiere a los inocentes.", "transformation", 18, 14, 16, { singleton: true }),
  myth("Inu Inu no Mi: Modelo Cerbero", "Dog-Dog Fruit: Cerberus", "LEGENDARY", "El perro guardián de tres cabezas: tres mordidas a la vez, un aullido triple que paraliza y una vigilancia que nadie esquiva.", "transformation", 24, 14, 10, { singleton: true }),
  myth("Ushi Ushi no Mi: Modelo Minotauro", "Cow-Cow Fruit: Minotaur", "EPIC", "El toro humano del laberinto: hacha de guerra, embestida capaz de derrumbar muros y un instinto de laberinto que le impide perderse.", "transformation", 24, 14, 6),
  myth("Uma Uma no Mi: Modelo Pegaso", "Horse-Horse Fruit: Pegasus", "LEGENDARY", "El caballo alado: galope aéreo, cascos de luz y la capacidad de llevar consigo a un aliado a través del cielo.", "mobility", 14, 10, 18, { singleton: true }),
  myth("Tori Tori no Mi: Modelo Grifo", "Bird-Bird Fruit: Griffin", "EPIC", "Mitad águila, mitad león: garras de rapiña, zarpazo de fiera y un vuelo veloz que aplasta al que huye en campo abierto.", "transformation", 22, 12, 14),
  myth("Hebi Hebi no Mi: Modelo Basilisco", "Snake-Snake Fruit: Basilisk", "LEGENDARY", "El rey de las serpientes: su mirada petrifica un instante a quien lo mire de frente y su veneno es tan fuerte como su constricción. Un espejo, o los ojos cerrados, lo neutralizan.", "transformation", 22, 12, 8, { singleton: true }),
  myth("Tako Tako no Mi: Modelo Kraken", "Octopus-Octopus Fruit: Kraken", "LEGENDARY", "El monstruo de las profundidades: tentáculos del tamaño de mástiles, capaz de hundir un barco y de arrastrar a un hombre a las profundidades. En tierra pierde casi todo.", "transformation", 26, 16, 4, { singleton: true }),
  myth("Kujira Kujira no Mi: Modelo Leviatán", "Whale-Whale Fruit: Leviathan", "MYTHICAL_TIER", "La bestia marina de los cuentos antiguos: el mar mismo se levanta con ella, olas gigantes y una masa casi imposible de mover. La más grande de las frutas de mar.", "transformation", 28, 22, 4, { singleton: true, awakened: "El mar entero responde a su voluntad" }),
  myth("Tori Tori no Mi: Modelo Pájaro del Trueno", "Bird-Bird Fruit: Thunderbird", "LEGENDARY", "El ave de la tormenta: sus alas provocan truenos y su chillido llama a la lluvia. Fuera de una tormenta gasta el doble de aguante.", "transformation", 24, 10, 16, { singleton: true }),
  myth("Inu Inu no Mi: Modelo Anubis", "Dog-Dog Fruit: Anubis", "LEGENDARY", "El guardián de los muertos: pesa el corazón de sus rivales, ve sus pecados y golpea con más fuerza a quien se sabe culpable; guía a las almas.", "transformation", 20, 14, 10, { singleton: true }),
  myth("Neko Neko no Mi: Modelo Mantícora", "Manticore Fruit: Manticore", "EPIC", "Cara humana, cuerpo de león y cola de escorpión: veneno mortal, saltos enormes y una voz que engaña con su encanto.", "transformation", 22, 12, 12),
  myth("Ryu Ryu no Mi: Modelo Hidra", "Dragon-Dragon Fruit: Hydra", "MYTHICAL_TIER", "La serpiente de muchas cabezas: cuando le cortan una, nacen dos. Su veneno es letal, y solo el fuego que sella la herida detiene su regeneración.", "transformation", 26, 20, 6, { singleton: true, awakened: "Sus cabezas se multiplican sin límite" }),
  myth("Sara Sara no Mi: Modelo Salamandra de Fuego", "Salamander Fruit: Fire Salamander", "EPIC", "La salamandra que nace del fuego: vive entre llamas, escupe fuego líquido y regenera cualquier herida si hay lumbre cerca. El agua la apaga.", "transformation", 20, 14, 8),
  myth("Kappa Kappa no Mi: Modelo Kappa", "Kappa Fruit: Kappa", "RARE", "El espíritu del río: un cuenco de agua sobre la cabeza que le da fuerza, luchas de agarre y una cortesía que puede usarse como trampa. Si el cuenco se vacía, se debilita.", "transformation", 14, 12, 10),
];
