import { FruitType, Rarity } from "@prisma/client";
import type { DevilFruitCatalogEntry } from "./devil-fruit-catalog";

/**
 * Original fruits invented for the beginner events (2026-09-25). Every one is a 1-of-1 (isSingleton): they never enter the
 * random drop pool, the shops or enemy kits; the only way to get one is to win the event that offers it.
 */
export const EVENT_FRUITS: DevilFruitCatalogEntry[] = [
  { name: "Tsuta Tsuta no Mi", englishName: "Ivy-Ivy Fruit", type: FruitType.PARAMECIA, rarity: Rarity.UNCOMMON, description: "Hace brotar hiedra viva desde su cuerpo y el suelo: enreda, trepa, ata y forma muros verdes. Crece más rápido con humedad y sol; el fuego la marchita.", effects: { category: "control", atk: 8, def: 8, spd: 2 }, isSingleton: true },
  { name: "Kagami Kagami no Mi", englishName: "Mirror-Mirror Fruit", type: FruitType.PARAMECIA, rarity: Rarity.EPIC, description: "Convierte superficies en espejos que devuelven ataques directos y crean reflejos engañosos. No refleja lo que no ve venir ni ataques por la espalda.", effects: { category: "defensive", atk: 8, def: 20, spd: 4 }, isSingleton: true },
  { name: "Sango Sango no Mi", englishName: "Coral-Coral Fruit", type: FruitType.PARAMECIA, rarity: Rarity.UNCOMMON, description: "Cubre su cuerpo y armas de coral duro y afilado, y hace crecer arrecifes cortantes bajo sus enemigos. Necesita agua cerca para regenerar el coral.", effects: { category: "defensive", atk: 8, def: 14, spd: -2 }, isSingleton: true },
  { name: "Hoshi Hoshi no Mi", englishName: "Star-Star Fruit", type: FruitType.PARAMECIA, rarity: Rarity.RARE, description: "Lanza estrellas de luz cortante y ligera que rebotan entre los enemigos; de noche sus estrellas brillan más y llegan más lejos.", effects: { category: "offensive", atk: 14, spd: 8 }, isSingleton: true },
  { name: "Arashi Arashi no Mi", englishName: "Storm-Storm Fruit", type: FruitType.LOGIA, rarity: Rarity.LEGENDARY, description: "Su cuerpo se vuelve tormenta: viento, lluvia y rayos a su voluntad. Los ataques comunes lo atraviesan; el Haki de Armadura sí le hace daño.", effects: { category: "offensive", element: "tormenta", atk: 22, def: 8, spd: 10, logiaIntangible: true, awakened: { atk: 12, note: "Su tormenta cubre toda la isla" } }, isSingleton: true },
  { name: "Tora Tora no Mi: Modelo Tigre Blanco", englishName: "Tiger-Tiger Fruit: White Tiger", type: FruitType.ZOAN, rarity: Rarity.RARE, description: "Se transforma en un tigre blanco: zarpazos, emboscadas silenciosas y una velocidad felina en la nieve y el bosque.", effects: { category: "transformation", atk: 16, def: 10, spd: 12 }, isSingleton: true },
  { name: "Same Same no Mi: Modelo Tiburón Martillo", englishName: "Shark-Shark Fruit: Hammerhead", type: FruitType.ZOAN, rarity: Rarity.UNCOMMON, description: "Un tiburón martillo: gran olfato para la sangre, cabezazos brutales y ventaja bajo el agua... aunque, como toda fruta, le impide nadar.", effects: { category: "transformation", atk: 14, def: 8, spd: 6 }, isSingleton: true },
  { name: "Shio Shio no Mi", englishName: "Tide-Tide Fruit", type: FruitType.PARAMECIA, rarity: Rarity.EPIC, description: "Controla las mareas: sube y baja el agua de la zona, forma olas y arrastra a sus rivales. Cerca del mar es formidable; lejos de él, casi inútil.", effects: { category: "control", atk: 12, def: 10, spd: 4 }, isSingleton: true },
  { name: "Hari Hari no Mi", englishName: "Needle-Needle Fruit", type: FruitType.PARAMECIA, rarity: Rarity.UNCOMMON, description: "Crece y dispara agujas de todos los tamaños desde su piel, desde alfileres precisos hasta lanzas. Sus agujas no atraviesan el Haki de Armadura fuerte.", effects: { category: "offensive", atk: 12, def: 4, spd: 4 }, isSingleton: true },
  { name: "Kusuri Kusuri no Mi", englishName: "Remedy-Remedy Fruit", type: FruitType.PARAMECIA, rarity: Rarity.RARE, description: "Prepara con su cuerpo remedios y venenos: cura heridas ajenas, adormece o debilita. Cada dosis le cuesta aguante y no revive a nadie.", effects: { category: "utility", atk: 4, def: 10, spd: 4 }, isSingleton: true },
  { name: "Yume Yume no Mi", englishName: "Dream-Dream Fruit", type: FruitType.PARAMECIA, rarity: Rarity.EPIC, description: "Entra en los sueños de quien duerme o está aturdido y los moldea. Un rival bien despierto y entrenado casi no se ve afectado.", effects: { category: "control", atk: 6, def: 8, spd: 6 }, isSingleton: true },
  { name: "Rasen Rasen no Mi", englishName: "Spiral-Spiral Fruit", type: FruitType.PARAMECIA, rarity: Rarity.RARE, description: "Todo lo que toca gira: puños taladro, torbellinos de aire y desvíos de golpes. Se marea si abusa de girar sobre sí mismo.", effects: { category: "offensive", atk: 16, def: 6, spd: 6 }, isSingleton: true },
];
