import type { IslandSecret } from "../engine/island-secrets";
import { KAIROS_SECRETS } from "./islands-kairos";

/**
 * Hand-written discoveries, two per island (one repeatable "common" find, one one-time "rare" find).
 * Texts name only real places from each island's lore gazetteer and never introduce a named person.
 * Fruits appear only on the rarest secrets of the latest islands and are always one-time.
 */
export const ISLAND_SECRETS: IslandSecret[] = [
  // ---- East Blue: starter islands (level 1) ----
  {
    id: "foosha:lata-bajo-el-muelle",
    island: "Pueblo Foosha",
    place: "Muelle de los Suspiros",
    title: "La lata bajo las tablas",
    discovery:
      "La marea baja deja al descubierto una lata sellada con cera, encajada bajo las tablas flojas del muelle. Dentro hay unas monedas y algo de comida seca: el fondo de emergencia de algún pescador que nunca volvió a buscarlo.",
    chance: 0.15,
    minLevel: 1,
    cooldownHours: 24,
    reward: { berries: 400, xp: 30, items: [{ id: "racion", qty: 1 }] },
  },
  {
    id: "foosha:arcon-de-monte-corvo",
    island: "Pueblo Foosha",
    place: "Monte Corvo",
    title: "El arcón del árbol partido",
    discovery:
      "Un rayo abrió en dos un viejo árbol de Monte Corvo y, entre sus raíces, asoma un arcón diminuto envuelto en lona. Guarda un sable de abordaje bien engrasado y unos ahorros que alguien enterró pensando en zarpar algún día.",
    chance: 0.05,
    minLevel: 3,
    cooldownHours: null,
    reward: {
      berries: 6000,
      xp: 150,
      items: [{ id: "mapa", qty: 1 }],
      weapon: { name: "Sable del arcón de Monte Corvo", kind: "Sable", atkBonus: 8, description: "Un sable de abordaje enterrado con cariño: el filo sigue limpio y la empuñadura lleva un ancla grabada.", basePrice: 2500 },
    },
  },
  {
    id: "g5:caja-del-almacen",
    island: "Cuartel Marine G-5",
    place: "El Almacén de Suministros",
    title: "Caja fuera de inventario",
    discovery:
      "Al fondo del almacén, detrás de unos sacos de harina, hay una caja que no figura en ningún registro. Contiene vendajes, raciones y un puñado de monedas de la caja chica que nadie reclamó jamás.",
    chance: 0.15,
    minLevel: 1,
    cooldownHours: 24,
    reward: { berries: 350, xp: 30, items: [{ id: "vendaje", qty: 2 }] },
  },
  {
    id: "g5:cartas-de-navegacion",
    island: "Cuartel Marine G-5",
    place: "Los Archivos y Cartografía",
    title: "El cajón de las cartas viejas",
    discovery:
      "Un cajón con doble fondo en los archivos guarda cartas náuticas descartadas y un fajo de recompensas cobradas hace años que se traspapeló. Los coleccionistas y los cartógrafos pagarían bien por todo ello.",
    chance: 0.04,
    minLevel: 3,
    cooldownHours: null,
    reward: { berries: 7000, xp: 160, items: [{ id: "mapa", qty: 2 }, { id: "botiquin", qty: 1 }] },
  },
  {
    id: "baltigo:alijo-del-bunker",
    island: "Isla Baltigo",
    place: "El Búnker",
    title: "El alijo tras el falso muro",
    discovery:
      "Un tabique hueco al final de un pasillo del búnker esconde un pequeño depósito de la causa: medicinas, algo de dinero y raciones para una emergencia que nunca llegó. Quien lo dejó ya no volvió a por él.",
    chance: 0.12,
    minLevel: 1,
    cooldownHours: 36,
    reward: { berries: 450, xp: 35, items: [{ id: "vendaje", qty: 2 }, { id: "racion", qty: 1 }] },
  },
  {
    id: "baltigo:cueva-de-los-acantilados",
    island: "Isla Baltigo",
    place: "Puesto de Vigía Costero",
    title: "Las luces de la cueva oriental",
    discovery:
      "Siguiendo un sendero de cabras desde el puesto de vigía llegas a una cueva de los acantilados donde alguien encendió señales durante años. Entre las cenizas queda una caja de metal con papeles falsos y un arma corta olvidada.",
    chance: 0.04,
    minLevel: 4,
    cooldownHours: null,
    reward: {
      berries: 8000,
      xp: 180,
      items: [{ id: "papeles", qty: 1 }],
      weapon: { name: "Pistola de los acantilados", kind: "Pistola", atkBonus: 8, description: "Una pistola de mecha con el cañón ennegrecido de humo de señales: pequeña, discreta y sorprendentemente certera.", basePrice: 2800 },
    },
  },
  {
    id: "gecko:botin-del-muelle-este",
    island: "Isla Gecko",
    place: "Muelle Este",
    title: "Botín bajo la red",
    discovery:
      "Entre las redes secas del muelle este hay una boya hueca, tapada con brea, que un contrabandista usaba de caja fuerte. Dentro rueda un buen puñado de monedas y una botella de sake que sobrevivió a mil mareas.",
    chance: 0.15,
    minLevel: 1,
    cooldownHours: 24,
    reward: { berries: 500, xp: 35, items: [{ id: "sake", qty: 1 }] },
  },
  {
    id: "gecko:barco-fantasma-del-norte",
    island: "Isla Gecko",
    place: "Los Muelles Principales",
    title: "El casco varado del norte",
    discovery:
      "La bajamar más grande del año deja varado, contra los arrecifes del norte, el casco de una nave sin bandera que los pescadores llamaban fantasma. Su bodega sellada aún conserva un botín de cazarrecompensas que nadie se atrevió a saquear.",
    chance: 0.05,
    minLevel: 4,
    cooldownHours: null,
    reward: { berries: 9000, xp: 200, items: [{ id: "reliquia", qty: 1 }, { id: "botiquin", qty: 1 }] },
  },
  {
    id: "shimotsuki:tablilla-del-santuario",
    island: "Villa Shimotsuki",
    place: "Santuario de la Cumbre",
    title: "La ofrenda del santuario",
    discovery:
      "Detrás del altar del santuario de la cumbre hay una caja de ofrendas que los viajeros dejan para los espíritus de las espadas. Los aldeanos permiten que un caminante honrado tome prestada una parte, siempre que la use bien.",
    chance: 0.12,
    minLevel: 1,
    cooldownHours: 48,
    reward: { berries: 500, xp: 40, items: [{ id: "sake", qty: 1 }] },
  },
  {
    id: "shimotsuki:hoja-del-vertedero",
    island: "Villa Shimotsuki",
    place: "Vertedero de Escoria",
    title: "La hoja entre la escoria",
    discovery:
      "Removiendo el vertedero de escoria de la fragua descubres una hoja rota y vuelta a forjar, escondida bajo capas de ceniza. Es imperfecta, pero cortó con verdad, y a su lado hay una bolsa de monedas de fundición.",
    chance: 0.04,
    minLevel: 4,
    cooldownHours: null,
    reward: {
      berries: 7500,
      xp: 190,
      weapon: { name: "Katana de la escoria", kind: "Katana", atkBonus: 9, description: "Una katana rescatada del vertedero de la fragua: no es perfecta, pero su filo tiene el temple de una forja honesta.", basePrice: 3200 },
    },
  },
  {
    id: "baratie:bodega-de-cristal",
    island: "Restaurante Baratie",
    place: "Bodega del Galeón",
    title: "El barril olvidado de la bodega",
    discovery:
      "Detrás de las últimas cajas de la bodega descubres un barril que se quedó sin apuntar en el inventario. Guarda vino añejo y un fajo de propinas que los cocineros metieron ahí durante años.",
    chance: 0.15,
    minLevel: 1,
    cooldownHours: 24,
    reward: { berries: 500, xp: 35, items: [{ id: "sake", qty: 1 }, { id: "racion", qty: 1 }] },
  },
  {
    id: "baratie:cobre-de-la-sala-de-hornos",
    island: "Restaurante Baratie",
    place: "Sala de los Hornos",
    title: "El cobre tras los hornos",
    discovery:
      "Por detrás de un horno apagado, la pared cede y deja ver un nicho lleno de piezas de cobre y latón, junto con un plato de cocina de gala envuelto en tela. Es lo que alguien fue robando poco a poco y nunca llegó a sacar del barco.",
    chance: 0.05,
    minLevel: 3,
    cooldownHours: null,
    reward: { berries: 8000, xp: 160, items: [{ id: "banquete", qty: 2 }, { id: "reliquia", qty: 1 }] },
  },
  {
    id: "conomi:red-de-la-pescaderia",
    island: "Isla Conomi",
    place: "La Pescadería Vacía",
    title: "Ahorros entre las redes",
    discovery:
      "En la pescadería vacía, bajo un montón de redes que nadie ha tocado desde la llegada de los hombres-pez, hay un frasco de vidrio con los ahorros de toda una familia. Quien lo escondió no pudo volver a por él.",
    chance: 0.15,
    minLevel: 1,
    cooldownHours: 24,
    reward: { berries: 600, xp: 40, items: [{ id: "vendaje", qty: 1 }] },
  },
  {
    id: "conomi:cueva-del-desertor",
    island: "Isla Conomi",
    place: "La Cueva del Desertor",
    title: "El escondite del desertor",
    discovery:
      "Al fondo de la cueva del desertor, tras una piedra que se desliza, aguarda un tesoro de guerra que el fugitivo nunca se atrevió a gastar: armas de mano, un mapa antiguo y una bolsa pesada de monedas.",
    chance: 0.05,
    minLevel: 4,
    cooldownHours: null,
    reward: {
      berries: 9000,
      xp: 220,
      items: [{ id: "mapa", qty: 1 }],
      weapon: { name: "Tridente del desertor", kind: "Tridente", atkBonus: 9, description: "Un tridente de coral y acero afilado a escondidas, con marcas de haber sido escondido durante años en la humedad de una cueva.", basePrice: 3500 },
    },
  },
  {
    id: "loguetown:bolsa-de-las-alcantarillas",
    island: "Loguetown",
    place: "Las Alcantarillas de la Ciudad Vieja",
    title: "El zurrón de las alcantarillas",
    discovery:
      "Un canal seco de las alcantarillas de la ciudad vieja termina en una reja oxidada con un zurrón atascado. Dentro hay monedas, un botiquín y ganzúas: el equipaje de alguien que huyó de la ley por aquí.",
    chance: 0.14,
    minLevel: 1,
    cooldownHours: 30,
    reward: { berries: 700, xp: 40, items: [{ id: "botiquin", qty: 1 }] },
  },
  {
    id: "loguetown:plataforma-de-metal",
    island: "Loguetown",
    place: "Plaza de la Ejecución",
    title: "La cámara bajo la plataforma",
    discovery:
      "Un adoquín suelto en la Plaza de la Ejecución revela una escalera estrecha que baja bajo la vieja plataforma. Abajo, en una cámara olvidada, alguien guardó objetos de la era dorada de la piratería, entre ellos una espada de recuerdo.",
    chance: 0.04,
    minLevel: 5,
    cooldownHours: null,
    reward: {
      berries: 12000,
      xp: 300,
      items: [{ id: "reliquia", qty: 2 }, { id: "logpose", qty: 1 }],
      weapon: { name: "Espada de la plataforma", kind: "Katana", atkBonus: 11, description: "Una espada de acero antiguo hallada en la cámara bajo la plataforma: pesada de historia, aún dispuesta a cortar.", basePrice: 4500 },
    },
  },
  {
    id: "reverse-mountain:despensa-de-la-montana",
    island: "Reverse Mountain",
    place: "Cavernas de los Susurros",
    title: "La despensa de los cansados",
    discovery:
      "Las cavernas de los susurros guardan una hornacina donde los navegantes agotados dejan lo que ya no cargarán tras cruzar la montaña: raciones, vendajes y algún que otro dinero. Hoy hay más de lo habitual, y nadie lo vigila.",
    chance: 0.15,
    minLevel: 1,
    cooldownHours: 24,
    reward: { berries: 700, xp: 45, items: [{ id: "racion", qty: 2 }, { id: "vendaje", qty: 1 }] },
  },
  {
    id: "reverse-mountain:atajo-de-la-corriente",
    island: "Reverse Mountain",
    place: "La Guarida de los Olvidados",
    title: "El atajo dentro de la montaña",
    discovery:
      "En la guarida de los olvidados, una grieta baja muestra un túnel seco por dentro de la montaña, esquivando la corriente principal. Al final, sobre una plataforma de roca, alguien dejó un Log Pose, mapas y un cofre sellado.",
    chance: 0.04,
    minLevel: 5,
    cooldownHours: null,
    reward: { berries: 14000, xp: 320, items: [{ id: "logpose", qty: 1 }, { id: "mapa", qty: 2 }, { id: "elixir", qty: 1 }] },
  },
  {
    id: "orange-town:fuente-seca",
    island: "Orange Town",
    place: "Plaza de la Fuente Seca",
    title: "Monedas en la fuente seca",
    discovery:
      "La fuente seca de la plaza dejó de manar hace años, pero los vecinos siguen lanzando monedas por costumbre. Entre las grietas del fondo se ha ido acumulando un pequeño montón que nadie se ha atrevido a tocar.",
    chance: 0.15,
    minLevel: 1,
    cooldownHours: 24,
    reward: { berries: 400, xp: 30, items: [{ id: "racion", qty: 1 }] },
  },
  {
    id: "orange-town:armas-del-torreon",
    island: "Orange Town",
    place: "Torreón del Vigía",
    title: "Las armas de la vieja guardia",
    discovery:
      "Tras una pared falsa en el torreón del vigía descubres el arsenal que la antigua guardia ocultó antes de que el circo se adueñara del puerto. Hay armas todavía engrasadas y una bolsa con las pagas atrasadas.",
    chance: 0.05,
    minLevel: 3,
    cooldownHours: null,
    reward: {
      berries: 6500,
      xp: 150,
      items: [{ id: "botiquin", qty: 1 }],
      weapon: { name: "Pistola de la guardia", kind: "Pistola", atkBonus: 8, description: "Una pistola reglamentaria de la antigua guardia de Orange Town, guardada con aceite y paciencia durante años.", basePrice: 2600 },
    },
  },
  {
    id: "syrup:historias-del-arrecife",
    island: "Villa Syrup",
    place: "El Muelle de la Media Luna",
    title: "El cofre de los arrecifes del norte",
    discovery:
      "En la bajamar, más allá del muelle de la media luna, un arrecife deja al descubierto un pequeño cofre de madera hinchada. No es el tesoro de las historias del pueblo, pero sí unas cuantas monedas y una botella bien tapada.",
    chance: 0.15,
    minLevel: 1,
    cooldownHours: 24,
    reward: { berries: 400, xp: 30, items: [{ id: "sake", qty: 1 }] },
  },
  {
    id: "syrup:sotano-de-la-mansion",
    island: "Villa Syrup",
    place: "La Mansión de la Colina",
    title: "El sótano tapiado de la colina",
    discovery:
      "En un rincón olvidado de la mansión de la colina, unas losas sueltas dan paso a un sótano tapiado. Guarda joyas de familia, vajilla de plata y una reliquia envuelta en terciopelo, como si alguien esperase volver por ella.",
    chance: 0.05,
    minLevel: 3,
    cooldownHours: null,
    reward: { berries: 8500, xp: 170, items: [{ id: "reliquia", qty: 2 }] },
  },
  {
    id: "tequila-wolf:herramientas-del-tramo",
    island: "Tequila Wolf",
    place: "Andamios del Tramo 303",
    title: "Herramientas tras el andamio",
    discovery:
      "Bajo los andamios del tramo 303, una losa suelta esconde el botín de un obrero que sacaba material de la obra poco a poco: herramientas de buen acero, un poco de dinero y una ración para una fuga que nunca se produjo.",
    chance: 0.15,
    minLevel: 1,
    cooldownHours: 24,
    reward: { berries: 350, xp: 30, items: [{ id: "racion", qty: 1 }] },
  },
  {
    id: "tequila-wolf:camara-sellada",
    island: "Tequila Wolf",
    place: "Archivo de Planos del Sector Central",
    title: "La cámara sellada de los planos",
    discovery:
      "Siguiendo una marca casi borrada de los planos antiguos llegas a una cámara sellada que se construyó hace siglos y que ningún capataz ha querido abrir. En su interior descansa un pequeño tesoro polvoriento y un arma con historia.",
    chance: 0.04,
    minLevel: 4,
    cooldownHours: null,
    reward: {
      berries: 9000,
      xp: 200,
      items: [{ id: "reliquia", qty: 1 }, { id: "papeles", qty: 1 }],
      weapon: { name: "Pistola del sector central", kind: "Pistola", atkBonus: 8, description: "Una pistola de fabricación antigua salida de la cámara sellada: la culata lleva números de obra que nadie sabe leer.", basePrice: 3000 },
    },
  },

  // ---- Grand Line, first half (levels 8-20) ----
  {
    id: "whisky-peak:libro-de-la-jarra",
    island: "Whisky Peak",
    place: "La Jarra Resquebrajada",
    title: "El hueco bajo la barra",
    discovery:
      "Bajo el mostrador de la taberna descubres un hueco donde se guardaban los bienes de quienes nunca salieron de los festejos. Hay monedas, licor bueno y varios objetos de valor sin dueño que reclamar.",
    chance: 0.12,
    minLevel: 8,
    cooldownHours: 36,
    reward: { berries: 1500, xp: 250, items: [{ id: "sake", qty: 2 }] },
  },
  {
    id: "whisky-peak:monstruo-del-fondo",
    island: "Whisky Peak",
    place: "Puerto de los Suspiros",
    title: "Lo que arrastró la marea",
    discovery:
      "Una noche de marea viva deja varada en el puerto de los suspiros una estructura de coral y huesos de gran bestia. Entre sus costillas quedaron atrapados joyas, perlas y un arma del fondo del mar.",
    chance: 0.04,
    minLevel: 11,
    cooldownHours: null,
    reward: {
      berries: 22000,
      xp: 1500,
      items: [{ id: "perla", qty: 1 }, { id: "elixir", qty: 1 }],
      weapon: { name: "Tridente del monstruo marino", kind: "Tridente", atkBonus: 13, description: "Un tridente de coral endurecido que la marea arrancó del fondo: frío al tacto y con el filo de un colmillo.", basePrice: 6500 },
    },
  },
  {
    id: "jaya:mapa-del-campamento",
    island: "Jaya",
    place: "El Campamento del Buscador",
    title: "El mapa del campamento abandonado",
    discovery:
      "En una tienda rota del campamento del buscador queda una caja de cartógrafo con mapas medio rotos y un poco de dinero. Los buscadores de la ciudad de oro dejaron lo que ya no les servía al partir.",
    chance: 0.15,
    minLevel: 9,
    cooldownHours: 36,
    reward: { berries: 1500, xp: 300, items: [{ id: "mapa", qty: 1 }] },
  },
  {
    id: "jaya:ruta-vertical",
    island: "Jaya",
    place: "El Bosque de los Suspiros",
    title: "La ruta que sube hacia el cielo",
    discovery:
      "En un claro del bosque de los suspiros, unas marcas talladas en la corteza señalan una ruta vertical hacia las nubes. Al pie de la última, en un hueco, aguarda un cofre con equipo de escalada y oro de otra época.",
    chance: 0.04,
    minLevel: 12,
    cooldownHours: null,
    reward: { berries: 24000, xp: 2500, items: [{ id: "reliquia", qty: 2 }, { id: "botiquin", qty: 2 }] },
  },
  {
    id: "long-ring:nave-varada",
    island: "Long Ring Long Land",
    place: "Playa Larga",
    title: "La bodega de la nave varada",
    discovery:
      "Entre las naves varadas de la playa larga, una bodega medio inundada guarda cajas que el antiguo capitán no quiso llevarse. Con paciencia, se rescata comida seca y unos pocos objetos secos y de valor.",
    chance: 0.15,
    minLevel: 11,
    cooldownHours: 36,
    reward: { berries: 1800, xp: 400, items: [{ id: "racion", qty: 3 }] },
  },
  {
    id: "long-ring:premio-del-circulo",
    island: "Long Ring Long Land",
    place: "El Círculo de los Desafíos",
    title: "Los premios enterrados del círculo",
    discovery:
      "Bajo la arena del círculo de los desafíos, donde tantos duelos se resolvieron, se esconden los premios que los ganadores dejaron como ofrenda: monedas, una buena arma y objetos rituales de valor.",
    chance: 0.04,
    minLevel: 14,
    cooldownHours: null,
    reward: {
      berries: 26000,
      xp: 3200,
      items: [{ id: "elixir", qty: 1 }],
      weapon: { name: "Bo del círculo", kind: "Bo", atkBonus: 12, description: "Un bastón largo de madera curada, gastado por incontables duelos rituales y con la punta reforzada de hierro.", basePrice: 5500 },
    },
  },
  {
    id: "little-garden:ambar-de-la-jungla",
    island: "Little Garden",
    place: "El Bosque de Helechos Gigantes",
    title: "Ámbar con algo dentro",
    discovery:
      "Entre los helechos gigantes hay una gota de resina fósil del tamaño de un puño, con un insecto perfecto atrapado dentro. Los coleccionistas pagan bien por estas piezas de un mundo que ya no existe.",
    chance: 0.14,
    minLevel: 10,
    cooldownHours: 36,
    reward: { berries: 1600, xp: 350, items: [{ id: "reliquia", qty: 1 }] },
  },
  {
    id: "little-garden:herida-del-campo",
    island: "Little Garden",
    place: "La Arena de los Cien Años",
    title: "Lo que quedó del duelo eterno",
    discovery:
      "Un siglo de batalla ha dejado la arena sembrada de restos de armas colosales hundidas en el barro. Escarbando en un cráter reciente sacas una hoja gigante, mellada pero utilizable, y un cofre con ofrendas de exploradores antiguos.",
    chance: 0.04,
    minLevel: 13,
    cooldownHours: null,
    reward: {
      berries: 28000,
      xp: 3200,
      items: [{ id: "perla", qty: 1 }, { id: "botiquin", qty: 2 }],
      weapon: { name: "Hacha del duelo eterno", kind: "Hacha", atkBonus: 14, description: "Un hacha enorme fundida a partir de una hoja gigante hallada en la arena: pesada como una losa y capaz de partir un mástil.", basePrice: 7500 },
    },
  },
  {
    id: "alabasta:agua-de-las-dunas",
    island: "Alabasta",
    place: "Oasis del Viento Seco",
    title: "El pozo oculto del oasis",
    discovery:
      "Detrás de las palmas del oasis del viento seco, una losa cubre un pozo excavado por las caravanas para los tiempos de sequía. Aún queda agua fresca y una bolsa con monedas de quienes agradecieron su sombra.",
    chance: 0.15,
    minLevel: 12,
    cooldownHours: 30,
    reward: { berries: 1800, xp: 500, items: [{ id: "oasis", qty: 2 }] },
  },
  {
    id: "alabasta:arma-bajo-las-dunas",
    island: "Alabasta",
    place: "Las Dunas Prohibidas",
    title: "La reliquia bajo las dunas prohibidas",
    discovery:
      "Cuando el viento retira la arena de las dunas prohibidas, asoma la esquina de un cofre de piedra con símbolos antiguos. Dentro yacen joyas de un reino más viejo que el actual y una hoja curva como una luna.",
    chance: 0.04,
    minLevel: 15,
    cooldownHours: null,
    reward: {
      berries: 30000,
      xp: 4500,
      items: [{ id: "reliquia", qty: 3 }],
      weapon: { name: "Cimitarra de las dunas prohibidas", kind: "Sable", atkBonus: 15, description: "Una cimitarra de acero blanco desenterrada del desierto: la hoja curva conserva el brillo de una luna vieja.", basePrice: 8500 },
    },
  },
  {
    id: "ohara:libros-del-subsuelo",
    island: "Ohara",
    place: "Túneles del Subsuelo",
    title: "Los libros que el fuego no alcanzó",
    discovery:
      "En un ramal de los túneles del subsuelo, un derrumbe dejó al aire un anaquel de madera con tomos chamuscados pero legibles. Los coleccionistas y los eruditos pagarían buen dinero por ellos, y ninguno de ellos pide preguntas.",
    chance: 0.12,
    minLevel: 14,
    cooldownHours: 48,
    reward: { berries: 2200, xp: 1400, items: [{ id: "reliquia", qty: 1 }] },
  },
  {
    id: "ohara:camara-bajo-el-arbol",
    island: "Ohara",
    place: "El Árbol Carbonizado",
    title: "La cámara bajo las raíces",
    discovery:
      "Entre las raíces más profundas del árbol carbonizado se abre una cámara que la destrucción no alcanzó. Sobre una mesa de piedra reposan reliquias intactas, mapas antiguos y un cofre de provisiones dejado por quienes protegieron el saber.",
    chance: 0.04,
    minLevel: 17,
    cooldownHours: null,
    reward: { berries: 32000, xp: 6500, items: [{ id: "reliquia", qty: 3 }, { id: "mapa", qty: 2 }, { id: "papeles", qty: 1 }] },
  },
  {
    id: "drum:flor-del-sendero",
    island: "Isla Drum",
    place: "Sendero de la Ascensión",
    title: "La flor del calor",
    discovery:
      "En una cueva abrigada junto al sendero de la ascensión crece, entre la nieve, una planta que florece con calor propio. Recolectada con cuidado, sirve de base para ungüentos y elixires que los médicos de la isla aprecian.",
    chance: 0.14,
    minLevel: 11,
    cooldownHours: 36,
    reward: { berries: 1500, xp: 400, items: [{ id: "botiquin", qty: 1 }, { id: "elixir", qty: 1 }] },
  },
  {
    id: "drum:tesoro-del-castillo",
    island: "Isla Drum",
    place: "Ruinas del Castillo Real",
    title: "La caja fuerte del castillo abandonado",
    discovery:
      "En las ruinas del castillo real, tras una capa de hielo y escombros, aparece una caja fuerte que la corona olvidó en su huida. Guarda las joyas del reino, medicinas de calidad y un arma de la guardia real.",
    chance: 0.04,
    minLevel: 14,
    cooldownHours: null,
    reward: {
      berries: 27000,
      xp: 3500,
      items: [{ id: "perla", qty: 1 }, { id: "elixir", qty: 2 }],
      weapon: { name: "Lanza de la guardia real", kind: "Lanza", atkBonus: 13, description: "Una lanza de acero azulado de la guardia del reino, con la escarcha aún pegada al asta.", basePrice: 7000 },
    },
  },
  {
    id: "water-7:mapa-de-la-biblioteca",
    island: "Water 7",
    place: "Biblioteca Municipal Sumergida",
    title: "El plano bajo el agua",
    discovery:
      "En un estante inundado de la biblioteca sumergida, un tubo de latón estanco guarda un plano de la ciudad que nadie más ha visto. Los astilleros y coleccionistas pagarán gustosos por él, y junto a él hay unas cuantas monedas.",
    chance: 0.14,
    minLevel: 14,
    cooldownHours: 36,
    reward: { berries: 2000, xp: 1200, items: [{ id: "mapa", qty: 1 }] },
  },
  {
    id: "water-7:yunque-secreto",
    island: "Water 7",
    place: "Cementerio de Barcos",
    title: "El casco que guardaba una forja",
    discovery:
      "Entre los cascos del cementerio de barcos hay uno cuya bodega se transformó en taller secreto. Aún cuelgan herramientas de calidad de los ganchos y sobre el banco descansa un arma a medio terminar que un maestro carpintero nunca acabó.",
    chance: 0.04,
    minLevel: 17,
    cooldownHours: null,
    reward: {
      berries: 32000,
      xp: 6800,
      items: [{ id: "reliquia", qty: 2 }, { id: "botiquin", qty: 1 }],
      weapon: { name: "Cañón de mano del cementerio", kind: "Cañón", atkBonus: 14, description: "Un cañón de mano ensamblado con piezas de mil barcos: pesa como un ancla, pero su estruendo no falla.", basePrice: 8000 },
    },
  },
  {
    id: "skypiea:nubes-de-la-bruma",
    island: "Skypiea",
    place: "El Mirador del Velo",
    title: "El nido de nubes del mirador",
    discovery:
      "Desde el mirador del velo distingues una nube pequeña y densa que no se desplaza con el viento. Al atravesarla encuentras un nido de conchas de impacto y una bolsa de moneda dorada que los cazadores de nubes guardaron para tiempos peores.",
    chance: 0.14,
    minLevel: 15,
    cooldownHours: 36,
    reward: { berries: 2400, xp: 1800, items: [{ id: "reliquia", qty: 1 }] },
  },
  {
    id: "skypiea:camara-de-oro",
    island: "Skypiea",
    place: "Cámara de los Susurros",
    title: "La cámara sellada de las ruinas de oro",
    discovery:
      "Más allá de las obras, una puerta de oro macizo cede al fin y deja ver una cámara de la antigua ciudad. Dentro reposa oro puro, ofrendas de un pueblo desaparecido y una lanza de oración envuelta en gasa.",
    chance: 0.04,
    minLevel: 18,
    cooldownHours: null,
    reward: {
      berries: 40000,
      xp: 10000,
      items: [{ id: "perla", qty: 2 }, { id: "reliquia", qty: 2 }],
      weapon: { name: "Lanza de oro de la cámara", kind: "Lanza", atkBonus: 16, description: "Una lanza ceremonial de oro macizo endurecido, hallada en la ciudad perdida: brillante, pesada y letal.", basePrice: 12000 },
    },
  },
  {
    id: "sabaody:pompas-del-manglar",
    island: "Archipiélago Sabaody",
    place: "Puerto del Manglar 44",
    title: "La pompa que llegó cargada",
    discovery:
      "Una pompa de resina se adhiere a la raíz del manglar 44 con un pequeño bulto en su interior. Al reventarla aparecen unas cuantas monedas, un frasco sellado y una nota en clave que ya nadie quiere entregar.",
    chance: 0.14,
    minLevel: 18,
    cooldownHours: 36,
    reward: { berries: 2800, xp: 3500, items: [{ id: "botiquin", qty: 1 }] },
  },
  {
    id: "sabaody:corazon-de-resina",
    island: "Archipiélago Sabaody",
    place: "Bosque Prohibido de la Resina",
    title: "El corazón de resina",
    discovery:
      "En lo más hondo del bosque prohibido de la resina, un manglar antiguo guarda en el tronco un núcleo dorado del tamaño de un puño. Es resina pura, endurecida durante siglos, y en el mercado de las pompas vale una fortuna.",
    chance: 0.04,
    minLevel: 20,
    cooldownHours: null,
    reward: { berries: 45000, xp: 16000, items: [{ id: "perla", qty: 3 }, { id: "reliquia", qty: 2 }] },
  },
  {
    id: "thriller-bark:tumba-sin-nombre",
    island: "Thriller Bark",
    place: "Cementerio Mayor",
    title: "La ofrenda de la tumba sin nombre",
    discovery:
      "Entre las lápidas del cementerio mayor descubres una losa suelta con ofrendas de todas las islas que fueron robadas junto con sus muertos. Recoges monedas y frascos que todavía huelen a incienso.",
    chance: 0.13,
    minLevel: 16,
    cooldownHours: 36,
    reward: { berries: 2600, xp: 2200, items: [{ id: "sake", qty: 2 }] },
  },
  {
    id: "thriller-bark:aviario-de-mal-aguero",
    island: "Thriller Bark",
    place: "Aviario de Mal Agüero",
    title: "El tesoro que vigilan los cuervos",
    discovery:
      "En un corral del aviario de mal agüero, los cuervos atesoran objetos brillantes en un nido de trapos. Bajo las plumas hay joyas, una perla de gran tamaño y un arma de ceremonia con la empuñadura en forma de garra.",
    chance: 0.04,
    minLevel: 19,
    cooldownHours: null,
    reward: {
      berries: 38000,
      xp: 13000,
      items: [{ id: "perla", qty: 1 }, { id: "elixir", qty: 1 }],
      weapon: { name: "Daga del aviario", kind: "Daga", atkBonus: 15, description: "Una daga de hueso y acero negro con la empuñadura tallada en forma de garra de cuervo.", basePrice: 9500 },
    },
  },
  {
    id: "amazon-lily:jardin-de-las-serpientes",
    island: "Amazon Lily",
    place: "Jardín Secreto de las Herbolarías",
    title: "Las hierbas del jardín olvidado",
    discovery:
      "En un rincón olvidado del jardín secreto de las herbolarías crecen matas de una hierba amarga que las guerreras usan para curar heridas graves. Con paciencia se recolectan suficientes para preparar un buen ungüento.",
    chance: 0.14,
    minLevel: 20,
    cooldownHours: 36,
    reward: { berries: 3000, xp: 6500, items: [{ id: "unguento", qty: 2 }] },
  },
  {
    id: "amazon-lily:santuario-de-serpientes",
    island: "Amazon Lily",
    place: "Santuario de las Serpientes Ancianas",
    title: "La muda de las serpientes ancianas",
    discovery:
      "En el suelo del santuario de las serpientes ancianas yace una muda enorme y perfecta, tan resistente como un cuero curtido, junto a ofrendas de joyas que las guerreras dejan por respeto. Retirar la muda es un honor que pocos consiguen.",
    chance: 0.04,
    minLevel: 23,
    cooldownHours: null,
    reward: {
      berries: 48000,
      xp: 22000,
      items: [{ id: "unguento", qty: 3 }, { id: "perla", qty: 1 }],
      weapon: { name: "Látigo de la muda ancestral", kind: "Látigo", atkBonus: 16, description: "Un látigo trenzado con la muda de una serpiente ancestral: flexible, silencioso y con una punta que silba al cortar el aire.", basePrice: 12000 },
    },
  },

  // ---- Grand Line, mid-game (levels 22-30) ----
  {
    id: "gyojin:mercado-de-la-burbuja",
    island: "Isla Gyojin",
    place: "Arrecife Exterior",
    title: "Las perlas del arrecife exterior",
    discovery:
      "Entre las grietas del arrecife exterior, las conchas jóvenes guardan perlas pequeñas que los pescadores dejan crecer. Con mucho cuidado, y sin dañar el arrecife, puedes recoger algunas ya maduras.",
    chance: 0.13,
    minLevel: 22,
    cooldownHours: 48,
    reward: { berries: 4000, xp: 12000, items: [{ id: "perlasirena", qty: 1 }] },
  },
  {
    id: "gyojin:nucleo-del-arbol",
    island: "Isla Gyojin",
    place: "Archivos de las Mareas",
    title: "El mapa hundido de las mareas",
    discovery:
      "Tras una compuerta de coral de los archivos de las mareas se guarda una carta submarina dibujada sobre piel de pez, con rutas y bancos de perlas nunca publicados. Con ella aparece también un cofre de tesoro de otra era.",
    chance: 0.04,
    minLevel: 25,
    cooldownHours: null,
    reward: {
      berries: 60000,
      xp: 60000,
      items: [{ id: "perlasirena", qty: 3 }, { id: "perla", qty: 2 }],
      weapon: { name: "Tridente de perla negra", kind: "Tridente", atkBonus: 17, description: "Un tridente de coral negro con una perla engastada en el astil: el mar parece obedecerlo, y su filo no se oxida.", basePrice: 15000 },
    },
  },
  {
    id: "punk-hazard:mercado-del-caos",
    island: "Punk Hazard",
    place: "Mercado del Caos",
    title: "El botín bajo el hielo",
    discovery:
      "En el límite entre el fuego y el hielo, una grieta del mercado del caos deja al descubierto una caja que los cazadores dejaron congelada. Todavía se conservan botiquines y monedas, intactos bajo una fina capa de escarcha.",
    chance: 0.12,
    minLevel: 25,
    cooldownHours: 48,
    reward: { berries: 4500, xp: 30000, items: [{ id: "botiquin", qty: 2 }, { id: "elixir", qty: 1 }] },
  },
  {
    id: "punk-hazard:laboratorio-sellado",
    island: "Punk Hazard",
    place: "Laboratorio Sellado",
    title: "La sala que sobrevivió al experimento",
    discovery:
      "Una compuerta de acero del laboratorio sellado cede tras una descarga y deja ver una sala intacta: estantes con viales, un arcón blindado y un arma experimental que nadie se atrevió a probar. Todo huele a frío y a metal.",
    chance: 0.04,
    minLevel: 27,
    cooldownHours: null,
    reward: {
      berries: 70000,
      xp: 110000,
      items: [{ id: "elixir", qty: 3 }, { id: "reliquia", qty: 2 }],
      weapon: { name: "Fusil del laboratorio", kind: "Fusil", atkBonus: 18, description: "Un fusil experimental de acero frío hallado en la sala sellada: de cañón largo, con un mecanismo que nadie más sabe reparar.", basePrice: 18000 },
    },
  },
  {
    id: "whole-cake:bosque-de-galletas",
    island: "Whole Cake Island",
    place: "Bosque de Galletas Recias",
    title: "La caja de dulces de emergencia",
    discovery:
      "En el hueco de una galleta gigante del bosque hay una caja metálica con dulces, raciones de emergencia y monedas de un patrullero desertor. Todo huele a caramelo tostado y a azúcar añeja.",
    chance: 0.13,
    minLevel: 28,
    cooldownHours: 48,
    reward: { berries: 5000, xp: 45000, items: [{ id: "banquete", qty: 2 }] },
  },
  {
    id: "whole-cake:tuneles-de-crema",
    island: "Whole Cake Island",
    place: "Las Tuberías de Crema",
    title: "La receta prohibida bajo las tuberías",
    discovery:
      "Bajo las tuberías de crema, un túnel oculto conduce a una cámara fría donde se guardan recetas, frascos de esencia rara y una fruta que huele a fruta de otro mundo. Es un tesoro de pastelero para quien sepa sacarlo sin que suenen las alarmas.",
    chance: 0.04,
    minLevel: 31,
    cooldownHours: null,
    reward: { berries: 90000, xp: 300000, items: [{ id: "estrella", qty: 1 }, { id: "banquete", qty: 3 }], fruit: "Kaori Kaori no Mi" },
  },
  {
    id: "marineford:cantina-de-suboficiales",
    island: "Marineford",
    place: "La Cantina de Suboficiales",
    title: "La caja de la cantina",
    discovery:
      "Bajo la barra de la cantina de suboficiales hay una caja que la guardia de intendencia no alcanzó a registrar tras la guerra. Contiene la paga de una semana, raciones de calidad y un botiquín completo.",
    chance: 0.12,
    minLevel: 26,
    cooldownHours: 48,
    reward: { berries: 4500, xp: 30000, items: [{ id: "botiquin", qty: 2 }, { id: "racion", qty: 2 }] },
  },
  {
    id: "marineford:celda-olvidada",
    island: "Marineford",
    place: "Los Muros Exteriores",
    title: "La celda de los grafitis",
    discovery:
      "Detrás de los muros exteriores un pasadizo de mantenimiento conduce a una celda que nadie ha vuelto a limpiar. En las paredes quedan grafitis de la guerra, y bajo una losa hay un alijo con un arma que un prisionero logró esconder.",
    chance: 0.04,
    minLevel: 29,
    cooldownHours: null,
    reward: {
      berries: 80000,
      xp: 200000,
      items: [{ id: "elixir", qty: 2 }, { id: "papeles", qty: 2 }],
      weapon: { name: "Katana de la celda olvidada", kind: "Katana", atkBonus: 18, description: "Una katana escondida bajo una losa de la celda: la vaina está rayada, pero la hoja aún corta el aire con limpieza.", basePrice: 20000 },
    },
  },
  {
    id: "dressrosa:tuneles-del-coliseo",
    island: "Dressrosa",
    place: "Coliseo Corrida",
    title: "El botín de los túneles del coliseo",
    discovery:
      "En los túneles bajo el coliseo corrida, entre marionetas rotas, hay un cofre que sobró de las apuestas. Contiene fichas cobrables, monedas y un poco de licor de los palcos.",
    chance: 0.12,
    minLevel: 28,
    cooldownHours: 48,
    reward: { berries: 5500, xp: 45000, items: [{ id: "sake", qty: 3 }] },
  },
  {
    id: "dressrosa:acantilados-del-este",
    island: "Dressrosa",
    place: "Acantilados del Este y Puerto Escondido",
    title: "El alijo del puerto escondido",
    discovery:
      "Una cueva del puerto escondido guarda un cargamento que nadie reclamó: cajas de mercancía de contrabando, armas de tecnología extraña y un extraño fruto guardado en hielo. Todo lo dejaron ahí antes de que la isla cambiara de manos.",
    chance: 0.04,
    minLevel: 31,
    cooldownHours: null,
    reward: { berries: 90000, xp: 350000, items: [{ id: "reliquia", qty: 3 }, { id: "elixir", qty: 2 }], fruit: "Ami Ami no Mi" },
  },
  {
    id: "kuraigana:bosque-de-plumas",
    island: "Isla Kuraigana",
    place: "El Bosque de Plumas Susurrantes",
    title: "La pluma con recado",
    discovery:
      "Entre las plumas del bosque susurrante hay un nido enorme con objetos brillantes que los cuervos fueron acumulando durante años. Sacas monedas antiguas, una botella de licor añejo y un vendaje limpio.",
    chance: 0.12,
    minLevel: 27,
    cooldownHours: 48,
    reward: { berries: 5000, xp: 38000, items: [{ id: "sake", qty: 2 }, { id: "vendaje", qty: 2 }] },
  },
  {
    id: "kuraigana:barco-de-la-niebla",
    island: "Isla Kuraigana",
    place: "Puerto de los Suspiros",
    title: "El barco pirata de la niebla",
    discovery:
      "La niebla se abre un instante y en el puerto de los suspiros aparece el casco de un barco pirata encallado, que solo los cuervos conocen. Su bodega guarda un tesoro entero: joyas, una espada de dueño desconocido y un extraño fruto conservado en cera.",
    chance: 0.04,
    minLevel: 30,
    cooldownHours: null,
    reward: {
      berries: 85000,
      xp: 300000,
      items: [{ id: "reliquia", qty: 3 }],
      weapon: { name: "Espada de la niebla", kind: "Katana", atkBonus: 20, description: "Una espada antigua recuperada de un barco encallado: la hoja está cubierta de un rocío que nunca se seca.", basePrice: 26000 },
      fruit: "Hone Hone no Mi",
    },
  },
  {
    id: "toro-negro:fumarolas",
    island: "Isla del Toro Negro",
    place: "Las Fumarolas",
    title: "Veta de mineral volcánico",
    discovery:
      "En el borde de las fumarolas, una veta de mineral negro brilla a través de la ceniza caliente. Con cuidado y buenas herramientas se extrae una muestra que los herreros de la isla pagarán muy bien.",
    chance: 0.12,
    minLevel: 30,
    cooldownHours: 48,
    reward: { berries: 6500, xp: 120000, items: [{ id: "reliquia", qty: 2 }] },
  },
  {
    id: "toro-negro:libros-negros",
    island: "Isla del Toro Negro",
    place: "Archivos de los Libros Negros",
    title: "El depósito de la tripulación rival",
    discovery:
      "En un cajón sin etiquetas de los archivos de los libros negros, una llave abre un compartimento con el tesoro de una tripulación rival aniquilada hace años: oro, provisiones de guerra y un hacha de guerra forjada en la isla.",
    chance: 0.04,
    minLevel: 33,
    cooldownHours: null,
    reward: {
      berries: 100000,
      xp: 450000,
      items: [{ id: "estrella", qty: 2 }, { id: "perla", qty: 2 }],
      weapon: { name: "Hacha de basalto del toro", kind: "Hacha", atkBonus: 20, description: "Un hacha de basalto fundido en el Yunque del Fuego: la hoja negra y opaca parece absorber la luz.", basePrice: 30000 },
    },
  },
  {
    id: "abismo:galeria-de-perlas",
    island: "Isla Abismo",
    place: "Galería de las Perlas Abisales",
    title: "La perla con símbolos",
    discovery:
      "En una veta de la galería de perlas abisales, una perla oscura con un patrón interno parece completar los símbolos que la isla custodia. El brillo que emite se apaga en cuanto la sacas del agua, pero su valor sigue intacto.",
    chance: 0.12,
    minLevel: 38,
    cooldownHours: 60,
    reward: { berries: 12000, xp: 700000, items: [{ id: "perla", qty: 2 }] },
  },
  {
    id: "abismo:coral-negro",
    island: "Isla Abismo",
    place: "Cámara de las Aguas",
    title: "La sumersión más larga",
    discovery:
      "Durante la sumersión más larga de la isla, las corrientes abren una galería de coral negro en la cámara de las aguas. Dentro, a salvo de la presión, queda un tesoro de los primeros custodios y un fruto de piel viscosa que nadie ha reclamado.",
    chance: 0.03,
    minLevel: 41,
    cooldownHours: null,
    reward: {
      berries: 120000,
      xp: 1500000,
      items: [{ id: "perla", qty: 3 }, { id: "elixir", qty: 3 }],
      fruit: "Tako Tako no Mi: Modelo Pulpo",
    },
  },

  // ---- New World and endgame (levels 30+) ----
  {
    id: "cementerio:cementerio-de-los-sin-nombre",
    island: "Isla Cementerio",
    place: "Cementerio de los Sin Nombre",
    title: "El fondo de una tumba abierta",
    discovery:
      "Entre las tumbas sin nombre, una lápida se ha hundido hasta dejar ver una caja de hierro bajo tierra. Es el equipaje de un pirata al que enterraron con sus ahorros, y sus deudas.",
    chance: 0.12,
    minLevel: 30,
    cooldownHours: 48,
    reward: { berries: 7000, xp: 130000, items: [{ id: "reliquia", qty: 2 }] },
  },
  {
    id: "cementerio:guarida-de-las-bestias",
    island: "Isla Cementerio",
    place: "La Guarida de las Bestias",
    title: "Lo que late en las cavernas",
    discovery:
      "En lo más hondo de la guarida de las bestias, entre huesos y niebla, hay una cámara excavada a la fuerza. Contiene un botín robado a los grandes poderes del mundo: joyas, medicinas raras y un arma de gran calidad.",
    chance: 0.03,
    minLevel: 34,
    cooldownHours: null,
    reward: {
      berries: 95000,
      xp: 500000,
      items: [{ id: "estrella", qty: 2 }, { id: "perla", qty: 2 }],
      weapon: { name: "Guadaña de las cavernas", kind: "Guadaña", atkBonus: 20, description: "Una guadaña de acero negro hallada en la cámara de las bestias: el mango está gastado por manos que nunca temieron a la muerte.", basePrice: 32000 },
    },
  },
  {
    id: "enies-lobby:corredores-de-celdas",
    island: "Enies Lobby",
    place: "Los Corredores de Celdas",
    title: "Los efectos confiscados",
    discovery:
      "Al fondo de los corredores de celdas hay una taquilla de efectos confiscados a presos que jamás volverán. Guarda monedas, papeles y algún arma corta, sin inventario que la reclame.",
    chance: 0.12,
    minLevel: 35,
    cooldownHours: 48,
    reward: { berries: 8000, xp: 180000, items: [{ id: "papeles", qty: 2 }, { id: "botiquin", qty: 2 }] },
  },
  {
    id: "enies-lobby:arbol-marchito",
    island: "Enies Lobby",
    place: "El Árbol del Conocimiento Marchito",
    title: "La savia negra del árbol",
    discovery:
      "En las raíces del árbol marchito, un nicho guarda frascos de savia negra como la tinta y un arcón de expedientes robados. Lo que allí duerme no sirve para leer, pero sí para pagar muy bien a quien no haga preguntas.",
    chance: 0.03,
    minLevel: 38,
    cooldownHours: null,
    reward: {
      berries: 110000,
      xp: 900000,
      items: [{ id: "reliquia", qty: 3 }, { id: "elixir", qty: 2 }],
      weapon: { name: "Bastón del juicio", kind: "Bo", atkBonus: 19, description: "Un bastón negro de madera del árbol marchito: ligero, pulido por manos de jueces y rematado en hierro.", basePrice: 28000 },
    },
  },
  {
    id: "wano:aguardiente-de-la-cascada",
    island: "País de Wano",
    place: "Aguardiente de la Cascada",
    title: "El barril del sake añejo",
    discovery:
      "En la trastienda de la taberna, un barril de sake de arroz añejo lleva años fermentando bajo una manta. Los lugareños permiten tomar una parte a quien la sepa apreciar, junto con una bolsa de monedas de agradecimiento.",
    chance: 0.13,
    minLevel: 32,
    cooldownHours: 48,
    reward: { berries: 7500, xp: 200000, items: [{ id: "sakewano", qty: 3 }] },
  },
  {
    id: "wano:santuario-del-amanecer",
    island: "País de Wano",
    place: "Santuario del Amanecer",
    title: "La máscara del santuario profanado",
    discovery:
      "Bajo el suelo de un santuario del amanecer profanado se esconde una cámara con máscaras rotas y ofrendas que los guardianes salvaron antes de la ocupación. Junto a ellas aguarda una hoja envuelta en seda y una fruta extraña conservada en laca.",
    chance: 0.03,
    minLevel: 35,
    cooldownHours: null,
    reward: {
      berries: 120000,
      xp: 700000,
      items: [{ id: "sakewano", qty: 3 }, { id: "estrella", qty: 1 }],
      weapon: { name: "Katana del santuario del amanecer", kind: "Katana", atkBonus: 22, description: "Una katana envuelta en seda que los guardianes salvaron de la profanación: la hoja, clara como el alba, parece cortar la sombra.", basePrice: 36000 },
      fruit: "Uroko Uroko no Mi",
    },
  },
  {
    id: "elbaf:hacha-y-cantaro",
    island: "Elbaf",
    place: "'El Hacha y el Cántaro'",
    title: "La reserva bajo el mostrador",
    discovery:
      "En un rincón de la taberna, tras un barril de cerveza del tamaño de una casa, hay un arcón donde los gigantes guardan sus botines de caza. Contiene monedas enormes, banquetes envasados y un cántaro de licor fuerte.",
    chance: 0.12,
    minLevel: 34,
    cooldownHours: 48,
    reward: { berries: 8500, xp: 260000, items: [{ id: "banquete", qty: 3 }, { id: "sake", qty: 2 }] },
  },
  {
    id: "elbaf:piedras-del-juramento",
    island: "Elbaf",
    place: "Bosque de los Susurros",
    title: "El origen de la promesa olvidada",
    discovery:
      "En lo más profundo del bosque de los susurros, entre raíces del tamaño de mástiles, un altar de piedra guarda el origen de la promesa antigua: un hacha ceremonial, joyas de gigante y un fruto de un mundo prehistórico.",
    chance: 0.03,
    minLevel: 37,
    cooldownHours: null,
    reward: {
      berries: 130000,
      xp: 900000,
      items: [{ id: "banquete", qty: 3 }, { id: "perla", qty: 2 }],
      weapon: { name: "Hacha del juramento", kind: "Hacha", atkBonus: 22, description: "Un hacha ceremonial de gigante reducida a manos humanas: pesada de historia, con runas del juramento grabadas en la hoja.", basePrice: 38000 },
      fruit: "Ryu Ryu no Mi: Modelo Triceratops",
    },
  },
  {
    id: "zou:jardin-de-los-humores",
    island: "Zou",
    place: "El Jardín de los Humores",
    title: "La raíz medicinal del jardín",
    discovery:
      "En un bancal al fondo del jardín de los humores crece una raíz que los curanderos de Zou usan para preparar infusiones. Cortada en su punto, sirve para reponer aguante y aliento a quien la tome.",
    chance: 0.12,
    minLevel: 30,
    cooldownHours: 48,
    reward: { berries: 6500, xp: 130000, items: [{ id: "infusion", qty: 3 }] },
  },
  {
    id: "zou:enramada-del-archivo",
    island: "Zou",
    place: "La Enramada del Archivo",
    title: "El nicho tras el archivo",
    discovery:
      "Detrás de la enramada del archivo, una losa marcada con garras oculta un nicho donde los antiguos habitantes guardaron tesoros del pueblo. Hay joyas, medicinas, y un fruto de aroma salvaje conservado en salmuera.",
    chance: 0.03,
    minLevel: 33,
    cooldownHours: null,
    reward: {
      berries: 100000,
      xp: 500000,
      items: [{ id: "infusion", qty: 3 }, { id: "reliquia", qty: 3 }],
      fruit: "Inu Inu no Mi: Modelo Chacal",
    },
  },
  {
    id: "egghead:cubo-de-chatarra",
    island: "Isla Egghead",
    place: "El Cubo de Chatarra",
    title: "El contenedor de prototipos",
    discovery:
      "Entre la chatarra descartada, un contenedor sin vigilancia esconde prototipos de laboratorio, baterías y componentes valiosos que nadie quiso reciclar. Todo sigue funcionando, aunque ya no interesa a los ingenieros.",
    chance: 0.12,
    minLevel: 36,
    cooldownHours: 60,
    reward: { berries: 12000, xp: 500000, items: [{ id: "elixir", qty: 2 }, { id: "botiquin", qty: 2 }] },
  },
  {
    id: "egghead:sala-crisalida",
    island: "Isla Egghead",
    place: "Sala de Proyectos 'Crisálida'",
    title: "El proyecto que aún respira",
    discovery:
      "Una compuerta en la sala de proyectos crisálida se abre al reiniciar un panel apagado. Dentro dormita un proyecto de laboratorio: un arma de diseño imposible, componentes valiosos y un extraño fruto que se conserva entre cristales.",
    chance: 0.03,
    minLevel: 39,
    cooldownHours: null,
    reward: {
      berries: 140000,
      xp: 2500000,
      items: [{ id: "elixir", qty: 3 }, { id: "estrella", qty: 2 }],
      weapon: { name: "Rifle de la crisálida", kind: "Fusil", atkBonus: 22, description: "Un rifle de diseño imposible salido de la sala crisálida: la culata es de un metal que no conoce el óxido.", basePrice: 40000 },
      fruit: "Pazuru Pazuru no Mi",
    },
  },
  {
    id: "impel-down:cocina-nivel-4",
    island: "Impel Down",
    place: "Nivel 4",
    title: "La despensa de la cocina infernal",
    discovery:
      "En un rincón del nivel de las cocinas, tras las calderas, una despensa olvidada guarda víveres de guardia y frascos de licor que se usaban para pagar favores. Conviene llevárselo rápido, antes de que suene alguna campana.",
    chance: 0.1,
    minLevel: 45,
    cooldownHours: 72,
    reward: { berries: 20000, xp: 5000000, items: [{ id: "banquete", qty: 3 }, { id: "botiquin", qty: 3 }] },
  },
  {
    id: "impel-down:nivel-6",
    island: "Impel Down",
    place: "Nivel 6",
    title: "El tesoro del prisionero del fondo",
    discovery:
      "En una cámara de contención vacía del nivel 6, unos ladrillos sueltos ocultan las pertenencias de un prisionero que sabía dónde había un tesoro hundido. Hay mapas del fondo del mar, una fortuna en perlas y un arma que sobrevivió a mil registros.",
    chance: 0.03,
    minLevel: 46,
    cooldownHours: null,
    reward: {
      berries: 145000,
      xp: 9000000,
      items: [{ id: "perla", qty: 3 }, { id: "mapa", qty: 3 }],
      weapon: { name: "Cadena del nivel seis", kind: "Cadena", atkBonus: 22, description: "Una cadena de eslabones oscuros rescatada de una celda del nivel 6: fría al tacto, pesada y capaz de partir hueso.", basePrice: 42000 },
    },
  },
  {
    id: "mary-geoise:plaza-sagrada",
    island: "Mary Geoise",
    place: "Plaza Sagrada",
    title: "Ofrendas bajo la fuente",
    discovery:
      "En un rincón de la plaza sagrada, una reja de bronce deja ver ofrendas que los sirvientes arrojan con miedo a la fuente: monedas de oro, joyas menores y hasta medicinas. Nadie se atreve a recogerlas porque cae cerca la mirada de los guardias.",
    chance: 0.1,
    minLevel: 42,
    cooldownHours: 72,
    reward: { berries: 25000, xp: 4000000, items: [{ id: "perla", qty: 1 }, { id: "elixir", qty: 1 }] },
  },
  {
    id: "mary-geoise:registros-perdidos",
    island: "Mary Geoise",
    place: "Los Registros Perdidos",
    title: "El plano de los túneles de servicio",
    discovery:
      "Tras una estantería falsa de los registros perdidos hay un plano de los túneles de servicio y, a su lado, un fardo de valores robados por servidores que huyeron. Es un botín peligroso, pero cuantioso.",
    chance: 0.03,
    minLevel: 44,
    cooldownHours: null,
    reward: {
      berries: 150000,
      xp: 8000000,
      items: [{ id: "reliquia", qty: 5 }, { id: "papeles", qty: 3 }],
      weapon: { name: "Espada de los túneles de servicio", kind: "Katana", atkBonus: 22, description: "Una espada delgada, ligera y sin adornos, de las que se esconden bajo un abrigo de servicio: silenciosa y precisa.", basePrice: 45000 },
    },
  },
  {
    id: "laugh-tale:cataratas-del-silencio",
    island: "Laugh Tale",
    place: "Cataratas del Silencio",
    title: "Las risas tras la cascada",
    discovery:
      "Tras el velo de las cataratas del silencio hay una cueva donde la piedra parece haberse quedado quieta a mitad de una carcajada. Sobre un saliente reposa una bolsa de monedas antiguas y raciones que no han perdido su sabor.",
    chance: 0.1,
    minLevel: 50,
    cooldownHours: 72,
    reward: { berries: 30000, xp: 20000000, items: [{ id: "banquete", qty: 3 }, { id: "estrella", qty: 1 }] },
  },
  {
    id: "laugh-tale:arca-de-las-sombras",
    island: "Laugh Tale",
    place: "Arca de las Sombras",
    title: "Lo que guarda el arca",
    discovery:
      "En el arca de las sombras, un cofre de piedra parece esperar a quien merezca abrirlo. Dentro aguardan tesoros de otra era, un fruto que ningún libro registra y un arma que ríe con quien la empuña.",
    chance: 0.03,
    minLevel: 51,
    cooldownHours: null,
    reward: {
      berries: 150000,
      xp: 40000000,
      items: [{ id: "perla", qty: 5 }, { id: "estrella", qty: 2 }],
      weapon: { name: "Hoja de la risa", kind: "Katana", atkBonus: 22, description: "Una katana hallada en el arca: la hoja refleja una sonrisa que no es la de quien la mira, y corta con la ligereza de una carcajada.", basePrice: 50000 },
      fruit: "Gyaku Gyaku no Mi",
    },
  },
  {
    id: "g8-navarone:muelle-de-pescadores",
    island: "G-8 Navarone",
    place: "Muelle de Pescadores",
    title: "La nasa del barco fantasma",
    discovery:
      "Una nasa vieja del muelle de pescadores trae de las aguas bajas un pequeño arcón sin marcas. Los pescadores lo atribuyen al barco sin luces visto entre la niebla, y su contenido son monedas, un botiquín y un vendaje limpio.",
    chance: 0.13,
    minLevel: 10,
    cooldownHours: 36,
    reward: { berries: 1500, xp: 350, items: [{ id: "botiquin", qty: 1 }, { id: "vendaje", qty: 2 }] },
  },
  {
    id: "g8-navarone:tuneles-de-desague",
    island: "G-8 Navarone",
    place: "Calabozos de Máxima Seguridad",
    title: "El zurrón de los desagües",
    discovery:
      "Los túneles de desagüe más antiguos de los calabozos, marcados por zarpazos gigantes, esconden un zurrón atascado entre las rejas. Es el botín de un fugado que no llegó lejos, con monedas, ganzúas y una pistola.",
    chance: 0.04,
    minLevel: 13,
    cooldownHours: null,
    reward: {
      berries: 24000,
      xp: 2600,
      items: [{ id: "papeles", qty: 1 }, { id: "botiquin", qty: 2 }],
      weapon: { name: "Pistola de los desagües", kind: "Pistola", atkBonus: 13, description: "Una pistola de repetición rescatada de un desagüe: huele a salitre y, pese a todo, sigue disparando limpio.", basePrice: 6500 },
    },
  },
  {
    id: "banaro:plaza-del-silencio",
    island: "Isla Banaro",
    place: "La Plaza del Silencio",
    title: "El anillo bajo las cenizas",
    discovery:
      "En la plaza del silencio, bajo capas de ceniza fina, una losa cede y deja ver un cofre pequeño. Contiene joyas de los artesanos de antes de la destrucción y unas monedas que se salvaron del fuego.",
    chance: 0.13,
    minLevel: 14,
    cooldownHours: 36,
    reward: { berries: 2200, xp: 1500, items: [{ id: "reliquia", qty: 1 }] },
  },
  {
    id: "banaro:bosque-de-postes",
    island: "Isla Banaro",
    place: "El Bosque de Postes",
    title: "El testigo del bosque quemado",
    discovery:
      "En el bosque de postes, un tronco carbonizado más grande que los demás guarda en su hueco un tesoro de antes de la batalla. Al sacarlo, aparece un arma de herrero local aún sin templar y un fajo de valores resistente al fuego.",
    chance: 0.04,
    minLevel: 17,
    cooldownHours: null,
    reward: {
      berries: 32000,
      xp: 8000,
      items: [{ id: "reliquia", qty: 2 }, { id: "elixir", qty: 1 }],
      weapon: { name: "Espada del bosque de postes", kind: "Katana", atkBonus: 14, description: "Una espada forjada en Banaro antes de la batalla y sacada de un tronco quemado: ennegrecida, pero de filo inusualmente vivo.", basePrice: 8000 },
    },
  },
  {
    id: "rusukaina:playa-de-los-naufragios",
    island: "Isla Rusukaina",
    place: "La Playa de los Naufragios",
    title: "Los restos de la última tormenta",
    discovery:
      "Tras la tormenta, la playa de los naufragios amanece cubierta de cajas y barriles arrastrados por el mar. Entre los restos aprovechables hay raciones, sake y una bolsa de monedas empapada.",
    chance: 0.13,
    minLevel: 18,
    cooldownHours: 36,
    reward: { berries: 2800, xp: 3500, items: [{ id: "racion", qty: 2 }, { id: "sake", qty: 2 }] },
  },
  {
    id: "rusukaina:caleta-del-contrabandista",
    island: "Isla Rusukaina",
    place: "La Caleta del Contrabandista",
    title: "El tesoro del capitán hundido",
    discovery:
      "Cuando la marea baja en la caleta del contrabandista queda al aire la proa de una nave hundida hace décadas. En su cofre de cubierta sigue el tesoro del capitán, sellado con brea y con un arma de mano envuelta en piel.",
    chance: 0.04,
    minLevel: 21,
    cooldownHours: null,
    reward: {
      berries: 42000,
      xp: 20000,
      items: [{ id: "perla", qty: 2 }, { id: "reliquia", qty: 1 }],
      weapon: { name: "Sable de la caleta", kind: "Sable", atkBonus: 16, description: "Un sable de capitán envuelto en piel curtida: la hoja conserva la sal del mar y la guarda tiene grabadas estrellas.", basePrice: 12000 },
    },
  },
  {
    id: "kamabakka:huertos-de-la-extravagancia",
    island: "Reino Kamabakka",
    place: "Huertos de la Extravagancia",
    title: "La cosecha extravagante",
    discovery:
      "Entre las hileras de los huertos de la extravagancia, un bancal fuera de todo diseño ha dado una cosecha absurda: frutos enormes, hierbas medicinales y un frasco con extractos que los cocineros usan de reserva.",
    chance: 0.14,
    minLevel: 12,
    cooldownHours: 36,
    reward: { berries: 1800, xp: 700, items: [{ id: "unguento", qty: 1 }, { id: "racion", qty: 2 }] },
  },
  {
    id: "kamabakka:almacen-de-disfraces",
    island: "Reino Kamabakka",
    place: "Almacén de Disfraces y Disimulos",
    title: "El baúl de los disfraces perfectos",
    discovery:
      "Al fondo del almacén de disfraces, un baúl con doble fondo esconde papeles falsos impecables, joyas de atrezo que en realidad son de verdad y un arma diminuta camuflada en un abanico.",
    chance: 0.04,
    minLevel: 15,
    cooldownHours: null,
    reward: {
      berries: 27000,
      xp: 4500,
      items: [{ id: "papeles", qty: 3 }, { id: "botiquin", qty: 1 }],
      weapon: { name: "Abanico de los disimulos", kind: "Abanico", atkBonus: 13, description: "Un abanico de varillas de acero disfrazado de complemento: pliegues afilados y una empuñadura que no delata su uso.", basePrice: 7000 },
    },
  },
  {
    id: "hachinosu:mercado-de-las-sombras",
    island: "Hachinosu",
    place: "El Mercado de las Sombras",
    title: "El alijo del mercado negro",
    discovery:
      "Bajo una lona rota del mercado de las sombras hay un alijo que un tratante dejó a medio vender: sake, medicinas y una bolsa de monedas de mala procedencia. Nadie lo reclama porque nadie quiere admitir que es suyo.",
    chance: 0.12,
    minLevel: 32,
    cooldownHours: 48,
    reward: { berries: 7500, xp: 180000, items: [{ id: "sake", qty: 3 }, { id: "botiquin", qty: 2 }] },
  },
  {
    id: "hachinosu:calabozos-susurrantes",
    island: "Hachinosu",
    place: "Los Calabozos Susurrantes",
    title: "La celda secreta bajo los calabozos",
    discovery:
      "Bajo los calabozos susurrantes, una celda oculta guarda el tesoro de un antiguo almirante que nunca llegó a gastarlo: joyas, mapas y un fruto de veneno conservado entre paños. La reja de entrada lleva años sin engrasar.",
    chance: 0.03,
    minLevel: 35,
    cooldownHours: null,
    reward: {
      berries: 110000,
      xp: 700000,
      items: [{ id: "reliquia", qty: 3 }, { id: "elixir", qty: 2 }],
      fruit: "Doku Doku Nuru no Mi",
    },
  },
  {
    id: "nuevo-marineford:archivos-del-fenix",
    island: "Nuevo Marineford",
    place: "Archivos del Fénix",
    title: "Los poneglifos falsos",
    discovery:
      "Entre los legajos de los archivos del fénix hay un cajón forrado de plomo con copias falsas de inscripciones antiguas, hechas con una precisión asombrosa. Los coleccionistas pagan bien por ellas, aunque ninguna diga la verdad.",
    chance: 0.12,
    minLevel: 30,
    cooldownHours: 48,
    reward: { berries: 6500, xp: 120000, items: [{ id: "reliquia", qty: 2 }, { id: "papeles", qty: 1 }] },
  },
  {
    id: "nuevo-marineford:campo-hierro-nuevo",
    island: "Nuevo Marineford",
    place: "Campo de Entrenamiento 'Hierro Nuevo'",
    title: "La armería del campo de entrenamiento",
    discovery:
      "Bajo el suelo del campo de entrenamiento hierro nuevo, una trampilla oxidada conduce a una armería para reclutas que quedó fuera de las cuentas. Hay armas bien mantenidas, botiquines de campaña y una bolsa con la paga sin cobrar.",
    chance: 0.03,
    minLevel: 34,
    cooldownHours: null,
    reward: {
      berries: 95000,
      xp: 450000,
      items: [{ id: "botiquin", qty: 3 }, { id: "elixir", qty: 2 }],
      weapon: { name: "Sable del campo hierro nuevo", kind: "Sable", atkBonus: 20, description: "Un sable de reclutas de élite guardado con esmero: acero sobrio, equilibrio perfecto y ni un solo adorno.", basePrice: 30000 },
    },
  },
  ...KAIROS_SECRETS
];
