// Special recruits: original residents with a story of their own who only join a crew that meets a hand-written condition.
// The seed upserts them by name like any other resident; the condition is checked by engine/special-recruit.ts.
import type { SpecialRecruitDef } from "../engine/special-recruit";
import type { SeedRosterEntry } from "./island-npcs";

export type SpecialRecruitEntry = SeedRosterEntry & { recruit: SpecialRecruitDef };

type Attrs = SpecialRecruitDef["attrs"];
const at = (strength: number, agility: number, durability: number, willpower: number, intellect: number): Attrs => ({ strength, agility, durability, willpower, intellect });

function sp(
  island: string,
  slug: string,
  name: string,
  title: string,
  category: string,
  level: number,
  description: string,
  personality: string,
  weapon: string | null,
  recruit: SpecialRecruitDef,
): SpecialRecruitEntry {
  return { island, slot: `sp-${slug}`, name, title, category, level, description, personality, weapon, abilities: recruit.abilities, recruit };
}

export const SPECIAL_RECRUITS: SpecialRecruitEntry[] = [
  sp(
    "Pueblo Foosha", "tamsin-brea", "Tamsin Brea", "Cartógrafa sin barco del Muelle de los Suspiros", "civilian", 3,
    "Una mujer flaca de manos manchadas de tinta que dibuja cartas de cabotaje para los pescadores a cambio de pescado seco. Lleva un cuaderno atado al cinturón y mira el horizonte como quien mira una puerta cerrada.",
    "Callada, precisa y terca. Corrige los mapas ajenos sin pedir permiso y no soporta que se le mienta sobre una corriente.",
    "Compás de latón y un puñal de marinero",
    {
      role: "Navegante", epithet: "La del mapa sin costa",
      abilities: ["Lee el mar y el clima", "Traza rutas de cabotaje", "Nudos de emergencia", "Compás de latón"],
      attrs: at(8, 22, 10, 20, 28),
      lore: "Dibujó las cartas de todos los pescadores del Muelle de los Suspiros hasta que un patrón le quitó el barco y se quedó con su nombre en los mapas. Desde entonces no quiere servir a nadie que no navegue de verdad hacia mar abierto. Se va con la primera bandera pirata que le ofrezca un rumbo propio y un pago digno.",
      hint: "Solo se embarca con una tripulación pirata que ya haya salido a mar abierto y pueda pagarle un adelanto.",
      condition: { minLevel: 3, factions: ["PIRATE"], berries: 6_000 },
    },
  ),
  sp(
    "Cuartel Marine G-5", "odalys-brenn", "Odalys Brenn", "Médica de la Enfermería del cuartel", "marine", 6,
    "Una sargento de ojeras profundas que cose heridas hasta bien entrada la noche en la Enfermería. Los reclutas le tienen miedo y le deben la vida a partes iguales.",
    "Seca, impaciente y sorprendentemente amable con los que sangran. Odia el papeleo más que a los piratas.",
    "Instrumental de cirugía y una pistola de servicio",
    {
      role: "Médica", epithet: "La sargento de las suturas",
      abilities: ["Primeros auxilios", "Estabiliza a un aliado", "Cirugía de campo", "Triaje bajo fuego"],
      attrs: at(12, 16, 18, 30, 30),
      lore: "Lleva años en la Enfermería del cuartel curando a soldados a los que la Marina no ascendió ni recordó. Está harta de que el mérito se lo lleven quienes nunca pisaron el Patio de Instrucción. Solo sigue a un Marine que haya demostrado con hechos que protege a su gente antes que a su rango.",
      hint: "Solo acompaña a un Marine con un nombre ya hecho entre sus compañeros de armas.",
      condition: { minLevel: 6, factions: ["MARINE"], minNotoriety: 120 },
    },
  ),
  sp(
    "Isla Baltigo", "ruvel-hasp", "Ruvel Hasp", "Historiador clandestino de los Archivos de Vellum", "other", 6,
    "Un hombre encorvado de barba descuidada que copia libros prohibidos a mano en los Archivos de Vellum, siempre con una lámpara tapada. Entre el polvo y las hojas sueltas parece más vivo que fuera de ellos.",
    "Nervioso, erudito y leal hasta la médula a la causa. Habla bajo y cita fechas de memoria.",
    "Bastón de puño de hierro",
    {
      role: "Historiador", epithet: "El que copia lo que el Gobierno quemó",
      abilities: ["Descifra escrituras", "Conoce el mundo", "Punto débil del enemigo", "Falsifica documentos"],
      attrs: at(8, 14, 10, 32, 38),
      lore: "Copió a escondidas en los Archivos de Vellum lo que el Gobierno Mundial quiso borrar y ha perdido a media biblioteca por ello. No confía en corsarios ni en mercenarios: solo entrega su saber y su pluma al Ejército Revolucionario, y únicamente a quien ya haya arriesgado algo por la causa.",
      hint: "Solo se une a un revolucionario que ya haya mostrado lealtad a la causa.",
      condition: { minLevel: 6, factions: ["REVOLUTIONARY"], minNotoriety: 100 },
    },
  ),
  sp(
    "Isla Gecko", "hessa-varn", "Hessa Varn", "Rastreadora de cobros del Rincón de Flora", "other", 5,
    "Una cazadora curtida de cara ancha y mirada de pájaro, siempre con el cartel del día doblado en el bolsillo. En el Fogón Dorado paga las rondas con propinas de recompensa y no acepta preguntas.",
    "Práctica, cínica y muy cuidadosa con su palabra: nunca promete lo que no cobra.",
    "Ballesta de repetición y redes con plomos",
    {
      role: "Francotiradora", epithet: "La que nunca falla el cobro",
      abilities: ["Tiro certero", "Disparo de cobertura", "Rastreo de fugitivos", "Red de captura"],
      attrs: at(12, 26, 14, 24, 20),
      lore: "Trabajó sola durante años en los Muelles Principales, hasta que un cobro mal pagado le enseñó que la Oficina del Tablón no siempre juega limpio. No quiere banderas ni causas, solo compañeros que sepan repartir el botín y guardar un secreto. Únicamente sigue a otro cazador de recompensas que ya tenga fama en el gremio.",
      hint: "Solo trabaja con un cazador de recompensas que ya tenga fama en el gremio.",
      condition: { minLevel: 5, factions: ["BOUNTY_HUNTER"], minNotoriety: 110 },
    },
  ),
  sp(
    "Villa Shimotsuki", "kaede-torimune", "Kaede Torimune", "Maestra de esgrima del Dojo Shimotsuki", "civilian", 8,
    "Una espadachina de mediana edad con una cicatriz limpia que le cruza la palma. Enseña con paciencia infinita en el Dojo Shimotsuki y se niega a cortar a nadie que no haya desenvainado primero.",
    "Serena, exigente y con un humor seco que solo asoma tras un buen trago.",
    "Katana de filo largo",
    {
      role: "Espadachina", epithet: "La del corte que no se ve",
      styleId: "ittoryu",
      abilities: ["Iai Giri", "Guardia cerrada", "Corte doble", "Contragolpe sereno"],
      attrs: at(24, 22, 16, 30, 16),
      lore: "Enseña esgrima en el Dojo Shimotsuki desde que su maestro murió sin heredero y ya ha perdido a tres alumnos por el mar. Quiere volver a batirse con una espada de verdad, pero solo bajo el mando de quien comparta un trago sincero con ella. Cuando un capitán le abre una botella de sake y no le pide nada a cambio, deja el Dojo con gusto.",
      hint: "Quiere un capitán con la experiencia de haber cruzado espadas y con un buen sake para compartir.",
      condition: { minLevel: 8, item: "sake", berries: 12_000 },
    },
  ),
  sp(
    "Restaurante Baratie", "lucan-verdier", "Lucan Verdier", "Cocinero de la Sala de los Hornos", "civilian", 7,
    "Un cocinero corpulento de manos enormes que amasa pan con la misma furia con la que otros pelean. Se le ve siempre en la Sala de los Hornos, con la camisa arremangada y la frente perlada de sudor.",
    "Orgulloso, gruñón y generoso a escondidas. Cree que nadie lucha bien con el estómago vacío.",
    "Cuchillos de cocina y sartén de hierro",
    {
      role: "Cocinero", epithet: "El del pan que levanta muertos",
      styleId: "black_leg",
      abilities: ["Patadas de cocina", "Raciones que reaniman", "Banquete de batalla", "Sartén de hierro"],
      attrs: at(24, 24, 22, 24, 16),
      lore: "Lleva años en la Sala de los Hornos del Baratie soñando con un menú que solo se pueda cocinar en el mar abierto. Se ha cansado de servir a clientes que no saben lo que comen. Solo sigue a una tripulación pirata que le demuestre, con un banquete a la altura de su mesa, que sabe apreciar la cocina de verdad.",
      hint: "Quiere ver un banquete digno de su cocina y una tripulación pirata que sepa apreciarlo.",
      condition: { minLevel: 7, factions: ["PIRATE"], item: "banquete" },
    },
  ),
  sp(
    "Isla Conomi", "nerea-salt", "Nerea Salt", "Carpintera de la Cueva del Desertor", "civilian", 5,
    "Una mujer menuda de brazos fuertes que repara botes de pesca en el Muelle de la Aldea del Atardecer. Habla con la madera como si fuera un animal herido y le pone nombre a cada tabla.",
    "Callada, cabezota y tremendamente fiel a quien le ayuda a levantar una quilla.",
    "Martillo de calafateo y hacha corta",
    {
      role: "Carpintera", epithet: "La que remienda barcos con las manos",
      abilities: ["Repara el barco", "Artilugio de emergencia", "Fortificación improvisada", "Calafateo bajo fuego"],
      attrs: at(24, 14, 26, 22, 20),
      lore: "Creció remendando botes de la Aldea del Atardecer y sabe cuánto dolió Arlong Park a los suyos. Quiere un barco de verdad y un capitán que lo cuide, pero no se une a nadie por las buenas. Cuando una tripulación le paga un precio justo por su oficio y demuestra un poco de rodaje en el mar, se sube a bordo.",
      hint: "Busca una tripulación con algo de rodaje y con dinero para pagar a una buena carpintera.",
      condition: { minLevel: 5, berries: 10_000 },
    },
  ),
  sp(
    "Loguetown", "imre-caldero", "Imre Caldero", "Suboficial retirado de la Plaza de la Ejecución", "marine", 7,
    "Un veterano de hombros anchos y barba gris que aún camina como si patrullara. Se sienta en La Última Botella a mirar la Plaza de la Ejecución sin decir palabra.",
    "Disciplinado hasta el aburrimiento, con una rabia callada contra los ascensos comprados.",
    "Sable de abordaje reglamentario",
    {
      role: "Espadachín", epithet: "El suboficial que no firmó la orden",
      styleId: "marine_fencing",
      abilities: ["Tajo directo", "Guardia cerrada", "Corte doble", "Formación de abordaje"],
      attrs: at(24, 20, 22, 28, 16),
      lore: "Sirvió a la Marina hasta que se negó a firmar una orden sobre la Plaza de la Ejecución y lo mandaron a retiro sin honores. Desde entonces bebe en La Última Botella y espera a un oficial que mande con la cabeza fría. Solo se une a alguien que vista el uniforme de la Marina y ya tenga cierta reputación.",
      hint: "Solo sirve bajo un Marine que ya se haya ganado el respeto de los suyos.",
      condition: { minLevel: 7, factions: ["MARINE"], minNotoriety: 130 },
    },
  ),
  sp(
    "Villa Syrup", "sabela-ronn", "Sabela Ronn", "Curandera de la Cabaña de la Savia", "civilian", 4,
    "Una anciana de nariz aguileña que prepara ungüentos a base de savia y corteza en la Cabaña de la Savia. Mezcla remedios sin medir, y aun así nunca se equivoca.",
    "Mordaz, bondadosa y adicta a contar historias largas que casi siempre acaban en un consejo útil.",
    "Cuchillo de herborista",
    {
      role: "Curandera", epithet: "La de la savia que cierra heridas",
      abilities: ["Primeros auxilios", "Estabiliza a un aliado", "Ungüento de savia", "Cirugía de campo"],
      attrs: at(6, 12, 12, 30, 30),
      lore: "Cura en la Cabaña de la Savia a pescadores, granjeros y hasta a quienes vienen de noche por la Plaza de las Historias. Quiere ver mundo antes de que sus huesos se lo prohíban, pero exige un capitán que le lleve un botiquín de campaña decente. Sin material no cura, y sin curar no sube a ningún barco.",
      hint: "Solo acompaña a quien lleve un buen botiquín y haya demostrado un poco de valor.",
      condition: { minLevel: 4, item: "botiquin" },
    },
  ),
  sp(
    "Tequila Wolf", "brant-korelli", "Brant Korelli", "Instructor caído de los Barracones CP", "official", 8,
    "Un hombre de mirada fría con el cuello cubierto de cicatrices, que enseña a los novatos en la Sala de Instrucción y fuera de ella no habla con nadie. Sabe demasiado de cosas que nunca debió aprender.",
    "Frío, metódico y sin humor. Su lealtad se mide en hechos, jamás en promesas.",
    "Espada de hoja corta y dagas ocultas",
    {
      role: "Espadachín", epithet: "El instructor que sabe demasiado",
      styleId: "rokushiki",
      abilities: ["Tajo directo", "Movimiento veloz", "Corte doble", "Golpe de precisión"],
      attrs: at(24, 24, 20, 28, 20),
      lore: "Enseña en la Sala de Instrucción de los Barracones CP y ha visto desaparecer a demasiados alumnos tras una orden sin firma. Está convencido de que CP-0 se corrompe desde dentro y busca a un agente con nombre propio en la organización. Solo se marcha con quien pertenezca a CP-0 y haya probado que sabe callar.",
      hint: "Solo sigue a un agente de CP-0 que ya haya probado su discreción y su nombre dentro de la organización.",
      condition: { minLevel: 8, factions: ["CP0"], minNotoriety: 140 },
    },
  ),
  sp(
    "Reverse Mountain", "ovid-tarn", "Ovid Tarn", "Piloto del Faro de la Despedida", "civilian", 6,
    "Un viejo timonel de piel curtida que enciende el Faro de la Despedida cada noche desde hace décadas. Conoce la Reverse Mountain mejor que cualquier mapa y no quiere que nadie la cruce sin respeto.",
    "Testarudo, supersticioso y muy cariñoso con los novatos que escuchan sus advertencias.",
    "Timón de hierro y cuerda de amarre",
    {
      role: "Piloto", epithet: "El que guía a los que ya no vuelven",
      abilities: ["Lee el mar y el clima", "Traza rutas seguras", "Tormenta táctica", "Cruza corrientes ascendentes"],
      attrs: at(12, 20, 16, 30, 30),
      lore: "Enciende el Faro de la Despedida desde antes de que existiera el Puesto de Observación y ha visto perderse en la Montaña a demasiados capitanes sin Log Pose. Está cansado de despedir barcos y quiere navegar uno de nuevo. Solo se marcha con un capitán que lleve un Log Pose propio, prueba de que piensa cruzar el Grand Line con respeto.",
      hint: "Solo se embarca con quien lleve encima un buen Log Pose y haya navegado ya algún tiempo.",
      condition: { minLevel: 6, item: "logpose", berries: 15_000 },
    },
  ),
  sp(
    "Whisky Peak", "corvina-lash", "Corvina Lash", "Cazadora de la Guarida del Cobro", "other", 11,
    "Una mujer de sonrisa fina que se sienta al fondo del Salón de la Risa Eterna con una jarra sin tocar. Nadie recuerda haberla visto beber, pero todos saben cuándo mira.",
    "Sarcástica, calculadora y demasiado observadora. Se ríe solo cuando el chiste lo hace otro.",
    "Ballesta corta y cuchillos de lanzamiento",
    {
      role: "Francotiradora", epithet: "La sonrisa que cobra",
      abilities: ["Tiro certero", "Disparo de cobertura", "Cuchillos de lanzamiento", "Rastreo de fugitivos"],
      attrs: at(16, 30, 16, 30, 24),
      lore: "Cobró recompensas en la Guarida del Cobro hasta que se cansó de que el Salón de la Risa Eterna fingiera hospitalidad con los mismos a los que luego se les ponía precio. Quiere volver al mar con alguien que juegue limpio, y solo confía en cazadores de recompensas que ya tengan una fama a la altura de la suya.",
      hint: "Solo se une a un cazador con fama ganada y con nivel suficiente para acompañarla.",
      condition: { minLevel: 11, factions: ["BOUNTY_HUNTER"], minNotoriety: 200 },
    },
  ),
  sp(
    "Little Garden", "gorm-tallat", "Gorm Tallat", "Guerrero de la Arena de los Cien Años", "pirate", 12,
    "Un hombre enorme de espalda curtida por el sol que entrena solo en la Arena de los Cien Años, cargando troncos como si fueran leña. Su silencio pesa más que sus puños.",
    "Reservado, honorable y terriblemente paciente. Solo se enfada cuando alguien desprecia a los débiles.",
    "Maza de raíz de árbol",
    {
      role: "Guardaespaldas", epithet: "El muro de la Arena",
      abilities: ["Muro humano", "Placaje", "Aguante inquebrantable", "Maza de raíz"],
      attrs: at(38, 14, 36, 30, 12),
      lore: "Entrena a solas en la Arena de los Cien Años desde que dejó atrás su tripulación, y la selva de helechos gigantes le enseñó a esperar. Quiere volver a ser escudo de alguien, pero solo de quien tenga ya un cartel en los tablones. Un pirata sin cartel para él no es más que un chico jugando a serlo.",
      hint: "Solo sigue a un pirata cuyo cartel ya pese en los tablones de recompensas.",
      condition: { minLevel: 12, factions: ["PIRATE"], minBounty: 8_000_000, berries: 30_000 },
    },
  ),
  sp(
    "Alabasta", "yazan-kefeya", "Yazan Kefeya", "Espadachín de las Dunas Prohibidas", "other", 15,
    "Un rebelde de rostro tapado por un turbante polvoriento, con una cimitarra que nunca se aleja de su mano. Cruza las Dunas Prohibidas al amanecer para no ser visto.",
    "Fiero, honorable y desconfiado con los forasteros. Prefiere el silencio al sermón.",
    "Cimitarra curva",
    {
      role: "Espadachín", epithet: "El rebelde de las dunas",
      abilities: ["Tajo directo", "Guardia cerrada", "Corte doble", "Danza de arena"],
      attrs: at(30, 26, 20, 32, 16),
      lore: "Combatió por la causa en las Dunas Prohibidas y vio a los suyos caer en el Oasis del Viento Seco por una traición del Gobierno Mundial. Ya no cree en reyes, solo en el Ejército Revolucionario. Aceptará a quien comparta su agua del desierto, símbolo de que no bebe a costa de los demás.",
      hint: "Solo se une a un revolucionario dispuesto a compartir agua con él y con renombre en la causa.",
      condition: { minLevel: 15, factions: ["REVOLUTIONARY"], minNotoriety: 220, item: "oasis" },
    },
  ),
  sp(
    "Isla Drum", "ylvie-hoar", "Ylvie Hoar", "Médica del Refugio de los Olvidados", "civilian", 13,
    "Una doctora de dedos entumecidos por el frío que atiende a los exiliados en el Refugio de los Olvidados. Habla poco y rara vez sonríe, pero nadie muere bajo su techo.",
    "Estricta, desconfiada y con una ternura que se disfraza de reproches.",
    "Instrumental de cirugía y bisturí de hielo",
    {
      role: "Médica", epithet: "La del refugio bajo la nieve",
      abilities: ["Primeros auxilios", "Estabiliza a un aliado", "Cirugía de campo", "Tratamiento contra el frío"],
      attrs: at(10, 14, 20, 34, 36),
      lore: "Atiende a los exiliados en el Refugio de los Olvidados desde que el Castillo Real cayó en desgracia, y ya no quedan medicinas ni gente que las traiga. Sueña con una botica que no dependa de la nieve, pero no se va con cualquiera. Quiere ver el Elixir de la doctora en la mano del capitán, señal de que sabe cuánto cuesta curar.",
      hint: "Solo se une a quien traiga un elixir de calidad y ya haya visto peligro de verdad.",
      condition: { minLevel: 13, item: "elixir", berries: 40_000 },
    },
  ),
  sp(
    "Skypiea", "nubel-arcoy", "Nubel Arcoy", "Navegante del Mirador del Velo", "civilian", 17,
    "Un joven de andar ligero y ojos siempre en el cielo que ajusta conchas de aire en los miradores. Presume de leer las nubes mejor que nadie, y tiene razón.",
    "Bromista, valiente y adicto a las alturas. Se aburre de cualquier lugar con techo.",
    "Guantes con dial de impacto",
    {
      role: "Navegante", epithet: "El que lee las nubes",
      styleId: "dial_combat",
      abilities: ["Lee el mar y el clima", "Traza rutas de nube", "Impact Dial", "Tormenta táctica"],
      attrs: at(14, 34, 14, 26, 30),
      lore: "Cuida las conchas del Mirador del Velo y sueña con ver el mar azul que tantos visitantes le describen en el Mercado de la Bruma. No quiere cualquier tripulación, solo una que le pague bien por sus rutas y demuestre tener experiencia de mar. El Barrio del Alba le da la despedida con cariño cuando alguien es digno.",
      hint: "Solo se va con una tripulación con experiencia de mar y con dinero para pagar sus servicios.",
      condition: { minLevel: 17, berries: 60_000 },
    },
  ),
  sp(
    "Water 7", "petra-lovac", "Petra Lovac", "Ex-ingeniera del Astillero Secreto", "official", 16,
    "Una mujer de hombros anchos con un lápiz de carpintero siempre tras la oreja. Se le nota una mano que sabe de secretos de Estado, pese a lo mucho que se esfuerza en disimularlo.",
    "Seria, reservada y meticulosa. Cada tornillo tiene su razón de ser.",
    "Llave inglesa de hierro y pistola de servicio",
    {
      role: "Carpintera", epithet: "La del plano que no se archiva",
      abilities: ["Repara el barco", "Artilugio de emergencia", "Fortificación improvisada", "Planos secretos"],
      attrs: at(22, 20, 24, 28, 34),
      lore: "Trabajó en el Astillero Secreto de Water 7 para CP-0 hasta ver que sus planos se usaban para cosas que jamás aprobaría. Se escondió entre los Astilleros Galley-La y aún desconfía de todo el mundo. Solo se marchará con un agente de CP-0 que haya demostrado su prudencia y mande con cabeza fría.",
      hint: "Solo sigue a un agente de CP-0 con prudencia probada y con algo de experiencia.",
      condition: { minLevel: 16, factions: ["CP0"], minNotoriety: 200 },
    },
  ),
  sp(
    "Archipiélago Sabaody", "marek-dolsen", "Marek Dolsen", "Carpintero del Puerto del Manglar 44", "civilian", 19,
    "Un hombre de cuello grueso que forra barcos con resina en el Puerto del Manglar 44. Trabaja con una calma que contrasta con el ruido de las Pompas.",
    "Callado, exacto y feliz solo cuando su trabajo queda a salvo del agua.",
    "Cincel de calafateo y martillo pesado",
    {
      role: "Carpintero", epithet: "El que forra barcos con resina",
      abilities: ["Repara el barco", "Forrado de resina", "Fortificación improvisada", "Artilugio de emergencia"],
      attrs: at(28, 16, 30, 28, 24),
      lore: "Forra barcos con resina en el Puerto del Manglar 44 para capitanes que después no vuelven a dejarse ver. Está harto de mirar zarpar a los demás desde el muelle y quiere viajar con uno de esos barcos. Solo sirve a un pirata con cartel propio, capaz de comprar los materiales y de llevar la bandera con orgullo.",
      hint: "Solo se une a un pirata cuyo cartel ya sea conocido y capaz de comprar madera de calidad.",
      condition: { minLevel: 19, factions: ["PIRATE"], minBounty: 20_000_000, berries: 80_000 },
    },
  ),
  sp(
    "Jaya", "isolde-varga", "Isolde Varga", "Buscadora del Campamento del Buscador", "other", 11,
    "Una arqueóloga aficionada de pelo revuelto que rastrea pistas en el Bosque de los Suspiros con una libreta cubierta de barro. Nunca ha encontrado nada y jamás ha dejado de buscar.",
    "Curiosa, testaruda e incapaz de perder el hilo de una teoría. Se emociona con cada hallazgo.",
    "Pico de excavación y cuerda de escalada",
    {
      role: "Arqueóloga", epithet: "La que siempre está a un palmo del hallazgo",
      abilities: ["Descifra escrituras", "Conoce el mundo", "Punto débil del enemigo", "Excavación rápida"],
      attrs: at(12, 16, 14, 30, 34),
      lore: "Lleva años en el Campamento del Buscador reuniendo pistas que nadie más se molesta en leer. Está segura de que un mapa del tesoro bien interpretado la llevará donde los cuentos de Jaya prometen. Como sobrevive cobrando pequeñas recompensas del gremio, solo sigue a un cazador de recompensas que lleve un mapa del tesoro auténtico en el bolsillo.",
      hint: "Solo acompaña a un cazador de recompensas que lleve un mapa de tesoro auténtico.",
      condition: { minLevel: 11, factions: ["BOUNTY_HUNTER"], item: "mapa", berries: 30_000 },
    },
  ),
  sp(
    "Thriller Bark", "elric-moth", "Elric Moth", "Músico del Aviario de Mal Agüero", "civilian", 18,
    "Un hombre delgado y pálido de sombrero raído que toca el violín en el Aviario de Mal Agüero hasta que las aves callan. Nadie recuerda cómo llegó a la isla.",
    "Melancólico, ingenioso y risueño con un toque macabro. Le gusta que sus notas asusten un poco.",
    "Violín de madera negra con arco de acero",
    {
      role: "Músico", epithet: "El violín que hace callar a los cuervos",
      abilities: ["Canción que anima", "Nota discordante", "Himno de la tripulación", "Melodía de espanto"],
      attrs: at(10, 24, 14, 34, 28),
      lore: "Toca en el Aviario de Mal Agüero desde que perdió su primer barco y la Torre del Reloj se convirtió en su único calendario. Su música apenas anima a los vivos, y quiere volver a tocar para quien celebre en cubierta con un trago de sake. Solo sigue a un pirata con cartel que le ofrezca la mesa de una tripulación de verdad.",
      hint: "Solo toca para un pirata con cartel propio que sepa celebrar en cubierta.",
      condition: { minLevel: 18, factions: ["PIRATE"], minBounty: 15_000_000, item: "sake" },
    },
  ),
  sp(
    "Ohara", "wystan-crale", "Wystan Crale", "Guardián de las Ruinas de la Gran Biblioteca", "other", 15,
    "Un hombre de hombros caídos y ojos tristes que limpia con un trapo las piedras de las Ruinas de la Gran Biblioteca. Dice que aún se oyen las páginas al viento.",
    "Melancólico, afable y de una rabia contenida que solo sale cuando le hablan del Gobierno.",
    "Bastón de puño de piedra",
    {
      role: "Erudito", epithet: "El que aún oye las páginas",
      abilities: ["Descifra escrituras", "Conoce el mundo", "Punto débil del enemigo", "Memoria de archivo"],
      attrs: at(10, 12, 14, 36, 40),
      lore: "Vive entre las Ruinas de la Gran Biblioteca, bajo el Árbol Carbonizado, y protege lo que el Gobierno Mundial quiso borrar. Sospecha de casi todos los visitantes, excepto de quienes traigan una reliquia antigua y lleven la bandera de la Revolución. Con ellos comparte sus notas y viaja sin dudar.",
      hint: "Solo confía en un revolucionario que le traiga una reliquia de verdad y demuestre respeto por lo perdido.",
      condition: { minLevel: 15, factions: ["REVOLUTIONARY"], item: "reliquia", minNotoriety: 180 },
    },
  ),
  sp(
    "G-8 Navarone", "sigrun-halle", "Sigrun Halle", "Artillera de las Baterías del Acantilado Norte", "marine", 14,
    "Una cabo de ojos afilados y guantes de cuero gastado que vigila el horizonte desde las Baterías del Acantilado Norte. Sus compañeros la llaman la de los tiros imposibles.",
    "Concentrada, orgullosa y de pocas palabras. Solo se ríe cuando acierta a mil pasos.",
    "Fusil de largo alcance",
    {
      role: "Francotiradora", epithet: "La que acierta a mil pasos",
      abilities: ["Tiro certero", "Disparo de cobertura", "Bala de precisión", "Cálculo de trayectoria"],
      attrs: at(16, 28, 16, 30, 28),
      lore: "Sirve en las Baterías del Acantilado Norte de G-8 Navarone y ha hundido más barcos piratas de los que cuenta. Le pesa que sus tiros se atribuyan siempre a su jefe. Solo sirve como francotiradora a un Marine con renombre propio, que reparta el mérito con quienes lo ganan.",
      hint: "Solo se une a un Marine con nombre propio que reparta el mérito entre su gente.",
      condition: { minLevel: 14, factions: ["MARINE"], minNotoriety: 180 },
    },
  ),
  sp(
    "Reino Kamabakka", "nadir-quill", "Nadir Quill", "Coctelero del Coctelero Revolucionario", "other", 15,
    "Un hombre de sonrisa amplia y delantal impecable que sirve tragos con nombres de campaña en El Coctelero Revolucionario. Tras la barra cuelga siempre un mapa de rutas de escape.",
    "Extravagante, generoso y sorprendentemente feroz cuando alguien insulta su barra.",
    "Cuchillos de cocina y una botella de licor fuerte",
    {
      role: "Cocinero", epithet: "El coctelero de la Revolución",
      styleId: "newkama_kenpo",
      abilities: ["Patadas de cocina", "Raciones que reaniman", "Banquete de batalla", "Trago de aguante"],
      attrs: at(22, 28, 20, 30, 22),
      lore: "Sirve tragos en El Coctelero Revolucionario a los agentes que pasan por el Reino Kamabakka de camino a misiones que jamás cuentan. Quiere cocinar también en el frente y no pide más que un banquete bien hecho y una causa digna. Solo se une a un revolucionario con nombre en el Ejército, que sepa cuidar de su mesa.",
      hint: "Solo cocina para un revolucionario con nombre en el Ejército y una mesa que merezca su trabajo.",
      condition: { minLevel: 15, factions: ["REVOLUTIONARY"], minNotoriety: 200, berries: 50_000 },
    },
  ),
  sp(
    "Punk Hazard", "tobiah-frest", "Tobiah Frest", "Médico de la Cueva de los Cazadores", "civilian", 27,
    "Un doctor de piel marcada por el frío y las llamas que atiende a los pocos supervivientes de la Cueva de los Cazadores. Habla con calma incluso cuando la Fría vuelve a cortar el camino.",
    "Sereno, compasivo y un poco fatalista. No se rinde con ningún paciente.",
    "Instrumental de cirugía y guantes térmicos",
    {
      role: "Médico", epithet: "El que cose entre hielo y fuego",
      abilities: ["Primeros auxilios", "Estabiliza a un aliado", "Cirugía de campo", "Tratamiento contra quemaduras"],
      attrs: at(14, 18, 26, 42, 46),
      lore: "Trabaja en la Cueva de los Cazadores desde antes de que el Laboratorio Sellado se cerrara y jura no volver a dejar sin cura a nadie del Páramo de los Lamentos. Está agotado de la isla y solo se va con un capitán que ya haya enfrentado peligros reales y que le ofrezca un elixir para sus pacientes.",
      hint: "Solo se une a quien ya haya sobrevivido a peligros reales y lleve algo con qué curar.",
      condition: { minLevel: 27, item: "elixir", berries: 150_000 },
    },
  ),
  sp(
    "Whole Cake Island", "marzia-confit", "Marzia Confit", "Cocinera de la Taberna del Jarabe Ahumado", "civilian", 30,
    "Una cocinera de hombros anchos y cuchara de madera siempre en mano, con las cejas chamuscadas de tanto azúcar caramelizado. Fuera de la Taberna del Jarabe Ahumado se la ve poco, pero su fama llega a los muelles.",
    "Bulliciosa, sensible y feroz cuando alguien desprecia un plato. Cocina como quien enciende un incendio.",
    "Cuchillos de repostería y sartén de hierro",
    {
      role: "Cocinera", epithet: "La del azúcar que quema",
      abilities: ["Patadas de cocina", "Raciones que reaniman", "Banquete de batalla", "Caramelo ardiente"],
      attrs: at(28, 26, 30, 34, 26),
      lore: "Cocina en la Taberna del Jarabe Ahumado bajo la sombra de la Torre de Caramelo Hirviente, y guarda recetas que jamás le dejaron firmar. Sueña con un barco donde el fuego no dependa de los caprichos de nadie. Solo sigue a un pirata con un cartel que ya se pronuncie en voz alta, que le enseñe un banquete verdadero.",
      hint: "Solo cocina para un pirata de cartel notable que le demuestre respeto con un banquete de verdad.",
      condition: { minLevel: 30, factions: ["PIRATE"], minBounty: 60_000_000, item: "banquete" },
    },
  ),
  sp(
    "País de Wano", "sozan-mihara", "Sozan Mihara", "Ronin de la Aldea del Susurro", "other", 32,
    "Un samurái sin señor de mirada cansada que afila su hoja junto al Puente Roto. Nunca cuenta de dónde viene, pero sus pasos son los de quien ha cruzado mucho.",
    "Digno, sobrio y con una tristeza que solo se disipa con sake compartido.",
    "Katana larga de doble filo",
    {
      role: "Espadachín", epithet: "El ronin del puente roto",
      styleId: "ittoryu",
      abilities: ["Iai Giri", "Onda cortante", "Guardia cerrada", "Contragolpe sereno"],
      attrs: at(42, 34, 28, 40, 22),
      lore: "Fue samurái en un clan de Wano que ya no existe y ahora vaga entre la Aldea del Susurro y el Puente Roto sin señor. Ya no cree en juramentos, solo en un buen trago de sake de Wano compartido con un capitán que sepa perder. Si le ve la calidad, cruza el mar con él.",
      hint: "Solo sigue a un capitán con experiencia que comparta con él un sake de su tierra.",
      condition: { minLevel: 32, item: "sakewano", berries: 200_000 },
    },
  ),
  sp(
    "Dressrosa", "valeria-dorn", "Valeria Dorn", "Duelista de las Gradas Altas del Coliseo", "other", 29,
    "Una mujer de movimientos ágiles que practica estocadas contra un poste en las Gradas Altas del Coliseo. Sus admiradores son muchos y sus deudas, más.",
    "Vanidosa, ágil y con un corazón noble al que le cuesta admitir lo que siente.",
    "Florete de guarnición fina",
    {
      role: "Espadachina", epithet: "La duelista de la tribuna",
      styleId: "rapier",
      abilities: ["Kenbishi", "Estocada en cadena", "Danza de la espada", "Salto de altura"],
      attrs: at(28, 46, 22, 36, 26),
      lore: "Peleó durante años en el Coliseo Corrida y ha visto cómo la Plaza de los Suspiros se vuelve mercado de apuestas y traiciones. Ya no quiere ganar para otros, solo por su propia bandera. Se une a quien cubra su deuda con una suma decente y demuestre que sabe pelear sin humillar al rival.",
      hint: "Solo se une a quien pueda pagar sus deudas y haya demostrado que respeta a los rivales.",
      condition: { minLevel: 29, berries: 180_000 },
    },
  ),
  sp(
    "Zou", "koru-tannen", "Koru Tannen", "Sanador de El Jardín de los Humores", "civilian", 31,
    "Un sanador alto y de andar silencioso que cuida las hierbas de El Jardín de los Humores. Dice que cada planta recuerda el dolor de quien la usó antes.",
    "Sereno, amable y con un humor extraño. Habla poco, pero cada frase suena a sentencia.",
    "Bastón de bambú y morteros de madera",
    {
      role: "Sanador", epithet: "El que oye el dolor de las hierbas",
      abilities: ["Primeros auxilios", "Estabiliza a un aliado", "Cirugía de campo", "Infusión curativa"],
      attrs: at(18, 24, 24, 44, 44),
      lore: "Cuida El Jardín de los Humores y prepara infusiones para cada herido que llega a la Aldea de los Minks. Ha visto demasiados barcos zarpar con heridos que nunca regresan y ahora quiere ver mundo, pero solo con quien acepte llevar una infusión mink en su equipaje, símbolo de que respeta el oficio.",
      hint: "Solo se une a quien lleve una infusión de su tierra y demuestre respeto por el oficio de sanar.",
      condition: { minLevel: 31, item: "infusion", berries: 220_000 },
    },
  ),
  sp(
    "Elbaf", "hrafna-stenn", "Hrafna Stenn", "Escolta de las Piedras del Juramento", "civilian", 35,
    "Una guerrera de hombros como muros y trenzas grises que vigila las Piedras del Juramento con un hacha al hombro. Sus silencios son largos y sus abrazos, quebrantahuesos.",
    "Firme, leal y solemne. Cada promesa que hace es de piedra.",
    "Hacha de guerra de doble filo",
    {
      role: "Guardaespaldas", epithet: "La que jura sobre piedra",
      abilities: ["Muro humano", "Placaje", "Aguante inquebrantable", "Hachazo de juramento"],
      attrs: at(56, 22, 52, 44, 26),
      lore: "Vigila las Piedras del Juramento de Elbaf desde que se quedó sin compañeros de guerra y aún guarda silencio sobre cómo. Solo jurará lealtad a un pirata de cartel temible, capaz de mirar a los ojos a los suyos y reconocer que la fuerza sin honor no vale nada.",
      hint: "Solo jura lealtad a un pirata de cartel temible que mire de frente y cuide a los suyos.",
      condition: { minLevel: 35, factions: ["PIRATE"], minBounty: 90_000_000, berries: 300_000 },
    },
  ),
  sp(
    "Isla Egghead", "ansel-ferro", "Ansel Ferro", "Técnico del Centro de Comando Bóveda", "other", 36,
    "Un ingeniero de dedos ágiles y gafas empañadas que trabaja de noche en el Centro de Comando Bóveda con una pila de cables al hombro. Nunca deja de hablar solo.",
    "Nervioso, genial y con un sentido del humor negro. Odia que se toque un cable sin avisarle.",
    "Llave de precisión y pistola de descargas",
    {
      role: "Ingeniero", epithet: "El que oye latir las máquinas",
      abilities: ["Repara el barco", "Artilugio de emergencia", "Fortificación improvisada", "Cableado sabotaje"],
      attrs: at(18, 26, 20, 40, 50),
      lore: "Trabaja en el Centro de Comando Bóveda de Isla Egghead y descubrió, entre los Archivos del Legado, que muchos inventos se usan como armas contra pueblos enteros. No confía en el Gobierno Mundial ni en los piratas que solo saquean, y solo se marcha con un revolucionario que ya haya probado su causa con hechos.",
      hint: "Solo se une a un revolucionario de nombre reconocido que ya haya probado su causa con hechos.",
      condition: { minLevel: 36, factions: ["REVOLUTIONARY"], minNotoriety: 400, berries: 250_000 },
    },
  ),
  sp(
    "Enies Lobby", "castor-vale", "Castor Vale", "Agente arrepentido de las Torres del Juicio", "official", 37,
    "Un hombre de mirada fija y traje impecable que se pasea por las Torres del Juicio con la espalda muy recta. Detrás de la calma esconde a alguien que ya no cree en lo que sirve.",
    "Frío, cortés y de humor tan seco que casi nunca se nota. Sabe cuándo callar y cuándo no.",
    "Espada de hoja fina y guantes reforzados",
    {
      role: "Espadachín", epithet: "El del veredicto que ya no firma",
      styleId: "rokushiki",
      abilities: ["Tajo directo", "Movimiento veloz", "Corte doble", "Golpe de precisión"],
      attrs: at(44, 44, 32, 44, 32),
      lore: "Sirvió en CP-0 desde las Torres del Juicio, pero no ha vuelto a dormir tranquilo tras ver el Nicho del Verdicto Final. Sabe que si abandona el puesto lo darán por muerto, así que solo se va con otro agente de CP-0 con una reputación limpia dentro de la organización, capaz de sostener su silencio.",
      hint: "Solo sigue a un agente de CP-0 con reputación firme dentro de la organización y experiencia real.",
      condition: { minLevel: 37, factions: ["CP0"], minNotoriety: 450 },
    },
  ),
  sp(
    "Marineford", "ilse-marchant", "Ilse Marchant", "Escolta del Muelle de la Justicia", "marine", 27,
    "Una capitana de hombros anchos y gesto grave que vigila el Muelle de la Justicia como si cada barco fuera suyo. Los novatos la respetan; los veteranos, más aún.",
    "Recta, leal y con una tozudez casi comedida. Detesta la crueldad innecesaria.",
    "Mazo de acero reglamentario",
    {
      role: "Escolta", epithet: "La muralla del Muelle de la Justicia",
      styleId: "marine_fencing",
      abilities: ["Muro humano", "Placaje", "Aguante inquebrantable", "Formación de defensa"],
      attrs: at(42, 24, 44, 40, 26),
      lore: "Vigila el Muelle de la Justicia y ha visto pasar por Marineford a los mejores y a los peores de la Marina. Está harta de ver a sus mandos ceder ante los privilegios. Solo se marcha con un Marine de reputación limpia que lidere con la cabeza fría y proteja a los suyos ante cualquier orden.",
      hint: "Solo sirve bajo un Marine de reputación limpia que proteja a su gente aunque sea difícil.",
      condition: { minLevel: 27, factions: ["MARINE"], minNotoriety: 350 },
    },
  ),
];
