/**
 * The rest of the canon cast (2026-09-24): every notable character that was still missing, with
 * bounty, weapon, fruit, personality, combat stats, Haki and signature abilities. `status` marks the
 * ones whose story already ended (deceased / defeated / retired): they stay in the codex and the lore,
 * but never act in the world tick. Bounties are the canon figures (null = none known).
 */
import { ActorRole, FactionType } from "@prisma/client";
import type { ActorProfile } from "./world-actor-profiles";

export interface ExtraActor {
  name: string;
  role: ActorRole;
  powerLevel: number;
  description: string;
  personality: string;
  factionType: FactionType;
  factionName: string;
  rankLabel?: string;
  canonBounty?: bigint;
  canonWeapon?: string;
  devilFruitName?: string;
  status?: "ACTIVE" | "RETIRED" | "DEFEATED" | "DECEASED";
  profile: ActorProfile;
}

const B = (n: number) => BigInt(n);
const P = FactionType.PIRATE;
const M = FactionType.MARINE;
const R = FactionType.REVOLUTIONARY;
const C = FactionType.CIPHER_POL;
const BH = FactionType.BOUNTY_HUNTER;
const CIV = FactionType.CIVILIAN;
const U = FactionType.UNAFFILIATED;
const NP = ActorRole.NOTABLE_PIRATE;

export const EXTRA_ACTORS: ExtraActor[] = [
  // ---------- La era pasada (lore, ya no actúan) ----------
  { name: "Gol D. Roger", role: NP, powerLevel: 100, status: "DECEASED", factionType: P, factionName: "Piratas de Roger", rankLabel: "Rey de los Piratas", canonBounty: B(5_564_800_000), canonWeapon: "Ace (espada)", description: "El Rey de los Piratas: llegó a Laugh Tale, se rió y cambió el mundo. Su ejecución en Loguetown abrió la Gran Era Pirata.", personality: "Risueño hasta el final, desafió al mundo entero con una sonrisa.", profile: { s: [99, 94, 98, 99, 96], h: [99, 99, true], ab: ["Haoshoku de Rey", "Voz de todas las cosas", "Esgrima legendaria"], home: "laughTale" } },
  { name: "Edward Newgate (Barbablanca)", role: ActorRole.YONKO, powerLevel: 99, status: "DECEASED", factionType: P, factionName: "Piratas de Barbablanca", rankLabel: "El hombre más fuerte del mundo", canonBounty: B(5_046_000_000), canonWeapon: "Murakumogiri", devilFruitName: "Gura Gura no Mi", description: "Cayó en Marineford dejando un mundo en llamas. Su fruta, el Gura Gura, cambió de manos.", personality: "Un padre para todos sus hijos: firme, generoso y sin miedo a morir de pie.", profile: { s: [99, 82, 99, 99, 90], h: [98, 92, true], phase: "awakened", ab: ["Terremotos que parten el aire", "Quiebra del mundo", "Haoshoku de Emperador"], home: "sabaody" } },
  { name: "Portgas D. Ace", role: NP, powerLevel: 88, status: "DECEASED", factionType: P, factionName: "Piratas de Barbablanca", rankLabel: "Comandante de la 2ª flota", canonBounty: B(550_000_000), description: "Puño de Fuego, hermano de Luffy y Sabo. Su muerte en Marineford marcó una generación.", personality: "Ardiente y orgulloso; muere por proteger a quienes ama.", profile: { s: [90, 92, 84, 92, 80], h: [86, 84, false], ab: ["Puño de Fuego", "Hiken", "Hakis de armadura ardiente"], home: "sabaody" } },
  { name: "Rocks D. Xebec", role: NP, powerLevel: 98, status: "DECEASED", factionType: P, factionName: "Piratas de Rocks", description: "El capitán de los Piratas de Rocks, la tripulación más temida de la historia; su caída en God Valley quedó borrada de los libros.", personality: "Ambición sin freno: quería todo el mundo y lo quería ya.", profile: { s: [98, 84, 98, 99, 90], h: [98, 92, true], ab: ["Tripulación de monstruos", "Ambición de dominar el mar"], home: "graveyardIsland", hidden: true } },
  { name: "Kaido", role: ActorRole.YONKO, powerLevel: 99, status: "ACTIVE", factionType: P, factionName: "Piratas de las Bestias", rankLabel: "Rey de las Bestias", canonBounty: B(4_611_100_000), canonWeapon: "Hasu (maza)", devilFruitName: "Uo Uo no Mi: Modelo Seiryu", description: "La criatura más fuerte del mundo: Emperador de las Bestias, con Onigashima como fortaleza. La guerra de Wano sigue sin resolverse y su sombra pesa sobre todo el país.", personality: "Busca una muerte gloriosa; ríe borracho y lo destroza todo con la misma calma.", profile: { s: [99, 80, 99, 99, 76], h: [98, 88, true], phase: "awakened", ab: ["Dragón Azur", "Hakai: Thunder Bagua", "Clouds Bagua", "Haoshoku de Emperador"], home: "wano" } },
  { name: "Charlotte Linlin (Big Mom)", role: ActorRole.YONKO, powerLevel: 99, status: "ACTIVE", factionType: P, factionName: "Piratas de Big Mom", rankLabel: "Emperatriz del Dulce", canonBounty: B(4_388_000_000), canonWeapon: "Napoleón", devilFruitName: "Soru Soru no Mi", description: "Reina de Totto Land: arranca almas y sostiene un imperio de dulces desde Whole Cake Island, siempre a un antojo de la catástrofe.", personality: "Gloton y caprichosa; se vuelve imparable cuando tiene hambre.", profile: { s: [99, 76, 98, 96, 70], h: [96, 88, true], phase: "awakened", ab: ["Homies de Zeus, Prometeo y Napoleón", "Hell Hoy Tigers", "Almas por tiempo de vida"], home: "wholeCake" } },
  { name: "Kozuki Oden", role: NP, powerLevel: 90, status: "DECEASED", factionType: P, factionName: "Piratas de Barbablanca", rankLabel: "Daimyo de Kuri", canonWeapon: "Ame no Habakiri y Enma", description: "El samurái que quiso abrir el país de Wano al mundo: hervido vivo, pero sin bajar la sonrisa.", personality: "Ruidoso, alegre y con una honradez que asusta a los que no la tienen.", profile: { s: [92, 84, 92, 98, 80], h: [92, 86, false], ab: ["Corte doble Hyo", "Enma: Haki de Armadura extremo", "El Daimyo hervido"], home: "wano" } },
  { name: "Donquixote Rosinante (Corazón)", role: NP, powerLevel: 72, status: "DECEASED", factionType: M, factionName: "Marina", rankLabel: "Comandante infiltrado", devilFruitName: "Nagi Nagi no Mi", description: "Un marine infiltrado que dio la vida por salvar a un niño.", personality: "Torpe por fuera, valiente por dentro.", profile: { s: [70, 84, 68, 94, 78], h: [40, 60, false], phase: "initial", ab: ["Silencio absoluto", "Espionaje", "Sacrificio"], home: "loguetown" } },
  { name: "Vergo", role: NP, powerLevel: 84, status: "DECEASED", factionType: M, factionName: "Marina", rankLabel: "Vicealmirante de doble bandera", description: "El corazón traicionero de la Marina, espía de Doflamingo.", personality: "Frío y calculador, jamás pierde la compostura.", profile: { s: [86, 76, 88, 84, 84], h: [92, 82, false], ab: ["Bambú: cuerpo endurecido con Armadura", "Doble espionaje"], home: "marineG5" } },
  { name: "Orochi", role: NP, powerLevel: 60, status: "DECEASED", factionType: P, factionName: "Shogunato de Wano", rankLabel: "Shogun", description: "El shogun caprichoso que hundió Wano bajo las órdenes de Kaido.", personality: "Vanidoso y cruel.", profile: { s: [60, 58, 70, 60, 66], h: [40, 30, false], phase: "initial", ab: ["Hidra de ocho cabezas", "Cocodrilos de humo"], home: "wano" } },

  // ---------- Marina ----------
  { name: "Aokiji (Kuzan)", role: ActorRole.ADMIRAL, powerLevel: 96, factionType: P, factionName: "Piratas de Barbanegra (ex-Marina)", rankLabel: "Ex-Almirante", devilFruitName: "Hie Hie no Mi", description: "Ex-Almirante de la Marina; hoy abandonó la justicia absoluta por una propia, vagando entre bandos.", personality: "Perezoso, filósofo y letal; frío en todo sentido.", profile: { s: [90, 88, 90, 90, 88], h: [90, 92, false], phase: "awakened", ab: ["Ice Time: congelar el mar", "Ice Age", "Ice Block Pheasant Beak", "Lanza de hielo"], home: "graveyardIsland" } },
  { name: "Tsuru", role: ActorRole.MARINE_GENERAL, powerLevel: 82, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante", devilFruitName: "Woshu Woshu no Mi", description: "La Gran Estratega de la Marina: lava y estrangula sin manchar el uniforme.", personality: "Seca, mordaz y de una lealtad inquebrantable.", profile: { s: [70, 70, 74, 92, 96], h: [64, 80, false], phase: "advanced", ab: ["Lavado de cerebro", "Secado del cuerpo", "Estrategia de flota"], home: "marineG5" } },
  { name: "Coby", role: ActorRole.MARINE_OFFICER, powerLevel: 74, factionType: M, factionName: "Marina", rankLabel: "Capitán (Héroe de la Marina)", description: "El chico que soñaba con ser marine y terminó siendo héroe: su Haki de Observación es de nivel superior.", personality: "Amable, tenaz y sin miedo a dar la cara por los débiles.", profile: { s: [66, 72, 66, 96, 88], h: [60, 92, false], ab: ["Observación extrema", "Puños de hierro", "Liderazgo por ejemplo"], home: "marineG5" } },
  { name: "Helmeppo", role: ActorRole.MARINE_OFFICER, powerLevel: 60, factionType: M, factionName: "Marina", rankLabel: "Teniente", description: "De niño mimado a oficial disciplinado, lucha al lado de Coby.", personality: "Sarcástico y leal, aprende rápido.", profile: { s: [58, 62, 56, 80, 60], h: [30, 20, false], ab: ["Esgrima básica", "Tácticas de pelotón"], home: "marineG5" } },
  { name: "Tashigi", role: ActorRole.MARINE_OFFICER, powerLevel: 66, factionType: M, factionName: "Marina", rankLabel: "Capitana", canonWeapon: "Shigure", description: "Espadachina obsesionada con las grandes espadas; incorruptible.", personality: "Torpe con las gafas, implacable con el deber.", profile: { s: [68, 74, 62, 86, 70], h: [40, 40, false], ab: ["Iaido", "Ojo clínico de espadas"], home: "loguetown" } },
  { name: "Hina", role: ActorRole.MARINE_OFFICER, powerLevel: 72, factionType: M, factionName: "Marina", rankLabel: "Contralmirante (Jaula Negra)", devilFruitName: "Ori Ori no Mi", description: "Encierra a los criminales entre barrotes y no da explicaciones.", personality: "Elegante, fría y de pocas palabras.", profile: { s: [68, 78, 70, 82, 74], h: [50, 58, false], phase: "advanced", ab: ["Jaula Negra", "Cadenas de hierro", "Presa inmovilizada"], home: "marineG5" } },
  { name: "Momonga", role: ActorRole.MARINE_OFFICER, powerLevel: 74, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante", description: "Veterano de mil batallas, de trato austero y mano firme.", personality: "Sereno, formal y honrado.", profile: { s: [76, 72, 76, 84, 78], h: [70, 60, false], ab: ["Sable pesado", "Disciplina de flota"], home: "marineG5" } },
  { name: "Sentomaru", role: ActorRole.MARINE_OFFICER, powerLevel: 76, factionType: M, factionName: "Marina", rankLabel: "Jefe de guardia de Vegapunk", canonWeapon: "Hacha de guerra", description: "Guardaespaldas de Vegapunk: imponente y muy fuerte.", personality: "Leal, directo y algo torpe con las sutilezas.", profile: { s: [84, 66, 88, 82, 62], h: [60, 40, false], ab: ["Hachazos que parten muros", "Guardia impenetrable"], home: "eniesLobby" } },
  { name: "Strawberry", role: ActorRole.MARINE_OFFICER, powerLevel: 66, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante", description: "Un vicealmirante que confía en su intuición.", personality: "Excéntrico pero afilado.", profile: { s: [70, 72, 66, 78, 68], h: [50, 50, false], ab: ["Espada corta", "Corazonadas"], home: "marineG5" } },
  { name: "Doberman", role: ActorRole.MARINE_OFFICER, powerLevel: 70, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante", description: "Un oficial de tono severo que nunca se sale del manual.", personality: "Reglas primero, siempre.", profile: { s: [74, 70, 72, 82, 72], h: [56, 50, false], ab: ["Sable de doble filo", "Presión de mando"], home: "marineG5" } },

  // ---------- Cipher Pol ----------
  { name: "Jabra", role: ActorRole.CIPHER_POL, powerLevel: 78, factionType: C, factionName: "CP-0", rankLabel: "Agente", devilFruitName: "Inu Inu no Mi: Modelo Lobo", description: "Agente de CP-0: un lobo de sonrisa fácil y mandíbula letal.", personality: "Bocazas, competitivo y muy rápido.", profile: { s: [80, 92, 76, 76, 70], h: [60, 60, false], phase: "initial", ab: ["Híbrido de lobo", "Rokushiki: Shigan", "Persecución"], home: "eniesLobby" } },
  { name: "Blueno", role: ActorRole.CIPHER_POL, powerLevel: 78, factionType: C, factionName: "CP-0", rankLabel: "Agente (Puerta Blanca)", devilFruitName: "Doa Doa no Mi", description: "Puertas en el aire y silencio en la sala: un asesino de oficina.", personality: "Frío, correcto y profesional.", profile: { s: [76, 86, 74, 80, 78], h: [50, 60, false], phase: "advanced", ab: ["Puertas en cualquier superficie", "Rokushiki", "Emboscada silenciosa"], home: "eniesLobby" } },
  { name: "Fukuro", role: ActorRole.CIPHER_POL, powerLevel: 68, factionType: C, factionName: "CP-0", rankLabel: "Agente", description: "Agente de CP-0 de sonrisa y lengua afiladas.", personality: "Hablador y cruel.", profile: { s: [70, 80, 68, 72, 64], h: [40, 40, false], ab: ["Cremallera: cortar y unir", "Rokushiki básico"], home: "eniesLobby" } },
  { name: "Kumadori", role: ActorRole.CIPHER_POL, powerLevel: 68, factionType: C, factionName: "CP-0", rankLabel: "Agente", description: "Luchador de estilo teatral, con voz de kabuki.", personality: "Melodramático y honorable.", profile: { s: [74, 72, 74, 76, 60], h: [40, 40, false], ab: ["Kabuki: Cuerpo de baile", "Rokushiki de fuerza"], home: "eniesLobby" } },

  // ---------- Grandes tripulaciones: Pelirroja ----------
  { name: "Silvers Rayleigh", role: NP, powerLevel: 96, factionType: U, factionName: "Ex-Piratas de Roger", rankLabel: "El Rey Oscuro", canonBounty: B(0), canonWeapon: "Katana", description: "La mano derecha del Rey de los Piratas: hoy vive en Sabaody, pero su sombra aún hace temblar al mundo.", personality: "Sereno, sabio y de mirada afilada; un maestro que no necesita gritar.", profile: { s: [92, 88, 92, 98, 94], h: [98, 96, true], ab: ["Haoshoku de Rey", "Corte ondulante de Armadura", "Sabiduría de la Era de Roger"], home: "sabaody" } },
  { name: "Benn Beckman", role: NP, powerLevel: 90, factionType: P, factionName: "Piratas Pelirrojos", rankLabel: "Vicecapitán", canonBounty: B(2_140_000_000), canonWeapon: "Fusil de precisión", description: "El vicecapitán de Shanks: cerebro, puntería y calma en la peor tormenta.", personality: "Sereno, irónico y siempre unos pasos por delante.", profile: { s: [86, 82, 84, 92, 96], h: [88, 92, false], ab: ["Disparo de larga distancia", "Estrategia de crew", "Haki de Armadura sobre balas"], home: "foosha" } },
  { name: "Lucky Roo", role: NP, powerLevel: 74, factionType: P, factionName: "Piratas Pelirrojos", canonBounty: B(331_000_000), description: "El comilón de los Pelirrojos: un pirata grande que parte carne y huesos.", personality: "Alegre y voraz.", profile: { s: [84, 60, 84, 74, 50], h: [50, 30, false], ab: ["Puñetazo de fuerza bruta", "Aguante enorme"], home: "foosha" } },
  { name: "Yasopp", role: NP, powerLevel: 78, factionType: P, factionName: "Piratas Pelirrojos", canonBounty: B(500_000_000), canonWeapon: "Fusil", description: "Francotirador legendario y padre de Usopp.", personality: "Sonriente y cariñoso; puntería sin rival.", profile: { s: [70, 80, 70, 84, 76], h: [58, 84, false], ab: ["Tiro a 1000 metros", "Disparo curvo", "Puntería de leyenda"], home: "foosha" } },

  // ---------- Barbablanca ----------
  { name: "Marco", role: NP, powerLevel: 90, factionType: P, factionName: "Ex-Piratas de Barbablanca", rankLabel: "El Fénix", canonBounty: B(1_374_000_000), devilFruitName: "Tori Tori no Mi: Modelo Fénix", description: "Comandante de la 1ª flota de Barbablanca: llamas azules que curan.", personality: "Perezoso pero firme; el mayor de los hijos de Barbablanca.", profile: { s: [84, 92, 88, 92, 82], h: [80, 84, false], phase: "awakened", ab: ["Llamas azules regeneradoras", "Garras de fénix", "Vuelo"], home: "sabaody" } },
  { name: "Vista", role: NP, powerLevel: 84, factionType: P, factionName: "Ex-Piratas de Barbablanca", rankLabel: "Comandante de la 5ª flota", canonBounty: B(1_000_000_000), description: "El Esgrimista de la Flor: espadachín elegante y pulcro.", personality: "Refinado, honorable, obsesionado con sus flores.", profile: { s: [86, 84, 80, 88, 78], h: [84, 78, false], ab: ["Corte florido", "Estilo dual de espadas"], home: "sabaody" } },
  { name: "Jozu", role: NP, powerLevel: 86, factionType: P, factionName: "Ex-Piratas de Barbablanca", rankLabel: "Comandante de la 3ª flota", canonBounty: B(1_000_000_000), devilFruitName: "Dia Dia no Mi", description: "El Diamante: un muro imposible de romper.", personality: "Serio y protector.", profile: { s: [88, 66, 94, 88, 72], h: [80, 60, false], phase: "advanced", ab: ["Cuerpo de diamante", "Puño diamantino", "Muro humano"], home: "sabaody" } },

  // ---------- Piratas de Barbanegra ----------
  { name: "Jesus Burgess", role: NP, powerLevel: 84, factionType: P, factionName: "Piratas de Barbanegra", rankLabel: "Campeón", canonBounty: B(2_000_000_000), description: "El Campeón de Barbanegra: un gigante de fuerza bruta.", personality: "Pendenciero y bocazas.", profile: { s: [92, 60, 90, 76, 40], h: [60, 40, false], ab: ["Choque en carrera", "Golpes de gigante"], home: "graveyardIsland" } },
  { name: "Shiryu", role: NP, powerLevel: 88, factionType: P, factionName: "Piratas de Barbanegra", rankLabel: "El de la Lluvia", canonBounty: B(1_000_000_000), canonWeapon: "Katana Kabuto", description: "Ex-jefe de Impel Down: espadachín sádico y ambicioso.", personality: "Frío, calculador y sediento de poder.", profile: { s: [88, 86, 82, 88, 84], h: [80, 84, false], ab: ["Esgrima de Armadura", "Estrategia", "Lluvia de cortes"], home: "graveyardIsland" } },
  { name: "Van Augur", role: NP, powerLevel: 78, factionType: P, factionName: "Piratas de Barbanegra", rankLabel: "El Francotirador", canonBounty: B(600_000_000), description: "El francotirador que apunta desde el fin del horizonte.", personality: "Silencioso, leal a Barbanegra.", profile: { s: [70, 76, 70, 80, 74], h: [60, 82, false], ab: ["Disparo de larga distancia", "Rifle de asalto"], home: "graveyardIsland" } },
  { name: "Laffitte", role: NP, powerLevel: 80, factionType: P, factionName: "Piratas de Barbanegra", rankLabel: "El Poeta", canonBounty: B(600_000_000), description: "Un asesino elegante que declama versos mientras corta.", personality: "Melancólico y letal.", profile: { s: [76, 90, 72, 78, 84], h: [62, 74, false], ab: ["Espadón fino", "Versos de muerte", "Saltos"], home: "graveyardIsland" } },
  { name: "Avalo Pizarro", role: NP, powerLevel: 80, factionType: P, factionName: "Piratas de Barbanegra", rankLabel: "El Rey del Exilio", canonBounty: B(600_000_000), description: "Coloso de Impel Down, un demonio de escamas duras.", personality: "Sanguinario y bruto.", profile: { s: [90, 64, 88, 76, 46], h: [60, 40, false], ab: ["Puños como rocas", "Aguante brutal"], home: "graveyardIsland" } },

  // ---------- Piratas de las Bestias ----------
  { name: "King", role: NP, powerLevel: 92, factionType: P, factionName: "Piratas de las Bestias", rankLabel: "El Conflagración (Calamidad)", canonBounty: B(1_390_000_000), devilFruitName: "Ryu Ryu no Mi: Modelo Pteranodon", description: "Lunarian de alas ardientes, comandante de los Calamidades de Kaido.", personality: "Silencioso, orgulloso y leal a Kaido.", profile: { s: [92, 92, 90, 88, 76], h: [88, 86, false], phase: "awakened", ab: ["Vuelo en llamas", "Sable ardiente", "Fuerza de Lunarian"], home: "wano" } },
  { name: "Queen", role: NP, powerLevel: 88, factionType: P, factionName: "Piratas de las Bestias", rankLabel: "La Plaga (Calamidad)", canonBounty: B(1_320_000_000), devilFruitName: "Ryu Ryu no Mi: Modelo Brachiosaurus", description: "Científico y bailarín: mitad cyborg, mitad festival.", personality: "Teatral, cruel y muy inteligente.", profile: { s: [90, 66, 94, 76, 92], h: [64, 66, false], phase: "advanced", ab: ["Armas integradas", "Ondas de choque de cuello", "Plagas de laboratorio"], home: "wano" } },
  { name: "Jack", role: NP, powerLevel: 88, factionType: P, factionName: "Piratas de las Bestias", rankLabel: "La Sequía (Calamidad)", canonBounty: B(1_000_000_000), devilFruitName: "Zou Zou no Mi: Modelo Mamut", description: "El coloso mamut de Kaido: sequía y destrucción.", personality: "Cruel y voraz.", profile: { s: [94, 64, 96, 82, 50], h: [78, 50, false], phase: "advanced", ab: ["Aplastamiento de mamut", "Colmillos gigantes", "Aguante titánico"], home: "wano" } },
  { name: "Ulti", role: NP, powerLevel: 76, factionType: P, factionName: "Piratas de las Bestias", rankLabel: "Pluma Volante", canonBounty: B(700_000_000), devilFruitName: "Ryu Ryu no Mi: Modelo Pachycephalosaurus", description: "Embestida de cabeza que parte muros.", personality: "Ruidosa y competitiva.", profile: { s: [82, 74, 84, 76, 50], h: [50, 30, false], phase: "advanced", ab: ["Cabezazo demoledor", "Carga en línea recta"], home: "wano" } },

  // ---------- Big Mom ----------
  { name: "Charlotte Perospero", role: NP, powerLevel: 84, factionType: P, factionName: "Piratas de Big Mom", rankLabel: "Ministro del Azúcar", canonBounty: B(700_000_000), devilFruitName: "Pero Pero no Mi", description: "El hijo mayor de Big Mom: caramelos que aprisionan.", personality: "Refinado y calculador.", profile: { s: [72, 70, 74, 84, 88], h: [60, 78, false], phase: "advanced", ab: ["Caramelo endurecido", "Lamedura de hierro", "Estrategia de alianzas"], home: "wholeCake" } },
  { name: "Charlotte Cracker", role: NP, powerLevel: 84, factionType: P, factionName: "Piratas de Big Mom", rankLabel: "Ministro de la Galleta", canonBounty: B(860_000_000), devilFruitName: "Bisu Bisu no Mi", description: "Un ejército de galletas duras como el acero: un soldado nunca solo.", personality: "Orgulloso y tramposo.", profile: { s: [78, 74, 80, 78, 80], h: [66, 70, false], phase: "advanced", ab: ["Ejército de galletas", "Armadura de galleta", "Cañones de galleta"], home: "wholeCake" } },
  { name: "Charlotte Smoothie", role: NP, powerLevel: 84, factionType: P, factionName: "Piratas de Big Mom", rankLabel: "Ministra del Jugo", canonBounty: B(932_000_000), devilFruitName: "Shibo Shibo no Mi", description: "Exprime cuerpos hasta dejarlos secos.", personality: "Seca, directa y pragmática.", profile: { s: [74, 82, 74, 86, 76], h: [66, 70, false], phase: "advanced", ab: ["Exprimir", "Rejuvenecer al rival por presión", "Cuerpo largo"], home: "wholeCake" } },

  // ---------- Reyes/warlords viejos ----------
  { name: "Gecko Moria", role: ActorRole.WARLORD, powerLevel: 86, factionType: P, factionName: "Ex-Shichibukai", rankLabel: "Ex-Shichibukai", canonBounty: B(320_000_000), devilFruitName: "Kage Kage no Mi", description: "El señor de la Thriller Bark: roba sombras y levanta ejércitos de zombis.", personality: "Perezoso, vanidoso y peligroso.", profile: { s: [88, 60, 92, 78, 76], h: [66, 50, false], phase: "advanced", ab: ["Ejército de sombras", "Nightmare Luffy", "Cuerpo sobredimensionado"], home: "graveyardIsland" } },
  { name: "Bartholomew Kuma", role: ActorRole.WARLORD, powerLevel: 90, factionType: R, factionName: "Ejército Revolucionario", rankLabel: "Ex-Shichibukai", canonBounty: B(296_000_000), devilFruitName: "Nikyu Nikyu no Mi", description: "El Tirano, ahora pastor de los suyos: sus palmas repelen todo.", personality: "Solemne y amable, un padre roto.", profile: { s: [94, 78, 96, 96, 84], h: [70, 66, false], phase: "awakened", ab: ["Ursus Shock", "Teletransporte de Nikyu", "Pad Ho", "Mano que borra el dolor"], home: "baltigo" } },

  // ---------- Mares del Este ----------
  { name: "Arlong", role: NP, powerLevel: 46, factionType: P, factionName: "Piratas de Arlong", rankLabel: "Rey de Cocoyasi", canonBounty: B(20_000_000), canonWeapon: "Kiribachi", description: "Un hombre-pez que sometió el sur de East Blue con tributos y miedo.", personality: "Arrogante y despreciativo con los humanos.", profile: { s: [80, 72, 78, 66, 56], h: [10, 10, false], ab: ["Sierra Nariz: Shark on Tooth", "Karate hombre-pez", "Fuerza bajo el agua"], home: "conomi" } },
  { name: "Kuro", role: NP, powerLevel: 38, factionType: P, factionName: "Piratas del Gato Negro", rankLabel: "Kuro de los Cien Planes", canonBounty: B(16_000_000), canonWeapon: "Guantes de garras", description: "Un pirata que fingía ser mayordomo para robar una fortuna.", personality: "Meticuloso y despiadado.", profile: { s: [62, 92, 56, 62, 82], h: [10, 20, false], ab: ["Paso a Paso (Shakushi)", "Garras afiladas", "Planes de cien pasos"], home: "shimotsuki" } },
  { name: "Don Krieg", role: NP, powerLevel: 40, factionType: P, factionName: "Flota Krieg", rankLabel: "Almirante de la Flota", canonBounty: B(17_000_000), canonWeapon: "Armadura con armas integradas", description: "Almirante de la Flota Krieg: arma lo que puede y avanza.", personality: "Orgulloso, ambicioso y explosivo.", profile: { s: [68, 52, 74, 66, 50], h: [10, 0, false], ab: ["Armadura con mil armas", "Bombas de gas", "Flota masiva"], home: "baratie" } },
  { name: "Alvida", role: NP, powerLevel: 26, factionType: P, factionName: "Piratas de Alvida", rankLabel: "Capitana", canonBounty: B(5_000_000), canonWeapon: "Maza de hierro", description: "Vanidosa de los mares del Este: hoy más esbelta y menos ingenua.", personality: "Presumida, arrolladora y terca.", profile: { s: [48, 46, 46, 52, 38], h: [0, 0, false], ab: ["Maza de hierro", "Liposucción de la fruta"], home: "foosha" } },
  { name: "Wapol", role: NP, powerLevel: 50, factionType: P, factionName: "Ex-Rey de Drum", rankLabel: "Ex-Rey", devilFruitName: "Baku Baku no Mi", description: "Un rey glotón que devoraba armas y castillos.", personality: "Egoísta, quejoso y avariciado.", profile: { s: [54, 46, 60, 46, 44], h: [10, 0, false], phase: "advanced", ab: ["Comer y fusionar objetos", "Castillo de armas", "Devorar edificios"], home: "drum" } },
  { name: "Bon Clay (Mr. 2)", role: NP, powerLevel: 70, factionType: R, factionName: "Ejército Revolucionario", rankLabel: "Okama del Okama Kenpo", canonBounty: B(32_000_000), devilFruitName: "Mane Mane no Mi", description: "Bailarín con un corazón enorme: imita a cualquiera que haya tocado.", personality: "Escandaloso, leal y emocional.", profile: { s: [72, 84, 72, 92, 66], h: [30, 20, false], phase: "advanced", ab: ["Okama Kenpo", "Imitación exacta de cara y cuerpo", "Cisne del Ballet"], home: "baltigo" } },

  // ---------- Generación Peor y otros capitanes ----------
  { name: "Urouge", role: NP, powerLevel: 72, factionType: P, factionName: "Piratas Urouge", rankLabel: "El Monje Loco", canonBounty: B(108_000_000), description: "Monje guerrero de Skypiea, con músculos como muros.", personality: "Templado y agresivo a la vez.", profile: { s: [88, 60, 88, 82, 58], h: [50, 40, false], ab: ["Aura de monje", "Golpes de Kairoseki"], home: "sabaody" } },
  { name: "Scratchmen Apoo", role: NP, powerLevel: 78, factionType: P, factionName: "Piratas Apoo", rankLabel: "Capitán", canonBounty: B(350_000_000), devilFruitName: "Oto Oto no Mi", description: "Un bardo de tres brazos que se convierte en su propio instrumento.", personality: "Astuto, sonriente y oportunista.", profile: { s: [70, 84, 72, 84, 88], h: [60, 82, false], phase: "advanced", ab: ["Ondas de sonido", "Vibraciones que desorientan", "Música de combate"], home: "sabaody" } },
  { name: "Capone Bege", role: NP, powerLevel: 84, factionType: P, factionName: "Familia Firetank", rankLabel: "Gran Capo", canonBounty: B(1_057_000_000), devilFruitName: "Shiro Shiro no Mi", description: "Un capo que vive dentro de su propio castillo humano.", personality: "Calculador, elegante y mafioso.", profile: { s: [74, 72, 78, 88, 90], h: [56, 74, false], phase: "advanced", ab: ["Castillo en su interior", "Ejército de homie", "Cañones escondidos"], home: "sabaody" } },
  { name: "Cavendish", role: NP, powerLevel: 78, factionType: P, factionName: "Piratas de Cavendish", rankLabel: "El Príncipe de Bella", canonBounty: B(330_000_000), canonWeapon: "Durandal", description: "El príncipe de los piratas: elegancia, y a veces Hakuba.", personality: "Narcisista, encantador y peligrosísimo cuando se transforma.", profile: { s: [80, 88, 74, 74, 70], h: [56, 60, false], ab: ["Corte de la Luna", "Hakuba: el asesino nocturno", "Esgrima refinada"], home: "wano" } },
  { name: "Bartolomeo", role: NP, powerLevel: 66, factionType: P, factionName: "Piratas Barto Club", rankLabel: "El Caníbal", canonBounty: B(200_000_000), devilFruitName: "Bari Bari no Mi", description: "Superfán de Luffy: sus barreras son pura devoción.", personality: "Escandaloso, leal y con lágrimas fáciles.", profile: { s: [60, 66, 74, 84, 60], h: [30, 30, false], phase: "advanced", ab: ["Barrera invisible", "Bari Bari Star", "Fuerza de barrera comprimida"], home: "wano" } },
  { name: "Bellamy", role: NP, powerLevel: 60, factionType: P, factionName: "Piratas de Donquixote (ex)", rankLabel: "El Hiena", canonBounty: B(195_000_000), devilFruitName: "Bane Bane no Mi", description: "Un pirata que aprendió a respetar a los débiles.", personality: "Agresivo, orgulloso y arrepentido.", profile: { s: [72, 74, 66, 66, 40], h: [30, 20, false], phase: "advanced", ab: ["Patadas de resorte", "Springs de brazo"], home: "sabaody" } },

  // ---------- Donquixote ----------
  { name: "Diamante", role: NP, powerLevel: 78, factionType: P, factionName: "Familia Donquixote", rankLabel: "Comandante", description: "Un comandante de Dressrosa con una capa que corta.", personality: "Feroz y leal a Doflamingo.", profile: { s: [80, 80, 76, 76, 60], h: [60, 40, false], ab: ["Capa de Diamante", "Ráfagas de cortes", "Torbellino de hojas"], home: "sabaody" } },
  { name: "Trebol", role: NP, powerLevel: 72, factionType: P, factionName: "Familia Donquixote", rankLabel: "Comandante", canonBounty: B(0), description: "El viscoso: baba pegajosa y una lengua peor.", personality: "Viscoso y taimado.", profile: { s: [60, 66, 80, 78, 92], h: [40, 40, false], ab: ["Baba pegajosa", "Engaño de doble cara"], home: "sabaody" } },

  // ---------- Wano ----------
  { name: "Yamato", role: NP, powerLevel: 92, factionType: P, factionName: "Nueva Era de Wano", rankLabel: "Hija de Kaido", canonWeapon: "Kanabo", devilFruitName: "Inu Inu no Mi: Modelo Okuchi no Makami", description: "Se proclama Kozuki Oden: hija de Kaido que quiere abrir Wano.", personality: "Idealista, alegre y muy fuerte.", profile: { s: [94, 88, 92, 96, 74], h: [92, 80, true], phase: "awakened", ab: ["Hakai: Thunder Bagua", "Forma de lobo divino", "Hielo de Okuchi", "Haoshoku de Rey"], home: "wano" } },
  { name: "Kin'emon", role: NP, powerLevel: 74, factionType: P, factionName: "Samuráis de Wano", rankLabel: "Samurái", canonWeapon: "Shusui y Zanbato", description: "Samurái que viaja en el tiempo de las hojas: hace magia de zorro.", personality: "Honorable y algo excéntrico.", profile: { s: [78, 80, 74, 88, 72], h: [66, 58, false], ab: ["Fuego de zorro", "Magia de hojas", "Esgrima samurái"], home: "wano" } },
  { name: "Raizo", role: NP, powerLevel: 66, factionType: P, factionName: "Samuráis de Wano", rankLabel: "Ninja", description: "Un ninja de Wano, maestro del disfraz.", personality: "Serio y desenfadado.", profile: { s: [60, 88, 58, 80, 70], h: [30, 50, false], ab: ["Ninpo: humo", "Cambio de forma", "Sombras"], home: "wano" } },
  { name: "Nekomamushi", role: NP, powerLevel: 78, factionType: P, factionName: "Mink de Zou", rankLabel: "Rey de la Noche", description: "Rey de la Noche de los mink.", personality: "Testarudo y noble.", profile: { s: [88, 82, 84, 82, 60], h: [70, 60, false], ab: ["Electro: garras de rayo", "Sulong: luna llena"], home: "wano" } },
  { name: "Inuarashi", role: NP, powerLevel: 78, factionType: P, factionName: "Mink de Zou", rankLabel: "Duque del Día", description: "Duque de los mink: fuerza y lealtad.", personality: "Ceremonioso y orgulloso.", profile: { s: [86, 80, 84, 84, 64], h: [70, 60, false], ab: ["Electro: rayos", "Sulong: luna llena"], home: "wano" } },
  { name: "Carrot", role: NP, powerLevel: 60, factionType: P, factionName: "Mink de Zou", rankLabel: "Guerrera Sulong", description: "Una jovencita mink que se vuelve muy peligrosa con luna llena.", personality: "Alegre, curiosa y valiente.", profile: { s: [66, 90, 60, 72, 56], h: [30, 40, false], ab: ["Sulong: luna llena", "Electro", "Patadas rápidas"], home: "wano" } },
  { name: "Kozuki Momonosuke", role: ActorRole.NOTABLE_CIVILIAN, powerLevel: 40, factionType: CIV, factionName: "Wano", rankLabel: "Shogun", description: "Un niño convertido en shogun: aprende a ser fuerte.", personality: "Dulce y con gran sentido de la responsabilidad.", profile: { s: [40, 50, 44, 76, 66], h: [10, 10, false], ab: ["Dragón de nubes", "Liderazgo de un país"], home: "wano" } },
  { name: "Nefertari Vivi", role: ActorRole.NOTABLE_CIVILIAN, powerLevel: 40, factionType: CIV, factionName: "Reino de Alabasta", rankLabel: "Princesa", description: "La princesa de Alabasta que se mantuvo firme por su gente.", personality: "Valiente, honesta y diplomática.", profile: { s: [40, 60, 42, 86, 80], h: [0, 0, false], ab: ["Diplomacia", "Cuchillas Peacock", "Liderazgo"], home: "alabasta" } },
  { name: "Shirahoshi", role: ActorRole.NOTABLE_CIVILIAN, powerLevel: 70, factionType: CIV, factionName: "Reino Ryugu", rankLabel: "Princesa Sirena", description: "La Poseidón: una princesa gigante que oye a los reyes del mar.", personality: "Tímida, bondadosa y con un poder que ella misma teme.", profile: { s: [40, 40, 90, 96, 60], h: [0, 0, false], ab: ["Voz de Poseidón", "Comunicación con reyes marinos"], home: "fishMan", hidden: true } },

  // ---------- Revolucionarios ----------
  { name: "Belo Betty", role: ActorRole.REVOLUTIONARY_COMMANDER, powerLevel: 82, factionType: R, factionName: "Ejército Revolucionario", rankLabel: "Comandante de la 2ª división", canonBounty: B(457_000_000), description: "Comandante revolucionaria: le encanta reunir apoyos.", personality: "Vivaz, práctica y contagiosa.", profile: { s: [72, 78, 74, 88, 86], h: [60, 60, false], ab: ["Persuasión", "Estrategia", "Liderazgo popular"], home: "baltigo" } },
  { name: "Lindbergh", role: ActorRole.REVOLUTIONARY_COMMANDER, powerLevel: 80, factionType: R, factionName: "Ejército Revolucionario", rankLabel: "Comandante de la 4ª división", description: "Un guerrero Lunarian entre los revolucionarios.", personality: "Sereno y práctico.", profile: { s: [80, 82, 78, 82, 74], h: [64, 58, false], ab: ["Cañones en el brazo", "Fuerza de Lunarian"], home: "baltigo" } },
  { name: "Morley", role: ActorRole.REVOLUTIONARY_COMMANDER, powerLevel: 82, factionType: R, factionName: "Ejército Revolucionario", rankLabel: "Comandante de la 3ª división", description: "Gigante de Elbaf de mirada serena.", personality: "Filósofo y tranquilo.", profile: { s: [92, 60, 92, 80, 76], h: [66, 50, false], ab: ["Fuerza de gigante", "Cuernos de escudo"], home: "baltigo" } },
  { name: "Karasu", role: ActorRole.REVOLUTIONARY_COMMANDER, powerLevel: 78, factionType: R, factionName: "Ejército Revolucionario", rankLabel: "Comandante de la 5ª división", description: "Un maestro de las bandadas de cuervos.", personality: "Callado y penetrante.", profile: { s: [70, 90, 68, 82, 84], h: [56, 74, false], ab: ["Bandada de cuervos", "Espionaje", "Sombras"], home: "baltigo", hidden: true } },
  { name: "Hack", role: ActorRole.REVOLUTIONARY_COMMANDER, powerLevel: 76, factionType: R, factionName: "Ejército Revolucionario", rankLabel: "Comandante de la 1ª división", description: "Hombre-pez de estilo karate y corazón revolucionario.", personality: "Sereno y contundente.", profile: { s: [80, 72, 78, 82, 68], h: [56, 50, false], ab: ["Karate hombre-pez", "Agua a presión"], home: "baltigo" } },

  // ---------- Otros ----------
  { name: "Vinsmoke Judge", role: NP, powerLevel: 82, factionType: P, factionName: "Reino Germa 66", rankLabel: "Rey de Germa", description: "El jefe de Germa 66, científico que quiso fabricar guerreros.", personality: "Frío y calculador.", profile: { s: [78, 74, 76, 84, 92], h: [56, 50, false], ab: ["Ejército de clones", "Armas de Germa"], home: "whiskyPeak" } },
  { name: "Vinsmoke Reiju", role: NP, powerLevel: 74, factionType: P, factionName: "Reino Germa 66", rankLabel: "Princesa de Germa", description: "La hermana de Sanji: veneno y elegancia.", personality: "Sutil, fría y amable en secreto.", profile: { s: [66, 84, 64, 80, 80], h: [30, 40, false], ab: ["Sangre venenosa", "Puñalada de veneno"], home: "whiskyPeak" } },
  { name: "Vegapunk", role: ActorRole.NOTABLE_CIVILIAN, powerLevel: 60, factionType: C, factionName: "Gobierno Mundial", rankLabel: "El mayor genio del mundo", description: "El científico más brillante de su siglo: inventor de la tecnología que cambió la era.", personality: "Curioso, obsesivo y con un corazón dividido.", profile: { s: [30, 40, 30, 90, 100], h: [0, 0, false], ab: ["Satélites y clones", "Ciencia imposible", "Tecnología del futuro"], home: "punkHazard", hidden: true } },
  { name: "Monet", role: NP, powerLevel: 70, factionType: P, factionName: "Familia Donquixote", rankLabel: "Mujer de las Nieves", devilFruitName: "Yuki Yuki no Mi", description: "Una arpía de nieve: hielo en las alas y astucia en el pico.", personality: "Sonriente, fría y traicionera.", profile: { s: [64, 84, 60, 74, 76], h: [30, 40, false], phase: "initial", ab: ["Cuerpo de nieve", "Tormenta de hielo", "Alas de harpía"], home: "punkHazard" } },
  { name: "Bepo", role: NP, powerLevel: 60, factionType: P, factionName: "Piratas Heart", rankLabel: "Navegante", canonBounty: B(500_000), description: "El oso polar navegante de los Heart: un mink valiente y educado.", personality: "Tímido, leal y educado.", profile: { s: [72, 84, 68, 82, 66], h: [26, 36, false], ab: ["Sulong: luna llena", "Puño de oso", "Navegación en ruta"], home: "punkHazard" } },
];
