/**
 * Fifth wave of the canon cast (2026-09-27): well-known characters that were still missing from the
 * Whitebeard, Roger, Sun, Big Mom, Donquixote, Wano, Baroque Works, Skypiea, Beasts, Ohara and Fish-Man
 * stories. Same shape and rules as world-actor-extra.ts. Characters whose story ended (or whose fate after
 * their last appearance is unknown) carry a `status` so they live in the codex and the lore without acting.
 * A devil fruit is only listed when it is that character's canon fruit; those fruits are singletons.
 */
import { ActorRole, FactionType } from "@prisma/client";
import type { ExtraActor } from "./world-actor-extra";

const B = (n: number) => BigInt(n);
const P = FactionType.PIRATE;
const CIV = FactionType.CIVILIAN;
const U = FactionType.UNAFFILIATED;
const NP = ActorRole.NOTABLE_PIRATE;
const NC = ActorRole.NOTABLE_CIVILIAN;

export const WAVE5_ACTORS: ExtraActor[] = [
  // ---------- Piratas de Barbablanca ----------
  { name: "Thatch", role: NP, powerLevel: 66, status: "DECEASED", factionType: P, factionName: "Piratas de Barbablanca", rankLabel: "Comandante de la 4ª división", description: "El cocinero-comandante de Barbablanca, alma de la cubierta. Barbanegra lo asesinó para robarle el Yami Yami no Mi y huyó del barco.", personality: "Campechano, generoso y siempre con una broma; tan buen cocinero como luchador.", profile: { s: [68, 66, 66, 78, 62], h: [56, 52, false], ab: ["Cuchillos y sable de cocina", "Mando de una división", "Lealtad a Barbablanca"], home: "marineford" } },
  { name: "Izo", role: NP, powerLevel: 76, status: "RETIRED", factionType: P, factionName: "Piratas de Barbablanca", rankLabel: "Comandante de la 16ª división", canonWeapon: "Pistolas y katana", description: "El comandante nacido en Wano que peleó en Marineford al lado de sus hermanos. Su paradero tras la guerra es incierto.", personality: "Elegante y sereno; disparo certero, palabra medida.", profile: { s: [72, 84, 68, 84, 76], h: [70, 74, false], ab: ["Tiro doble de precisión", "Katana de Wano", "Mando de una división"], home: "marineford" } },
  { name: "Namur", role: NP, powerLevel: 74, status: "RETIRED", factionType: P, factionName: "Piratas de Barbablanca", rankLabel: "Comandante Hombre-Pez", description: "Un hombre-pez de la flota de Barbablanca, fuerte como una roca bajo el agua. Nada se sabe de él tras Marineford.", personality: "Callado y firme; fiel a su capitán hasta el último momento.", profile: { s: [80, 70, 80, 78, 56], h: [64, 50, false], ab: ["Karate Hombre-Pez", "Combate submarino", "Lealtad a Barbablanca"], home: "marineford" } },

  // ---------- Piratas de Roger ----------
  { name: "Scopper Gaban", role: NP, powerLevel: 86, status: "RETIRED", factionType: P, factionName: "Piratas de Roger", rankLabel: "Tripulante de Gol D. Roger", description: "Uno de los hombres de Roger en el viaje que llegó hasta Laugh Tale. Tras la disolución de la tripulación su paradero es incierto.", personality: "Reservado y leal a una promesa que nadie más recuerda.", profile: { s: [88, 84, 86, 90, 82], h: [88, 84, false], ab: ["Esgrima de la era dorada", "Haki curtido en la Gran Línea", "Conocimiento del último viaje de Roger"], home: "sabaody", hidden: true } },
  { name: "Crocus", role: NC, powerLevel: 56, factionType: CIV, factionName: "Reverse Mountain", rankLabel: "Farero y médico", description: "El farero de Cabo Gemelo, antiguo médico de la tripulación de Roger, que cuida de la ballena Laboon desde hace décadas.", personality: "Paciente y de humor seco; la promesa que guarda le pesa menos que la soledad.", profile: { s: [46, 44, 52, 82, 88], h: [26, 48, false], ab: ["Medicina de a bordo", "Conocimiento de la Gran Línea", "Cuidado de Laboon"], home: "reverseMountain" } },

  // ---------- Piratas del Sol y de Arlong ----------
  { name: "Fisher Tiger", role: NP, powerLevel: 80, status: "DECEASED", factionType: P, factionName: "Piratas del Sol", rankLabel: "Capitán", canonBounty: B(230_000_000), description: "El hombre-pez que fue esclavo de los Dragones Celestiales, liberó a otros esclavos y fundó los Piratas del Sol. Murió por no aceptar sangre humana.", personality: "Orgulloso, íntegro y tozudo; jamás pidió a nadie lo que él no daría.", profile: { s: [86, 76, 82, 92, 70], h: [70, 60, false], ab: ["Karate Hombre-Pez", "Liberación de esclavos", "Nadie más sufrirá lo que yo sufrí"], home: "fishMan" } },
  { name: "Kuroobi", role: NP, powerLevel: 48, status: "DEFEATED", factionType: P, factionName: "Piratas de Arlong", rankLabel: "Oficial", description: "El hombre-pez raya de Arlong, maestro de karate hombre-pez y del Arlong Park. Cayó ante los Sombrero de Paja.", personality: "Frío, cruel y convencido de la superioridad de su especie.", profile: { s: [60, 56, 58, 62, 52], h: [16, 24, false], ab: ["Karate Hombre-Pez", "Golpes de agua a presión", "Desprecio a los humanos"], home: "fishMan" } },
  { name: "Chew", role: NP, powerLevel: 44, status: "DEFEATED", factionType: P, factionName: "Piratas de Arlong", rankLabel: "Oficial", description: "El glotón del grupo de Arlong: labios enormes, hambre insaciable y fe ciega en su capitán. Cayó en Arlong Park.", personality: "Ruidoso y voraz; se ríe mientras devora lo que otros trabajaron.", profile: { s: [58, 46, 60, 60, 40], h: [12, 18, false], ab: ["Karate Hombre-Pez", "Mordida devastadora", "Aguante de glotón"], home: "fishMan" } },

  // ---------- Reino Ryugu ----------
  { name: "Otohime", role: NC, powerLevel: 34, status: "DECEASED", factionType: CIV, factionName: "Reino Ryugu", rankLabel: "Reina", description: "La reina que soñó con la convivencia entre humanos y hombres-pez. Fue asesinada, y su muerte encendió el odio que su pueblo tardó años en sanar.", personality: "Dulce, tenaz y capaz de perdonar lo imperdonable.", profile: { s: [26, 34, 32, 90, 84], h: [0, 40, false], ab: ["Diplomacia", "Voz de la paz", "Sueño de convivencia"], home: "fishMan" } },
  { name: "Fukaboshi", role: NC, powerLevel: 58, factionType: CIV, factionName: "Reino Ryugu", rankLabel: "Príncipe", description: "El primogénito de Ryugu, sereno y prudente, que defendió su reino con el tridente y la palabra cuando el odio amenazó con destruirlo.", personality: "Noble, sensato y sensible a los reproches de su pueblo.", profile: { s: [62, 60, 62, 80, 74], h: [30, 52, false], ab: ["Karate Hombre-Pez", "Tridente real", "Liderazgo del reino"], home: "fishMan" } },

  // ---------- Big Mom ----------
  { name: "Charlotte Brûlée", role: NP, powerLevel: 72, factionType: P, factionName: "Piratas de Big Mom", rankLabel: "Ministra del Espejo", devilFruitName: "Mira Mira no Mi", description: "La hija de Big Mom que vive en el Mundo Espejo: desde allí atrapa, copia y arrastra a sus víctimas a un espejo del que no se sale sin ella.", personality: "Fría, esquiva y cruel; sonríe solo cuando ya ha atrapado a alguien.", profile: { s: [60, 78, 62, 78, 80], h: [50, 62, false], phase: "advanced", ab: ["Espejos a voluntad", "Imitación de rostros", "Trampas de espejo"], home: "wholeCake" } },

  // ---------- Familia Donquixote ----------
  { name: "Baby 5", role: NP, powerLevel: 46, status: "DEFEATED", factionType: P, factionName: "Familia Donquixote", rankLabel: "Oficial", devilFruitName: "Buki Buki no Mi", description: "Una mujer que se convierte en arsenal: convierte cualquier parte de su cuerpo en un arma. Solo sabe cuidar a quien la necesite... y solo cuando alguien la necesita.", personality: "Obediente hasta la abnegación; su mayor miedo es que dejen de necesitarla.", profile: { s: [56, 56, 50, 60, 42], h: [24, 26, false], phase: "advanced", ab: ["Cuerpo convertido en armas", "Ametralladoras y cañones", "Lealtad ciega"], home: "dressrosa" } },
  { name: "Buffalo", role: NP, powerLevel: 50, status: "DEFEATED", factionType: P, factionName: "Familia Donquixote", rankLabel: "Oficial", devilFruitName: "Guru Guru no Mi", description: "Un oficial de Doflamingo que gira como una hélice, con las manos convertidas en aspas y los pies en ruedas de huida.", personality: "Ruidoso y bravucón; pierde los nervios cuando no es el más fuerte de la sala.", profile: { s: [58, 56, 56, 58, 40], h: [22, 24, false], phase: "advanced", ab: ["Hélices de brazo", "Giro acelerado", "Bravuconería"], home: "dressrosa" } },
  { name: "Dellinger", role: NP, powerLevel: 62, status: "DEFEATED", factionType: P, factionName: "Familia Donquixote", rankLabel: "Oficial", description: "Mitad hombre-pez y mitad pirata, el más joven de los oficiales de Doflamingo: una patada en salto de tiburón puede partir a un hombre.", personality: "Sarcástico y rabioso; se burla de todo, incluso de su propio dolor.", profile: { s: [66, 78, 60, 62, 54], h: [40, 44, false], ab: ["Patada aérea de tiburón", "Velocidad de nadador", "Ferocidad de niño malcriado"], home: "dressrosa" } },
  { name: "Sugar", role: NP, powerLevel: 40, status: "DEFEATED", factionType: P, factionName: "Familia Donquixote", rankLabel: "Oficial", devilFruitName: "Hobi Hobi no Mi", description: "La niña eterna del Hobi Hobi no Mi: convierte a quien toca en juguete y borra su recuerdo de todos. El hechizo cae si ella pierde la concentración.", personality: "Caprichosa y cruel; llora cuando nadie le hace caso y pega cuando alguien la contradice.", profile: { s: [14, 30, 18, 44, 64], h: [0, 12, false], phase: "advanced", ab: ["Convertir en juguete", "Borrar el recuerdo de quien fue juguete", "Enfado infantil"], home: "dressrosa" } },

  // ---------- Wano ----------
  { name: "Kanjuro", role: NP, powerLevel: 68, status: "RETIRED", factionType: P, factionName: "Samuráis de Wano", rankLabel: "Guardián Rojo (traidor)", devilFruitName: "Fude Fude no Mi", canonWeapon: "Pincel de tinta", description: "El artista de los Nueve Guardianes Rojos: sus dibujos cobran vida, pero traicionó a Oden al servicio de Orochi. Su destino tras la caída de Onigashima es incierto.", personality: "Refinado, teatral y atormentado por la deuda que nunca pudo pagar.", profile: { s: [56, 70, 56, 76, 84], h: [50, 62, false], phase: "advanced", ab: ["Dibujos que cobran vida", "Tinta viva", "Engaño del espía"], home: "wano" } },
  { name: "Kawamatsu", role: NP, powerLevel: 62, factionType: P, factionName: "Samuráis de Wano", rankLabel: "Guardián Rojo (Kappa)", canonWeapon: "Katana", description: "El kappa de los Nueve Guardianes Rojos: bajo el agua es un torbellino, y sobre ella, un espadachín de honor que no olvida.", personality: "Tenaz y cortés; solo se ríe cuando el honor está a salvo.", profile: { s: [68, 64, 66, 82, 60], h: [58, 46, false], ab: ["Esgrima samurái", "Combate acuático", "Lealtad a los Kozuki"], home: "wano" } },
  { name: "Kozuki Hiyori", role: NC, powerLevel: 8, factionType: CIV, factionName: "Clan Kozuki", rankLabel: "Hija de Oden", description: "La hija de Kozuki Oden, criada en la sombra como la cortesana Komurasaki para que Orochi no descubriera quién era. Hoy canta libre en una Wano que despierta.", personality: "Serena, aguda y con humor: aprendió a sobrevivir sin perder la sonrisa.", profile: { s: [6, 14, 8, 60, 56], h: [0, 0, false], ab: ["Canto", "Astucia de cortesana", "Coraje heredado de Oden"], home: "wano" } },
  { name: "Ryuma", role: NP, powerLevel: 84, status: "DECEASED", factionType: U, factionName: "Samuráis de Wano (leyenda)", rankLabel: "Samurái legendario", canonWeapon: "Shusui", description: "El samurái que cortó un dragón, dueño de Shusui hace ochocientos años. Su cuerpo fue reanimado como zombi en Thriller Bark; su alma nunca abandonó Wano.", personality: "Callado y digno; solo le importa una cosa: su espada.", profile: { s: [88, 84, 80, 86, 70], h: [84, 78, false], ab: ["Corte del dragón", "Esgrima de Shusui", "Zombi de una era pasada"], home: "wano" } },

  // ---------- Baroque Works ----------
  { name: "Miss Doublefinger (Zala)", role: NP, powerLevel: 42, status: "DEFEATED", factionType: P, factionName: "Baroque Works", rankLabel: "Agente de Baroque Works", devilFruitName: "Toge Toge no Mi", description: "La agente de las púas: cubre su cuerpo de agujas afiladas y las lanza o las usa como armadura. Cayó en Alabasta.", personality: "Seria y calculadora; nunca pierde la compostura en misión.", profile: { s: [46, 50, 50, 56, 54], h: [18, 24, false], phase: "advanced", ab: ["Púas por todo el cuerpo", "Espinas lanzables", "Frialdad profesional"], home: "alabasta" } },
  { name: "Mr. 4 (Babe)", role: NP, powerLevel: 40, status: "DEFEATED", factionType: P, factionName: "Baroque Works", rankLabel: "Agente de Baroque Works", canonWeapon: "Bate de béisbol gigante", description: "El agente del bate y su perro Lassoo: un gigante con un bate como cañón que lanza bombas con cada golpe. Cayó en Alabasta.", personality: "Torpe, terco y convencido de que la fuerza lo arregla todo.", profile: { s: [56, 34, 60, 52, 30], h: [10, 12, false], ab: ["Bate cañón", "Bombas de béisbol", "Ataques con su perro Lassoo"], home: "alabasta" } },

  // ---------- Skypiea, Drum, Water Seven, East Blue ----------
  { name: "Conis", role: NC, powerLevel: 6, factionType: CIV, factionName: "Skypiea", rankLabel: "Joven de Angel Beach", description: "Una joven de Skypiea que guió a los Sombrero de Paja por las nubes y conoce cada dial y cada camino de su hogar.", personality: "Dulce y curiosa; pregunta por el mar de abajo con los ojos muy abiertos.", profile: { s: [6, 12, 8, 46, 50], h: [0, 0, false], ab: ["Uso de diales", "Conocimiento de Skypiea", "Amistad sincera"], home: "skypiea" } },
  { name: "Doctor Hiluluk", role: NC, powerLevel: 22, status: "DECEASED", factionType: CIV, factionName: "Reino de Drum", rankLabel: "Doctor", description: "El médico charlatán que dio a Chopper el nombre y el sueño de curar cualquier enfermedad. Murió con su sueño, pero los cerezos siguen floreciendo.", personality: "Extravagante, testarudo y tan generoso que se olvidaba de él mismo.", profile: { s: [14, 24, 16, 88, 76], h: [0, 0, false], ab: ["Medicina", "Bandera de Cerezo", "Carisma de charlatán"], home: "drum" } },
  { name: "Kokoro", role: NC, powerLevel: 12, factionType: CIV, factionName: "Water Seven", rankLabel: "Sirena de Cala Sirena", description: "La sirena que guarda un secreto de Water Seven en la Cala Sirena: conoce el mar como pocos y dice cada cosa exactamente cuando conviene.", personality: "Franca, amable y de humor seco; sabe callar mejor que reír.", profile: { s: [12, 24, 16, 60, 56], h: [0, 20, false], ab: ["Conocimiento del mar", "Cuidado de recién llegados", "Diplomacia sin adornos"], home: "waterSeven" } },
  { name: "Kuina", role: NC, powerLevel: 30, status: "DECEASED", factionType: CIV, factionName: "Dojo Shimotsuki", rankLabel: "Alumna del dojo", canonWeapon: "Wado Ichimonji", description: "La hija del maestro Koshiro, mejor espadachín de su edad, rival y promesa de Zoro. Murió tras una caída, y su espada quedó en sus manos.", personality: "Orgullosa y determinada; nunca perdonó ser la mejor y que no la dejaran soñar.", profile: { s: [34, 40, 30, 82, 54], h: [0, 20, false], ab: ["Esgrima de dojo", "Ittoryu", "Promesa a Zoro"], home: "shimotsuki" } },
  { name: "Cabaji", role: NP, powerLevel: 40, factionType: P, factionName: "Buggy's Delivery", rankLabel: "Acróbata de Buggy", canonWeapon: "Sable y monociclo", description: "El acróbata de Buggy: monociclo, sable curvo y tanta convicción de que nunca pierde que hasta le salen los tropiezos con estilo.", personality: "Vanidoso, ruidoso y fiel a Buggy hasta el ridículo.", profile: { s: [50, 62, 48, 60, 44], h: [16, 22, false], ab: ["Acrobacias con sable", "Monociclo de combate", "Lealtad a Buggy"], home: "loguetown" } },

  // ---------- Marina y los Neo Marines ----------
  { name: "Zephyr (Z)", role: NP, powerLevel: 88, status: "RETIRED", factionType: U, factionName: "Neo Marina", rankLabel: "Ex almirante, líder de los Neo Marines", description: "El ex almirante conocido como Z, que dejó la Marina cuando la Justicia le pareció una excusa y fundó los Neo Marines para cazar piratas por su cuenta.", personality: "Obstinado y amargo; su justicia no admite excepciones.", profile: { s: [92, 78, 92, 94, 78], h: [90, 82, false], ab: ["Puño de un ex almirante", "Mando de los Neo Marines", "Odio a los piratas"], home: "marineford", hidden: true } },

  // ---------- Ohara ----------
  { name: "Professor Clover", role: NC, powerLevel: 20, status: "DECEASED", factionType: CIV, factionName: "Ohara", rankLabel: "Arqueólogo jefe", description: "El jefe de los arqueólogos de Ohara, que descifró el Siglo Vacío y murió con su isla bajo el Buster Call, pero antes le entregó a Robin todas las preguntas.", personality: "Amable, cerebral y terco cuando de la verdad se trata.", profile: { s: [14, 20, 18, 90, 96], h: [0, 20, false], ab: ["Lectura de Poneglifos", "Historia del Siglo Vacío", "Fe en la verdad"], home: "ohara" } },
  { name: "Jaguar D. Saul", role: NC, powerLevel: 78, status: "RETIRED", factionType: U, factionName: "Ohara", rankLabel: "Gigante protector de Robin", description: "El gigante que protegió a Robin de niña durante la caída de Ohara. Su paradero tras la caída de la isla es incierto.", personality: "Grande, bonachón y leal a quien protege.", profile: { s: [88, 50, 92, 84, 60], h: [50, 40, false], ab: ["Fuerza de gigante", "Protección de Robin", "Voluntad de hierro"], home: "ohara", hidden: true } },

  // ---------- Piratas de las Bestias ----------
  { name: "Who's Who", role: NP, powerLevel: 78, factionType: P, factionName: "Piratas de las Bestias", rankLabel: "Tobiroppo", canonBounty: B(546_000_000), devilFruitName: "Neko Neko no Mi: Modelo Dientes de Sable", description: "El Tobiroppo del tigre dientes de sable: garras enormes, colmillos capaces de partir acero y una ferocidad que nunca aprendió a apagar.", personality: "Sanguinario y ambicioso; solo respeta a quien lo doblega.", profile: { s: [84, 80, 80, 78, 46], h: [70, 62, false], phase: "advanced", ab: ["Zarpazos de dientes de sable", "Mordida perforadora", "Fuerza bruta"], home: "wano" } },
];
