/**
 * Fourth wave of the canon cast (2026-09-25): the Marine officers of the new headquarters and the bases, the
 * Cipher Pol agents who train the CP-0 recruits on Tequila Wolf, the Impel Down staff, the people of the East
 * Blue villages, Skypiea, Alabasta and the Grand Fleet. Same shape and rules as world-actor-extra.ts. Every
 * `home` is a real island key from prisma/seed.ts: that is where the codex and the narrator place them.
 */
import { ActorRole, FactionType } from "@prisma/client";
import type { ExtraActor } from "./world-actor-extra";

const B = (n: number) => BigInt(n);
const P = FactionType.PIRATE;
const M = FactionType.MARINE;
const R = FactionType.REVOLUTIONARY;
const C = FactionType.CIPHER_POL;
const CIV = FactionType.CIVILIAN;
const NP = ActorRole.NOTABLE_PIRATE;
const MO = ActorRole.MARINE_OFFICER;
const NC = ActorRole.NOTABLE_CIVILIAN;

export const WAVE4_ACTORS: ExtraActor[] = [
  // ---------- Marina: el nuevo cuartel general y las bases ----------
  { name: "Prince Grus", role: MO, powerLevel: 78, factionType: M, factionName: "Marina", rankLabel: "Contraalmirante (SWORD)", description: "Prince Grus: oficial joven de la Marina, miembro de SWORD, que convierte el terreno en un arma.", personality: "Correcto y ambicioso; quiere estar a la altura de sus mentores.", profile: { s: [74, 78, 72, 78, 76], h: [72, 72, false], ab: ["Manipulación del terreno", "Tácticas de SWORD", "Formación de asalto"], home: "nuevoMarineford" } },
  { name: "Kujaku", role: MO, powerLevel: 74, factionType: M, factionName: "Marina", rankLabel: "Capitana (SWORD)", canonWeapon: "Látigo", description: "Nieta adoptiva de Tsuru y miembro de SWORD: un látigo que vuela como un ave y una lealtad sin fisuras.", personality: "Seria, disciplinada y protectora con los suyos.", profile: { s: [70, 80, 70, 76, 74], h: [70, 70, false], ab: ["Látigo de acero", "Presa del ave", "Tácticas de SWORD"], home: "nuevoMarineford" } },
  { name: "Gion (Momousagi)", role: MO, powerLevel: 84, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante (candidata a almirante)", canonWeapon: "Konpira (katana)", description: "Momousagi: vicealmirante de élite, tan cerca del almirantazgo que el nombre ya le quedaba corto.", personality: "Elegante, directa y temible con la espada.", profile: { s: [80, 86, 78, 84, 80], h: [80, 82, false], ab: ["Esgrima de élite", "Tajo de melocotón", "Mando de flota"], home: "nuevoMarineford" } },
  { name: "Tokikake (Chaton)", role: MO, powerLevel: 82, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante (candidato a almirante)", canonWeapon: "Katana", description: "Chaton: vicealmirante de élite y candidato a almirante, un espadachín de gesto relajado y filo impecable.", personality: "Tranquilo y seguro de sí mismo.", profile: { s: [82, 80, 80, 82, 76], h: [78, 76, false], ab: ["Esgrima de élite", "Mando de flota", "Ataque de gato montés"], home: "nuevoMarineford" } },
  { name: "Bastille", role: MO, powerLevel: 72, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante", canonWeapon: "Zanbatō", description: "El 'Tiburón Cortador': vicealmirante gigante con un zanbatō del tamaño de un mástil.", personality: "Ruidoso y confiado; ataca de frente y sin rodeos.", profile: { s: [84, 60, 82, 74, 58], h: [68, 60, false], ab: ["Zanbatō del tiburón", "Tajo que parte muros", "Carga de gigante"], home: "punkHazard" } },
  { name: "Doll", role: MO, powerLevel: 70, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante", description: "Vicealmirante de pocas palabras, conocida por perseguir a sus objetivos hasta el Nuevo Mundo.", personality: "Seria y metódica.", profile: { s: [72, 74, 70, 74, 72], h: [66, 66, false], ab: ["Persecución implacable", "Esgrima marina", "Mando de escuadra"], home: "nuevoMarineford" } },
  { name: "Jonathan", role: MO, powerLevel: 68, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante (comandante de la G-8)", description: "Comandante de la base G-8 de Navarone: un estratega que nunca pierde la calma, ni siquiera cuando su fortaleza se llena de piratas.", personality: "Sereno, irónico y brillante: juega al ajedrez con la guerra.", profile: { s: [60, 62, 64, 76, 92], h: [60, 64, false], ab: ["Estrategia de fortaleza", "Mando de base", "Trampas de Navarone"], home: "navarone" } },
  { name: "Axe-Hand Morgan", role: MO, powerLevel: 30, factionType: M, factionName: "Marina", rankLabel: "Ex-capitán (degradado)", canonWeapon: "Hacha en el brazo", description: "El antiguo tirano del cuartel del East Blue: un brazo de hacha y una mandíbula de acero, degradado pero no olvidado.", personality: "Arrogante y cruel con los débiles.", profile: { s: [40, 24, 38, 30, 18], h: [0, 0, false], ab: ["Mano de hacha", "Mandíbula de acero", "Tiranía de cuartel"], home: "marineG5" } },
  { name: "Nezumi", role: MO, powerLevel: 14, factionType: M, factionName: "Marina", rankLabel: "Capitán corrupto", description: "Un capitán de la Marina que cobraba a Arlong por mirar hacia otro lado. Su risa ('chichichi') suena en cada soborno.", personality: "Rastrero, avaro y cobarde.", profile: { s: [14, 14, 14, 12, 26], h: [0, 0, false], ab: ["Sobornos", "Abuso de autoridad"], home: "conomi" } },
  { name: "Fullbody", role: MO, powerLevel: 22, factionType: M, factionName: "Marina", rankLabel: "Teniente", description: "Teniente presumido que aprende la humildad a base de patadas en el Baratie.", personality: "Presumido, pero con un sentido del deber que crece con los años.", profile: { s: [28, 26, 26, 24, 20], h: [0, 0, false], ab: ["Puños de hierro", "Disciplina marina"], home: "baratie" } },

  // ---------- Impel Down ----------
  { name: "Magellan", role: MO, powerLevel: 86, factionType: M, factionName: "Impel Down", rankLabel: "Jefe de Impel Down", devilFruitName: "Doku Doku no Mi", description: "El alcaide de Impel Down: un hombre de veneno que ha convertido la prisión más temida del mundo en su cuerpo entero.", personality: "Metódico y leal a su deber; se pasa la mitad del día en el baño y la otra mitad siendo invencible.", profile: { s: [84, 60, 90, 88, 70], h: [72, 70, false], ab: ["Hydra de veneno", "Venom Demon", "Mar de veneno"], home: "impelDown" } },
  { name: "Hannyabal", role: MO, powerLevel: 58, factionType: M, factionName: "Impel Down", rankLabel: "Subjefe de Impel Down", canonWeapon: "Naginata", description: "Subjefe de Impel Down que sueña en voz alta con el puesto de su jefe... y que se juega la vida por la prisión cuando toca.", personality: "Ambicioso, ruidoso y, cuando importa, valiente.", profile: { s: [62, 56, 64, 72, 56], h: [50, 46, false], ab: ["Naginata del guardián", "Resistencia heroica", "Mando de carceleros"], home: "impelDown" } },
  { name: "Sadi-chan", role: MO, powerLevel: 52, factionType: M, factionName: "Impel Down", rankLabel: "Jefa de guardianes", canonWeapon: "Látigo", description: "La jefa de guardianes de Impel Down, con un látigo y un gusto inquietante por el trabajo.", personality: "Sádica y entusiasta.", profile: { s: [54, 62, 52, 56, 50], h: [40, 40, false], ab: ["Látigo de castigo", "Bestias guardianas", "Tortura"], home: "impelDown" } },
  { name: "Domino", role: MO, powerLevel: 40, factionType: M, factionName: "Impel Down", rankLabel: "Jefa de guardia", description: "Guardia de élite de Impel Down: gafas oscuras, pocas palabras y cero tolerancia.", personality: "Seca y profesional.", profile: { s: [44, 48, 44, 50, 54], h: [30, 30, false], ab: ["Control de celdas", "Disciplina carcelaria"], home: "impelDown" } },

  // ---------- Cipher Pol (instructores de Tequila Wolf) ----------
  { name: "Guernica", role: ActorRole.CIPHER_POL, powerLevel: 78, factionType: C, factionName: "CP-0", rankLabel: "Agente de CP-0 (instructor)", description: "Agente de CP-0 con máscara y sombrero, experto en Rokushiki. Supervisa en persona a los reclutas de Tequila Wolf.", personality: "Frío, cortés y sin un solo gesto de más.", profile: { s: [74, 86, 72, 80, 80], h: [72, 76, false], ab: ["Rokushiki avanzado", "Rankyaku de ejecución", "Infiltración"], home: "tequilaWolf" } },
  { name: "Joseph", role: ActorRole.CIPHER_POL, powerLevel: 72, factionType: C, factionName: "CP-0", rankLabel: "Agente de CP-0", description: "Agente de CP-0 de trato distante que actúa como escolta de los Dragones Celestiales.", personality: "Callado y obediente.", profile: { s: [72, 78, 70, 74, 70], h: [66, 68, false], ab: ["Rokushiki", "Escolta de la Tierra Sagrada", "Tekkai"], home: "maryGeoise" } },
  { name: "Maha", role: ActorRole.CIPHER_POL, powerLevel: 70, factionType: C, factionName: "CP-0", rankLabel: "Agente de CP-0", description: "Agente de CP-0 que se encarga de las misiones que no pueden figurar en ningún informe.", personality: "Discreta y eficaz.", profile: { s: [68, 80, 66, 72, 76], h: [64, 70, false], ab: ["Rokushiki", "Operaciones encubiertas", "Soru"], home: "tequilaWolf", hidden: true } },
  { name: "Gismonda", role: ActorRole.CIPHER_POL, powerLevel: 66, factionType: C, factionName: "CP-0", rankLabel: "Agente de CP-0", description: "Agente de CP-0 veterano que evalúa a los reclutas de Tequila Wolf: si él no te aprueba, no subes.", personality: "Exigente y paciente, como un maestro que ha visto morir a muchos alumnos.", profile: { s: [66, 72, 66, 76, 80], h: [62, 66, false], ab: ["Rokushiki", "Evaluación de reclutas", "Interrogatorio"], home: "tequilaWolf" } },

  // ---------- East Blue ----------
  { name: "Gin", role: NP, powerLevel: 26, factionType: P, factionName: "Piratas de Don Krieg", rankLabel: "Comandante de Don Krieg", canonBounty: B(12_000_000), canonWeapon: "Tonfas", description: "El 'Demonio' de Don Krieg: leal hasta el final, con dos tonfas y una deuda de honor con un cocinero.", personality: "Leal, atormentado y peligroso cuando se lo propone.", profile: { s: [30, 32, 28, 34, 22], h: [0, 0, false], ab: ["Tonfas del demonio", "Bolas de pinchos", "Lealtad inquebrantable"], home: "baratie" } },
  { name: "Jango", role: NP, powerLevel: 18, factionType: P, factionName: "Piratas del Gato Negro", rankLabel: "Hipnotizador", canonBounty: B(9_000_000), canonWeapon: "Chakram de hipnosis", description: "El hipnotizador del Gato Negro: un péndulo, un paso de baile y demasiada confianza en sus trucos.", personality: "Excéntrico, bailarín y con más corazón del que parece.", profile: { s: [16, 24, 16, 22, 26], h: [0, 0, false], ab: ["Hipnosis de péndulo", "Moonwalk", "Uno, dos... ¡Jango!"], home: "syrup" } },
  { name: "Kaya", role: NC, powerLevel: 4, factionType: CIV, factionName: "Villa Syrup", rankLabel: "Heredera de la mansión", description: "La joven heredera de la mansión de Villa Syrup, que estudia medicina para curar a quien lo necesite.", personality: "Dulce, valiente y más fuerte de lo que aparenta.", profile: { s: [4, 6, 6, 18, 40], h: [0, 0, false], ab: ["Medicina", "Fortuna familiar"], home: "syrup" } },
  { name: "Makino", role: NC, powerLevel: 3, factionType: CIV, factionName: "Pueblo Foosha", rankLabel: "Tabernera", description: "La tabernera de Pueblo Foosha: sirvió leche a un niño que soñaba con ser Rey de los Piratas y aún guarda su silla.", personality: "Cálida y serena; escucha más de lo que habla.", profile: { s: [3, 5, 6, 20, 30], h: [0, 0, false], ab: ["Hospitalidad", "Oído para los rumores"], home: "foosha" } },
  { name: "Curly Dadan", role: NP, powerLevel: 16, factionType: P, factionName: "Bandidos de la Montaña", rankLabel: "Jefa de bandidos", description: "La jefa de bandidos que crió a tres chicos imposibles en el monte Corvo y aún finge que no los echa de menos.", personality: "Gruñona, ruidosa y con un corazón enorme escondido.", profile: { s: [24, 12, 26, 20, 14], h: [0, 0, false], ab: ["Bandidaje de montaña", "Cabezazo de jefa"], home: "foosha" } },
  { name: "Nojiko", role: NC, powerLevel: 5, factionType: CIV, factionName: "Isla Conomi", rankLabel: "Cultivadora de mandarinas", description: "La hermana de Nami: cuida el huerto de mandarinas de Bellemere en Villa Cocoyashi.", personality: "Serena y firme; no se deja intimidar.", profile: { s: [8, 8, 8, 20, 22], h: [0, 0, false], ab: ["Huerto de mandarinas", "Conoce todos los secretos de Conomi"], home: "conomi" } },

  // ---------- Paradise ----------
  { name: "Wyper", role: NC, powerLevel: 60, factionType: CIV, factionName: "Shandia", rankLabel: "Guerrero shandia", canonWeapon: "Bazuca de ardillas y Reject Dial", description: "El guerrero más feroz de los shandia: pelea por recuperar la tierra de sus ancestros con un Reject Dial que puede matarle a él también.", personality: "Feroz, orgulloso y dispuesto a todo por su pueblo.", profile: { s: [64, 66, 60, 78, 54], h: [40, 52, false], ab: ["Reject Dial", "Bazuca de Burn", "Tabla de nubes"], home: "skypiea" } },
  { name: "Gan Fall", role: NC, powerLevel: 44, factionType: CIV, factionName: "Skypiea", rankLabel: "Antiguo Dios de Skypiea", canonWeapon: "Lanza y montura Pierre", description: "El antiguo Dios de Skypiea: un caballero anciano que patrulla el cielo sobre su pájaro-caballo.", personality: "Noble, justo y protector.", profile: { s: [44, 46, 44, 60, 58], h: [0, 34, false], ab: ["Lanza del caballero", "Pierre (montura)", "Dials de combate"], home: "skypiea" } },
  { name: "Pell", role: NC, powerLevel: 46, factionType: CIV, factionName: "Reino de Alabasta", rankLabel: "Guardián real", description: "Guardián real de Alabasta: un halcón que vuela sobre el desierto protegiendo a su reina.", personality: "Leal y abnegado hasta el sacrificio.", profile: { s: [48, 58, 46, 58, 46], h: [0, 20, false], ab: ["Vuelo del halcón", "Guardia real", "Garra del desierto"], home: "alabasta" } },
  { name: "Mr. 5", role: NP, powerLevel: 30, factionType: P, factionName: "Baroque Works", rankLabel: "Agente de Baroque Works", devilFruitName: "Bomu Bomu no Mi", description: "Agente de Baroque Works que convierte cualquier parte de su cuerpo (y lo que escupe) en explosivos.", personality: "Frío, presumido y leal a su jefe.", profile: { s: [32, 26, 34, 30, 30], h: [0, 0, false], ab: ["Bomba nasal", "Cuerpo explosivo", "Estornudo explosivo"], home: "whiskyPeak" } },
  { name: "Miss Valentine", role: NP, powerLevel: 24, factionType: P, factionName: "Baroque Works", rankLabel: "Agente de Baroque Works", devilFruitName: "Kilo Kilo no Mi", description: "Compañera de Mr. 5: puede pesar un kilo o diez mil a voluntad, y caer del cielo con toda la carga.", personality: "Risueña y cruel.", profile: { s: [22, 32, 22, 24, 26], h: [0, 0, false], ab: ["Cambio de peso", "Caída de diez mil kilos", "Paraguas flotante"], home: "whiskyPeak" } },
  { name: "Doc Q", role: NP, powerLevel: 62, factionType: P, factionName: "Piratas de Barbanegra", rankLabel: "Médico de Barbanegra", canonBounty: B(1_000_000_000), description: "El médico enfermo de Barbanegra, que reparte manzanas de la muerte sobre un caballo tan débil como él.", personality: "Lúgubre y siniestro; tose más de lo que habla.", profile: { s: [52, 50, 48, 70, 72], h: [58, 62, false], ab: ["Manzanas de la muerte", "Enfermedades", "Stronger (montura)"], home: "banaro", hidden: true } },
  { name: "Hogback", role: NC, powerLevel: 24, factionType: CIV, factionName: "Thriller Bark", rankLabel: "Cirujano de Moria", description: "El famoso doctor que vendió su genio a Moria: cose zombis en Thriller Bark como quien firma autógrafos.", personality: "Vanidoso, cobarde y cruel.", profile: { s: [18, 20, 20, 26, 60], h: [0, 0, false], ab: ["Cirugía de zombis", "Bisturí traicionero"], home: "thrillerBark" } },

  // ---------- Revolucionarios ----------
  { name: "Terry Gilteo", role: ActorRole.REVOLUTIONARY_COMMANDER, powerLevel: 62, factionType: R, factionName: "Ejército Revolucionario", rankLabel: "Oficial revolucionario", description: "Oficial de la plana mayor de Dragon, famoso por su peinado desafiante y su puntería.", personality: "Excéntrico y leal.", profile: { s: [60, 64, 58, 66, 64], h: [48, 54, false], ab: ["Tiro de precisión", "Operaciones de célula", "Sabotaje"], home: "baltigo" } },

  // ---------- Nuevo Mundo ----------
  { name: "Hajrudin", role: NP, powerLevel: 72, factionType: P, factionName: "Gran Flota de Sombrero de Paja", rankLabel: "Capitán de los Nuevos Piratas Gigantes", canonBounty: B(1_000_000_000), description: "Un guerrero gigante de Elbaf que juró lealtad a Luffy tras el torneo de Dressrosa.", personality: "Orgulloso, honorable y leal.", profile: { s: [88, 50, 86, 76, 48], h: [66, 50, false], ab: ["Puño de gigante", "Honor de Elbaf", "Carga titánica"], home: "elbaf" } },
  { name: "Leo", role: NC, powerLevel: 38, factionType: CIV, factionName: "Gran Flota de Sombrero de Paja (Tontatta)", rankLabel: "Capitán Tontatta", description: "El capitán de los Tontatta: diminuto, rápido y con una aguja que cose lo que haga falta.", personality: "Valiente, ingenuo y muy leal.", profile: { s: [24, 70, 26, 60, 40], h: [30, 40, false], ab: ["Aguja de costura", "Velocidad Tontatta", "Remiendo imposible"], home: "dressrosa" } },
  { name: "Orlumbus", role: NP, powerLevel: 60, factionType: P, factionName: "Gran Flota de Sombrero de Paja", rankLabel: "Almirante de la flota Yonta Maria", canonBounty: B(148_000_000), description: "El aventurero de las mil victorias fallidas: capitán de una flota de 56 barcos que juró seguir a Luffy.", personality: "Grandilocuente, dramático y valiente.", profile: { s: [72, 48, 70, 70, 50], h: [50, 40, false], ab: ["Cañonazo de brazo", "Flota Yonta Maria", "Coraje del explorador"], home: "dressrosa" } },
];

/** Canon moves: where these characters really are now (applied once; later reseeds never move anyone). */
export const WAVE4_RELOCATIONS: Record<string, string> = {
  Sakazuki: "nuevoMarineford",
  "Aokiji (Kuzan)": "hachinosu",
  "Emporio Ivankov": "kamabakka",
};
