/**
 * Third wave of the canon cast (2026-09-24): the rest of the Gorosei and the Celestial Dragons, the
 * Marine officers, the crews of the Yonko, and the people every island of the Grand Line is known for.
 * Same shape and rules as world-actor-extra.ts (bounties are canon figures, null = none known; devil
 * fruits only when the catalog has them and nobody else holds them). Kaido and Big Mom are NOT here:
 * they are active again in world-actor-extra.ts (the owner wants them alive and waiting).
 */
import { ActorRole, FactionType } from "@prisma/client";
import type { ExtraActor } from "./world-actor-extra";

const B = (n: number) => BigInt(n);
const P = FactionType.PIRATE;
const M = FactionType.MARINE;
const R = FactionType.REVOLUTIONARY;
const CIV = FactionType.CIVILIAN;
const C = FactionType.CIPHER_POL;
const NP = ActorRole.NOTABLE_PIRATE;
const MO = ActorRole.MARINE_OFFICER;
const NC = ActorRole.NOTABLE_CIVILIAN;
const GO = ActorRole.GOROSEI;

export const MORE_ACTORS: ExtraActor[] = [
  // ---------- Gorosei (los Cinco Ancianos) ----------
  { name: "Topman Warcury", role: GO, powerLevel: 96, factionType: C, factionName: "Gorosei", rankLabel: "Anciano — Guardián de la Justicia", canonWeapon: "Espada de ceremonia", description: "El Anciano que firma las condenas: nada llega a la Marina sin pasar por su tinta.", personality: "Frío y burocrático; habla de ejecuciones como de trámites.", profile: { s: [90, 82, 92, 94, 96], h: [88, 90, false], ab: ["Forma monstruosa de la Tierra Sagrada", "Sentencia de los Ancianos", "Autoridad sobre almirantes"], home: "maryGeoise" } },
  { name: "Marcus Mars", role: GO, powerLevel: 96, factionType: C, factionName: "Gorosei", rankLabel: "Anciano — Guardián del Medio Ambiente", description: "El Anciano que decide qué cambios tolera el mundo y cuáles se borran.", personality: "Sereno y cruel; sonríe cuando alguien cree tener una salida.", profile: { s: [88, 80, 92, 94, 96], h: [86, 92, false], ab: ["Forma monstruosa de la Tierra Sagrada", "Control de la información", "Mano de hierro sobre los reinos"], home: "maryGeoise" } },
  { name: "Ethanbaron V. Nusjuro", role: GO, powerLevel: 97, factionType: C, factionName: "Gorosei", rankLabel: "Anciano — Guardián de la Legislación", canonWeapon: "Ame no Habakiri", description: "El espadachín de los Ancianos: escribe las leyes y las defiende con una hoja que casi nadie ha visto desenvainar.", personality: "Orgulloso y sereno; desprecia lo que no entiende.", profile: { s: [92, 90, 90, 94, 90], h: [94, 92, false], ab: ["Ame no Habakiri", "Corte de la ley", "Forma monstruosa de la Tierra Sagrada"], home: "maryGeoise" } },
  { name: "Shepherd Ju Peter", role: GO, powerLevel: 95, factionType: C, factionName: "Gorosei", rankLabel: "Anciano — Guardián de la Agricultura", description: "El Anciano que reparte la comida del mundo y, con ella, la obediencia.", personality: "Amable en la superficie, implacable en el fondo.", profile: { s: [86, 78, 90, 92, 94], h: [84, 88, false], ab: ["Forma monstruosa de la Tierra Sagrada", "Manejo de recursos del mundo", "Orden directa a Cipher Pol"], home: "maryGeoise" } },

  // ---------- Dragones Celestiales y Caballeros Sagrados ----------
  { name: "Figarland Garling", role: NC, powerLevel: 92, factionType: CIV, factionName: "Caballeros Sagrados", rankLabel: "Comandante de los Caballeros Sagrados", canonWeapon: "Espada sagrada", description: "El guerrero más temido de la Tierra Sagrada: hombre de la Casa de los Dragones Celestiales que lidera a los Caballeros Sagrados.", personality: "Callado y devoto: solo obedece a los Ancianos.", profile: { s: [92, 90, 90, 92, 82], h: [94, 92, true], ab: ["Espada sagrada", "Guardia de la Tierra Sagrada", "Haki del Rey"], home: "maryGeoise" } },
  { name: "Saint Charlos", role: NC, powerLevel: 12, factionType: CIV, factionName: "Dragones Celestiales", rankLabel: "Dragón Celestial", description: "Un noble de la Tierra Sagrada que cree que el mundo entero es suyo y nada de lo que hay en él tiene derecho a quejarse.", personality: "Caprichoso y cruel; su mayor arma es la palabra 'Almirante'.", profile: { s: [12, 10, 12, 14, 30], h: [0, 0, false], ab: ["Escolta de la Marina", "Poder político absoluto", "Esclavos personales"], home: "maryGeoise" } },
  { name: "Saint Rosward", role: NC, powerLevel: 12, factionType: CIV, factionName: "Dragones Celestiales", rankLabel: "Dragón Celestial", description: "Un Dragón Celestial que viaja a Marineford, Sabaody o donde le apetezca con toda una flota alrededor.", personality: "Altivo, aburrido y peligroso por capricho.", profile: { s: [12, 10, 12, 14, 30], h: [0, 0, false], ab: ["Escolta de la Marina", "Poder político absoluto"], home: "maryGeoise" } },

  // ---------- Marina ----------
  { name: "Onigumo", role: MO, powerLevel: 74, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante", canonWeapon: "Chakram con cadena", description: "Vicealmirante duro con los piratas y más duro aún con sus propios reclutas.", personality: "Rígido y frío: la disciplina es su religión.", profile: { s: [76, 72, 74, 78, 70], h: [72, 66, false], ab: ["Chakram con cadena", "Mando de flota", "Asalto disciplinado"], home: "marineford" } },
  { name: "Ronse", role: MO, powerLevel: 72, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante", canonWeapon: "Pistola y sable", description: "Vicealmirante de campo: llega tarde a las conferencias pero no a las batallas.", personality: "Impulsivo y leal.", profile: { s: [74, 72, 72, 74, 68], h: [70, 64, false], ab: ["Mando de escuadra", "Tiro y sable", "Persecución marítima"], home: "marineford" } },
  { name: "Lacroix", role: MO, powerLevel: 72, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante", description: "Vicealmirante de mirada fría que analiza todo antes de disparar.", personality: "Cauto y meticuloso.", profile: { s: [72, 74, 72, 74, 78], h: [70, 70, false], ab: ["Mando táctico", "Tirador de precisión", "Persecución marítima"], home: "marineford" } },
  { name: "Maynard", role: MO, powerLevel: 70, factionType: M, factionName: "Marina", rankLabel: "Vicealmirante", description: "Vicealmirante veterano, hombre de mar y de rutina.", personality: "Paciente; no se deja provocar.", profile: { s: [72, 68, 74, 76, 68], h: [68, 62, false], ab: ["Mando de flota", "Abordaje", "Artillería naval"], home: "loguetown" } },

  // ---------- Big Mom ----------
  { name: "Charlotte Oven", role: NP, powerLevel: 82, factionType: P, factionName: "Piratas de Big Mom", rankLabel: "Comandante Dulce (Ministro del Horno)", canonBounty: B(500_000_000), canonWeapon: "Sable de fuego", description: "Comandante de los Big Mom: un torbellino de fuego con voz de trueno.", personality: "Temperamental y feroz.", profile: { s: [86, 80, 84, 82, 68], h: [78, 70, false], ab: ["Sable ardiente", "Llamaradas", "Furia del horno"], home: "wholeCake" } },
  { name: "Charlotte Daifuku", role: NP, powerLevel: 82, factionType: P, factionName: "Piratas de Big Mom", rankLabel: "Comandante Dulce (Ministro del Mochi)", canonBounty: B(820_000_000), description: "Comandante Dulce de los Big Mom: gigante y cruel, siempre acompañado de sus cañones.", personality: "Cruel y goloso.", profile: { s: [88, 66, 92, 82, 62], h: [76, 68, false], ab: ["Cañones incorporados", "Aplastamiento", "Guardia de la reina"], home: "wholeCake" } },
  { name: "Charlotte Pudding", role: NP, powerLevel: 46, factionType: P, factionName: "Piratas de Big Mom", rankLabel: "Hija de Big Mom", description: "Hija de Big Mom con un tercer ojo y memoria capaz de moldear recuerdos.", personality: "Calculadora y muy convincente.", profile: { s: [34, 48, 36, 62, 92], h: [30, 62, false], ab: ["Tercer ojo (lectura de memoria)", "Manipulación de recuerdos", "Engaños elaborados"], home: "wholeCake" } },

  // ---------- Barbanegra ----------
  { name: "Catarina Devon", role: NP, powerLevel: 74, factionType: P, factionName: "Piratas de Barbanegra", rankLabel: "Capitana del barco de la Luna Llena", canonBounty: B(2_500_000_000), description: "Capitana de Barbanegra, especialista en disfrazarse de su víctima hasta que ya es demasiado tarde.", personality: "Astuta y cruel.", profile: { s: [72, 78, 70, 78, 76], h: [66, 68, false], ab: ["Imitación de rostro", "Emboscada", "Engaño"], home: "graveyardIsland" } },
  { name: "Sanjuan Wolf", role: NP, powerLevel: 76, factionType: P, factionName: "Piratas de Barbanegra", rankLabel: "Capitán del barco de la Sirena", canonBounty: B(1_500_000_000), description: "Un gigante entre los Piratas de Barbanegra: mano derecha con puños del tamaño de un barco.", personality: "Sanguinario y sencillo.", profile: { s: [92, 56, 92, 76, 50], h: [74, 60, false], ab: ["Puños gigantes", "Aplastamiento", "Furia de gigante"], home: "graveyardIsland" } },
  { name: "Vasco Shot", role: NP, powerLevel: 74, factionType: P, factionName: "Piratas de Barbanegra", rankLabel: "Capitán del barco del Jugador", canonBounty: B(1_000_000_000), description: "Un borracho que pelea como si el mundo fuera un barril: dos pistolas y demasiado ron.", personality: "Grosero, ruidoso y letal.", profile: { s: [76, 72, 74, 72, 52], h: [70, 58, false], ab: ["Puñetazos borrachos", "Pistolas", "Aguante temerario"], home: "graveyardIsland" } },
  { name: "Stronger", role: NP, powerLevel: 60, factionType: P, factionName: "Piratas de Barbanegra", rankLabel: "Tripulante de Barbanegra", canonBounty: B(400_000_000), description: "Un montón de músculos a las órdenes de Barbanegra.", personality: "Bruto y leal.", profile: { s: [80, 56, 82, 68, 44], h: [60, 44, false], ab: ["Fuerza bruta", "Aguante"], home: "graveyardIsland" } },

  // ---------- Kaido ----------
  { name: "Page One", role: NP, powerLevel: 82, factionType: P, factionName: "Piratas de las Bestias", rankLabel: "Tobiroppo", canonBounty: B(1_000_000_000), description: "El Tobiroppo más joven: un dinosaurio en cuerpo de niño que sueña con ser como su capitán.", personality: "Ambicioso, orgulloso y desafiante.", profile: { s: [86, 76, 84, 82, 60], h: [74, 66, false], ab: ["Aplastamiento de dinosaurio", "Furia de un bruto", "Golpe titánico"], home: "wano" } },
  { name: "Black Maria", role: NP, powerLevel: 80, factionType: P, factionName: "Piratas de las Bestias", rankLabel: "Calamidad — La Plaga", canonBounty: B(1_000_000_000), description: "Una araña gigante de Kaido con voz seductora y hilos que arrancan cuerpos enteros.", personality: "Seductora, cruel y vanidosa.", profile: { s: [80, 76, 78, 76, 70], h: [70, 66, false], ab: ["Hilos de araña", "Seducción envenenada", "Veneno paralizante"], home: "wano" } },
  { name: "Sasaki", role: NP, powerLevel: 78, factionType: P, factionName: "Piratas de las Bestias", rankLabel: "Tobiroppo", canonBounty: B(1_000_000_000), description: "El Tobiroppo blindado: un triceratops de acero con obediencia total a su capitán.", personality: "Disciplinado y bruto.", profile: { s: [84, 66, 90, 78, 52], h: [72, 60, false], ab: ["Embestida de triceratops", "Coraza de acero", "Lealtad ciega"], home: "wano" } },

  // ---------- Corazón / Kid ----------
  { name: "Penguin", role: NP, powerLevel: 54, factionType: P, factionName: "Piratas Heart", rankLabel: "Tripulante de Law", description: "Uno de los primeros tripulantes de Law: mecánico y luchador de mucha fe en su capitán.", personality: "Leal, ruidoso y con gorra siempre puesta.", profile: { s: [56, 58, 56, 66, 60], h: [40, 40, false], ab: ["Mecánico del submarino", "Combate cuerpo a cuerpo", "Lealtad total a Law"], home: "punkHazard" } },
  { name: "Shachi", role: NP, powerLevel: 54, factionType: P, factionName: "Piratas Heart", rankLabel: "Tripulante de Law", description: "El otro pilar de los Heart: bromas y garras al servicio de su capitán.", personality: "Bromista y leal.", profile: { s: [56, 60, 54, 66, 58], h: [40, 40, false], ab: ["Combate a garras", "Navegación submarina", "Lealtad total a Law"], home: "punkHazard" } },

  // ---------- Isla Drum, Alabasta, Jaya y las islas de la primera mitad ----------
  { name: "Dr. Kureha", role: NC, powerLevel: 54, factionType: CIV, factionName: "Reino de Drum", rankLabel: "Doctora (la Bruja)", description: "La doctora legendaria de Drum: rostro de bruja, manos de cirujana y una receta contra casi todo.", personality: "Ácida y risueña; cura a golpes si hace falta.", profile: { s: [40, 40, 42, 84, 92], h: [30, 48, false], ab: ["Medicina de Drum", "Elixires", "Golpes de doctora enfadada"], home: "drum" } },
  { name: "Dalton", role: NC, powerLevel: 60, factionType: CIV, factionName: "Reino de Drum", rankLabel: "Capitán de la guardia", description: "El guerrero que defendió Drum cuando el reino se hundía.", personality: "Sereno y honorable.", profile: { s: [76, 62, 78, 82, 58], h: [50, 40, false], ab: ["Transformación en bestia", "Guardia del reino", "Voluntad de hierro"], home: "drum" } },
  { name: "Nefertari Cobra", role: NC, powerLevel: 40, factionType: CIV, factionName: "Reino de Alabasta", rankLabel: "Rey de Alabasta", description: "El rey de Alabasta: un hombre sereno que sostiene un reino sobre arena y palabra.", personality: "Sabio y paciente.", profile: { s: [40, 40, 44, 82, 88], h: [20, 40, false], ab: ["Diplomacia", "Conocimiento del Poneglifo del reino", "Mando del ejército de Alabasta"], home: "alabasta" } },
  { name: "Kohza", role: NC, powerLevel: 46, factionType: CIV, factionName: "Reino de Alabasta", rankLabel: "Líder rebelde de Alabasta", canonWeapon: "Cimitarra", description: "El joven líder de la rebelión de Alabasta, ahora aliado del reino.", personality: "Ardiente y sincero.", profile: { s: [56, 58, 54, 72, 56], h: [30, 34, false], ab: ["Cimitarra", "Liderazgo rebelde", "Combate en el desierto"], home: "alabasta" } },
  { name: "Montblanc Cricket", role: NC, powerLevel: 52, factionType: CIV, factionName: "Jaya", rankLabel: "Buscador de oro", canonWeapon: "Ballesta", description: "El buscador de oro de Jaya, hombre de risa fuerte que cree que la Ciudad de Oro existió.", personality: "Testarudo y honrado.", profile: { s: [60, 60, 58, 74, 60], h: [30, 40, false], ab: ["Ballesta", "Trampas de la selva", "Ojo de cartógrafo"], home: "jaya" } },
  { name: "Foxy", role: NP, powerLevel: 48, factionType: P, factionName: "Piratas del Zorro Plateado", rankLabel: "Capitán", canonBounty: B(24_000_000), devilFruitName: "Noro Noro no Mi", description: "Capitán fanfarrón de Long Ring Long Land: sus duelos de tramposo son el orgullo de la isla.", personality: "Presumido y tramposo, pero con su código.", profile: { s: [44, 42, 44, 56, 54], h: [16, 16, false], phase: "initial", ab: ["Rayo lento", "Duelos de trampa", "Bravuconería"], home: "longRing" } },
  { name: "Perona", role: NP, powerLevel: 60, factionType: P, factionName: "Piratas de Moria", rankLabel: "Princesa Fantasma", canonBounty: B(60_000_000), devilFruitName: "Horo Horo no Mi", description: "La Princesa Fantasma: envía espectros que quitan todo el ánimo a quien toquen.", personality: "Caprichosa, dramática y con un lado inesperadamente valiente.", profile: { s: [34, 52, 34, 66, 74], h: [10, 34, false], phase: "advanced", ab: ["Hollow Hollow", "Espectros negativos", "Muñecos"], home: "kuraigana" } },
  { name: "Absalom", role: NP, powerLevel: 60, factionType: P, factionName: "Piratas de Moria", rankLabel: "Lugarteniente de Moria", canonBounty: B(150_000_000), description: "El lugarteniente invisible de Moria: sus modales son los de quien no cree que nadie le mire.", personality: "Lascivo, arrogante y cobarde.", profile: { s: [70, 62, 68, 60, 40], h: [40, 34, false], ab: ["Invisibilidad", "Fuerza bruta", "Acecho"], home: "thrillerBark" } },

  // ---------- Water 7, Baratie, Conomi ----------
  { name: "Iceburg", role: NC, powerLevel: 46, factionType: CIV, factionName: "Galley-La Company", rankLabel: "Alcalde de Water 7", description: "El alcalde de Water 7 y maestro carpintero, que ve a los barcos como personas.", personality: "Sereno y astuto; siempre ve tres jugadas por delante.", profile: { s: [44, 44, 48, 74, 92], h: [16, 40, false], ab: ["Maestría de astillero", "Diplomacia de ciudad", "Negociación"], home: "waterSeven" } },
  { name: "Paulie", role: NC, powerLevel: 44, factionType: CIV, factionName: "Galley-La Company", rankLabel: "Carpintero de Galley-La", canonWeapon: "Cuerdas de acero", description: "Carpintero de Galley-La, viejo amigo de los astilleros y de los pequeños milagros.", personality: "Rudo y sentimental.", profile: { s: [56, 58, 52, 68, 48], h: [8, 16, false], ab: ["Combate con cuerdas", "Carpintería", "Guardia de astillero"], home: "waterSeven" } },
  { name: "Red-Leg Zeff", role: NP, powerLevel: 58, factionType: P, factionName: "Restaurante Baratie", rankLabel: "Cocinero jefe", canonWeapon: "Pierna de madera", description: "El cocinero jefe del Baratie: antiguo pirata que juró que nadie pasaría hambre en su restaurante.", personality: "Rudo, sarcástico y muy paternal.", profile: { s: [62, 62, 58, 80, 60], h: [46, 42, false], ab: ["Patadas de cocinero", "Cocina del mar", "Pierna de madera"], home: "baratie" } },
  { name: "Genzo", role: NC, powerLevel: 36, factionType: CIV, factionName: "Villa Cocoyasi", rankLabel: "Antiguo policía de Cocoyasi", description: "El policía de Cocoyasi que enfrentó a Arlong sin miedo.", personality: "Fiero y protector.", profile: { s: [42, 40, 40, 70, 42], h: [10, 20, false], ab: ["Puños de veterano", "Voluntad de aldeano"], home: "conomi" } },
  { name: "Bellemere", role: NC, powerLevel: 30, factionType: M, factionName: "Marina (antigua)", rankLabel: "Marine retirada", status: "DECEASED", description: "La marine que adoptó a Nami y a Nojiko. Su memoria sigue siendo la razón de muchas cosas.", personality: "Dura y cariñosa a partes iguales.", profile: { s: [40, 44, 40, 70, 46], h: [10, 20, false], ab: ["Combate marine"], home: "conomi" } },

  // ---------- Amazon Lily, Ohara, Isla Gyojin ----------
  { name: "Boa Sandersonia", role: NP, powerLevel: 62, factionType: P, factionName: "Piratas Kuja", rankLabel: "Guerrera Kuja", description: "Hermana de Hancock, guerrera Kuja de puntería mortal.", personality: "Orgullosa y leal a su hermana.", profile: { s: [64, 72, 60, 72, 58], h: [50, 46, false], ab: ["Combate Kuja", "Serpientes", "Lealtad a Hancock"], home: "amazonLily" } },
  { name: "Boa Marigold", role: NP, powerLevel: 62, factionType: P, factionName: "Piratas Kuja", rankLabel: "Guerrera Kuja", description: "Hermana de Hancock: guerrera Kuja de mirada dura.", personality: "Reservada y firme.", profile: { s: [62, 72, 60, 72, 60], h: [50, 46, false], ab: ["Combate Kuja", "Guardia de Amazon Lily"], home: "amazonLily" } },
  { name: "Nico Olvia", role: NC, powerLevel: 40, factionType: CIV, factionName: "Ohara", rankLabel: "Arqueóloga de Ohara", status: "DECEASED", description: "La arqueóloga que protegió a su hija y a un mundo entero de un secreto que el Gobierno no perdonaba.", personality: "Serena y decidida.", profile: { s: [30, 40, 34, 90, 96], h: [10, 30, false], ab: ["Lectura de Poneglifos", "Arqueología prohibida"], home: "ohara" } },
  { name: "Neptune", role: NC, powerLevel: 74, factionType: CIV, factionName: "Reino Ryugu", rankLabel: "Rey del Reino Ryugu", canonWeapon: "Tridente", description: "El rey del Reino Ryugu: un tritón inmenso que gobierna con el pueblo del mar.", personality: "Cálido y firme.", profile: { s: [78, 66, 82, 88, 74], h: [56, 60, false], ab: ["Tridente", "Mando del reino", "Comunicación con reyes marinos"], home: "fishMan" } },
  { name: "Vander Decken IX", role: NP, powerLevel: 66, factionType: P, factionName: "Nuevos Piratas Hombre-Pez", rankLabel: "Capitán", canonBounty: B(300_000_000), description: "Capitán de un barco fantasma, obsesionado con la sirena que perdió.", personality: "Vanidoso, dramático e implacable.", profile: { s: [64, 62, 66, 66, 60], h: [50, 44, false], ab: ["Ataques de escudero y nave", "Barco fantasma", "Rabia romántica"], home: "fishMan" } },
  { name: "Hatchan", role: NP, powerLevel: 46, factionType: P, factionName: "Piratas de Arlong", rankLabel: "Cocinero pulpo", description: "El pulpo de seis brazos que hoy hace takoyaki y arrepentimientos.", personality: "Buenazo y torpe.", profile: { s: [56, 52, 56, 64, 48], h: [8, 20, false], ab: ["Seis espadas", "Cocina de pulpo"], home: "fishMan" } },

  // ---------- Dressrosa ----------
  { name: "Rebecca", role: NC, powerLevel: 46, factionType: CIV, factionName: "Reino de Dressrosa", rankLabel: "Gladiadora y princesa", canonWeapon: "Espada de gladiadora", description: "Gladiadora del coliseo y princesa de un reino que casi se olvidó de sí mismo.", personality: "Testaruda y noble.", profile: { s: [52, 56, 52, 70, 54], h: [16, 30, false], ab: ["Esgrima de coliseo", "Gladiadora", "Carisma de campeona"], home: "dressrosa" } },
  { name: "Kyros", role: NC, powerLevel: 68, factionType: CIV, factionName: "Reino de Dressrosa", rankLabel: "Campeón del coliseo", canonWeapon: "Espada de un solo tajo", description: "El soldado de un solo tajo: campeón legendario del coliseo de Dressrosa.", personality: "Sereno y honorable.", profile: { s: [76, 76, 72, 88, 66], h: [70, 66, false], ab: ["Espada de un tajo", "Haki avanzado", "Campeón del coliseo"], home: "dressrosa" } },
  { name: "Viola", role: NC, powerLevel: 54, factionType: CIV, factionName: "Reino de Dressrosa", rankLabel: "Gladiadora — La Vidente", description: "Capaz de leer las intenciones de quienes la rodean: la carta que nunca se ve venir en el coliseo.", personality: "Discreta y astuta.", profile: { s: [42, 60, 44, 72, 88], h: [24, 66, false], ab: ["Visión del futuro cercano", "Espada corta", "Lectura de intenciones"], home: "dressrosa" } },
  { name: "Pica", role: NP, powerLevel: 70, factionType: P, factionName: "Familia Donquixote", rankLabel: "As de picas", canonBounty: B(99_000_000), description: "Un coloso de voz aguda que se funde con la piedra: aplasta al rival como si lo tallara.", personality: "Frío y calculador.", profile: { s: [80, 60, 84, 78, 60], h: [64, 56, false], ab: ["Fusión con la piedra", "Titán de roca", "Aplastamiento"], home: "dressrosa" } },
  { name: "Señor Pink", role: NP, powerLevel: 46, factionType: P, factionName: "Familia Donquixote", rankLabel: "Ejecutivo", description: "Un caballero de mameluco rosa que pelea con tanta fe en sí mismo como en el amor.", personality: "Excéntrico y sorprendentemente peligroso.", profile: { s: [58, 56, 54, 66, 48], h: [30, 24, false], ab: ["Combate acrobático", "Bravura absurda"], home: "dressrosa" } },

  // ---------- Wano, Zou, Elbaf, otros ----------
  { name: "Denjiro", role: NP, powerLevel: 72, factionType: P, factionName: "Nueva Era de Wano", rankLabel: "Samurái de Wano (Kyoshiro)", canonWeapon: "Katana", description: "Uno de los Guardianes Rojos de Oden, disfrazado durante años entre los lobos de Wano.", personality: "Sereno y leal a Oden.", profile: { s: [74, 72, 72, 82, 72], h: [72, 70, false], ab: ["Esgrima de samurái", "Disfraz de bandido", "Lealtad a Oden"], home: "wano" } },
  { name: "Hyogoro", role: NP, powerLevel: 68, factionType: P, factionName: "Nueva Era de Wano", rankLabel: "Jefe de los Yakuza de Wano", canonWeapon: "Katana", description: "El jefe yakuza de la Capital de las Flores: un protector de los pobres con espada.", personality: "Amable, digno y firme.", profile: { s: [72, 66, 74, 82, 68], h: [64, 58, false], ab: ["Esgrima yakuza", "Mando de bajos fondos", "Aguante"], home: "wano" } },
  { name: "Dorry", role: NP, powerLevel: 88, factionType: P, factionName: "Guerreros de Elbaf", rankLabel: "Gigante de Elbaf", canonBounty: B(100_000_000), canonWeapon: "Hacha gigante", description: "Gigante de Elbaf, uno de los dos guerreros más famosos: hace décadas que pelea contra su hermano por un honor absurdo.", personality: "Honorable y terco.", profile: { s: [96, 50, 94, 90, 56], h: [80, 62, false], ab: ["Hacha gigante", "Fuerza de gigante", "Fuerza de voluntad"], home: "elbaf" } },
  { name: "Brogy", role: NP, powerLevel: 88, factionType: P, factionName: "Guerreros de Elbaf", rankLabel: "Gigante de Elbaf", canonBounty: B(100_000_000), canonWeapon: "Espada gigante", description: "El otro gigante legendario: rival y hermano de sangre de Dorry, lucha por un honor que ya nadie recuerda.", personality: "Sereno y orgulloso.", profile: { s: [96, 50, 94, 90, 56], h: [80, 62, false], ab: ["Espada gigante", "Fuerza de gigante", "Fuerza de voluntad"], home: "elbaf" } },

  // ---------- Revolucionarios, Germa y otros ----------
  { name: "Inazuma", role: ActorRole.REVOLUTIONARY_COMMANDER, powerLevel: 66, factionType: R, factionName: "Ejército Revolucionario", rankLabel: "Comandante — Mano izquierda de Ivankov", description: "El apoyo de Ivankov en Baltigo: una lengua de hierro y unas tijeras que cortan destinos.", personality: "Optimista y algo trágico.", profile: { s: [56, 66, 56, 82, 84], h: [46, 46, false], ab: ["Tijeras de hierro", "Reconocimiento y apoyo"], home: "baltigo" } },
  { name: "Vinsmoke Ichiji", role: NP, powerLevel: 74, factionType: P, factionName: "Germa 66", rankLabel: "Hijo mayor de Judge", canonBounty: B(0), description: "El hijo mayor de Vinsmoke Judge: soldado de élite con una armadura de electricidad.", personality: "Frío y arrogante.", profile: { s: [76, 76, 76, 78, 64], h: [60, 56, false], ab: ["Armadura eléctrica", "Combate con pinchos", "Disciplina de Germa"], home: "whiskyPeak" } },
  { name: "Vinsmoke Niji", role: NP, powerLevel: 74, factionType: P, factionName: "Germa 66", rankLabel: "Hijo de Judge", canonBounty: B(0), description: "Hijo de Judge, soldado de Germa con armadura de fuego y un ego del tamaño de la torre.", personality: "Arrogante y competitivo.", profile: { s: [76, 76, 74, 76, 62], h: [58, 56, false], ab: ["Armadura de fuego", "Disciplina de Germa"], home: "whiskyPeak" } },
  { name: "Vinsmoke Yonji", role: NP, powerLevel: 74, factionType: P, factionName: "Germa 66", rankLabel: "Hijo de Judge", canonBounty: B(0), description: "El pequeño de los hermanos Vinsmoke: piernas de hielo y un buen fondo ausente.", personality: "Presumido y ruidoso.", profile: { s: [74, 78, 72, 76, 60], h: [56, 56, false], ab: ["Armadura de hielo", "Patadas de germa"], home: "whiskyPeak" } },
];

/** Where each of these people, and a few earlier characters, really belong (the seed moves them once, on reseed). */
export const RELOCATIONS: Record<string, string> = {
  "Boa Hancock": "amazonLily",
  "Dracule Mihawk": "kuraigana",
  "Gecko Moria": "thrillerBark",
  "Kozuki Momonosuke": "wano",
};
