// Second wave of filler residents: asks the AI for 8-10 more per island (with real lore), resumable, writes island-npc-data-wave2.ts.
// Usage: npx tsx scripts/gen-island-rosters-wave2.ts [onlyIslandName]   (dev DB seeded + OPENROUTER_API_KEY)
import "dotenv/config";
import fs from "fs";
import path from "path";
import { prisma } from "../src/lib/db";
import { generateMoreResidents } from "../src/lib/ai/island-npc";
import type { SeedRosterEntry } from "../src/lib/game/island-npcs";

const OUT = path.resolve(process.cwd(), "src/lib/game/island-npc-data-wave2.ts");
const PARALLEL = 4;

function load(): SeedRosterEntry[] {
  if (!fs.existsSync(OUT)) return [];
  const m = fs.readFileSync(OUT, "utf8").match(/ISLAND_NPC_DATA_WAVE2: SeedRosterEntry\[\] = (\[[\s\S]*\]);\s*$/);
  return m ? (JSON.parse(m[1]) as SeedRosterEntry[]) : [];
}
function save(rows: SeedRosterEntry[]) {
  fs.writeFileSync(OUT, `// Second wave of island residents, generated by scripts/gen-island-rosters-wave2.ts (AI-written lore, edit freely). The seed upserts by name and never revives the dead.\nimport type { SeedRosterEntry } from "./island-npcs";\n\nexport const ISLAND_NPC_DATA_WAVE2: SeedRosterEntry[] = ${JSON.stringify(rows, null, 1)};\n`);
}

async function main() {
  const only = process.argv[2];
  const islands = await prisma.island.findMany({ where: only ? { name: only } : {}, orderBy: { name: "asc" } });
  const rows = load().filter((r) => !only || r.island !== only);
  const done = new Set(rows.map((r) => r.island));
  const residents = await prisma.islandNpc.findMany({ select: { name: true, title: true, islandId: true } });
  const forbidden = new Set<string>([...(await prisma.worldActor.findMany({ select: { name: true } })).map((a) => a.name), ...residents.map((r) => r.name), ...rows.map((r) => r.name)]);
  const queue = islands.filter((i) => only || !done.has(i.name));
  console.log(`${queue.length} islands to do (${done.size} already done)`);
  let idx = 0;
  const worker = async () => {
    while (idx < queue.length) {
      const isl = queue[idx++];
      const existing = residents.filter((r) => r.islandId === isl.id).map((r) => ({ name: r.name, title: r.title }));
      let got = null;
      for (let attempt = 0; attempt < 3 && !got; attempt++) got = await generateMoreResidents({ name: isl.name, description: isl.description, arcHook: isl.arcHook, danger: isl.dangerLevel, control: isl.factionControl, existing, forbidden: [...forbidden] });
      if (!got) {
        console.log(`FAILED ${isl.name}`);
        continue;
      }
      const entries: SeedRosterEntry[] = got.map((n) => ({ island: isl.name, slot: n.slot, name: n.name, title: n.title, category: n.category, level: n.level, description: n.description, personality: n.personality, weapon: n.weapon, abilities: n.abilities }));
      for (const e of entries) forbidden.add(e.name);
      rows.push(...entries);
      save(rows);
      console.log(`OK ${isl.name}: ${entries.length}`);
    }
  };
  await Promise.all(Array.from({ length: PARALLEL }, worker));
  console.log(`done: ${rows.length} new residents`);
}
main().finally(() => prisma.$disconnect());
