// Regenerable: asks the AI for the fixed gazetteer of every island (places, history, customs, rumours, who is where)
// and writes src/lib/game/island-lore-data.ts. Usage: npx tsx scripts/gen-island-lore.ts [onlyIslandName]
import "dotenv/config";
import fs from "fs";
import path from "path";
import { prisma } from "../src/lib/db";
import { generateIslandLore } from "../src/lib/ai/island-npc";
import type { IslandLore } from "../src/lib/engine/island-lore";

const OUT = path.resolve(process.cwd(), "src/lib/game/island-lore-data.ts");
const PARALLEL = 5;

function loadExisting(): IslandLore[] {
  if (!fs.existsSync(OUT)) return [];
  const m = fs.readFileSync(OUT, "utf8").match(/ISLAND_LORE_DATA: IslandLore\[\] = (\[[\s\S]*\]);\s*$/);
  return m ? (JSON.parse(m[1]) as IslandLore[]) : [];
}

function save(rows: IslandLore[]) {
  rows.sort((a, b) => a.island.localeCompare(b.island));
  fs.writeFileSync(OUT, `// Generated by scripts/gen-island-lore.ts from each island's lore and residents; edit freely.\nimport type { IslandLore } from "../engine/island-lore";\n\nexport const ISLAND_LORE_DATA: IslandLore[] = ${JSON.stringify(rows, null, 1)};\n`);
}

async function main() {
  const only = process.argv[2];
  const islands = await prisma.island.findMany({ where: only ? { name: only } : {}, orderBy: { name: "asc" } });
  const rows = loadExisting().filter((r) => !only || r.island !== only);
  const done = new Set(rows.map((r) => r.island));
  const queue = islands.filter((i) => only || !done.has(i.name));
  console.log(`${queue.length} islands to write (${done.size} already done)`);
  let idx = 0;
  const worker = async () => {
    while (idx < queue.length) {
      const isl = queue[idx++];
      const residents = await prisma.islandNpc.findMany({ where: { islandId: isl.id, status: { not: "DEAD" } }, select: { name: true, title: true } });
      let got: IslandLore | null = null;
      for (let attempt = 0; attempt < 3 && !got; attempt++) {
        got = await generateIslandLore({ name: isl.name, description: isl.description, arcHook: isl.arcHook, danger: isl.dangerLevel, control: isl.factionControl, residents });
      }
      if (!got) {
        console.log(`FAILED ${isl.name}`);
        continue;
      }
      rows.push(got);
      save(rows);
      console.log(`OK ${isl.name}: ${got.places.map((p) => p.name).join(", ")}`);
    }
  };
  await Promise.all(Array.from({ length: PARALLEL }, worker));
  console.log(`done: ${rows.length} islands`);
}
main().finally(() => prisma.$disconnect());
