// One-off/regenerable: asks the AI for the filler cast of every island (from its lore) and writes src/lib/game/island-npc-data.ts.
// Usage: npx tsx scripts/gen-island-rosters.ts [onlyIslandName]   (needs the dev DB seeded and OPENROUTER_API_KEY)
import "dotenv/config";
import fs from "fs";
import path from "path";
import { prisma } from "../src/lib/db";
import { generateIslandRoster } from "../src/lib/ai/island-npc";
import type { SeedRosterEntry } from "../src/lib/game/island-npcs";

const OUT = path.resolve(process.cwd(), "src/lib/game/island-npc-data.ts");
const PARALLEL = 4;

function loadExisting(): SeedRosterEntry[] {
  if (!fs.existsSync(OUT)) return [];
  const txt = fs.readFileSync(OUT, "utf8");
  const m = txt.match(/ISLAND_NPC_DATA: SeedRosterEntry\[\] = (\[[\s\S]*\]);\s*$/);
  return m ? (JSON.parse(m[1]) as SeedRosterEntry[]) : [];
}

function save(rows: SeedRosterEntry[]) {
  const body = `// Generated by scripts/gen-island-rosters.ts from each island's lore; edit freely, the seed upserts by name and never revives the dead.\nimport type { SeedRosterEntry } from "./island-npcs";\n\nexport const ISLAND_NPC_DATA: SeedRosterEntry[] = ${JSON.stringify(rows, null, 1)};\n`;
  fs.writeFileSync(OUT, body);
}

async function main() {
  const only = process.argv[2];
  const islands = await prisma.island.findMany({ where: only ? { name: only } : {}, orderBy: { name: "asc" } });
  const rows = loadExisting().filter((r) => !only || r.island !== only);
  const done = new Set(rows.map((r) => r.island));
  const forbidden = new Set<string>([...(await prisma.worldActor.findMany({ select: { name: true } })).map((a) => a.name), ...rows.map((r) => r.name)]);
  const queue = islands.filter((i) => only || !done.has(i.name));
  console.log(`${queue.length} islands to generate (${done.size} already done)`);
  let idx = 0;
  const worker = async () => {
    while (idx < queue.length) {
      const isl = queue[idx++];
      const extra =
        isl.name === "Impel Down"
          ? "ESPECIAL: es la prisión submarina de 6 niveles. Genera 12 carceleros y guardias rasos (2 por cada nivel del 1 al 6, con slot nivel-N-carcelero-1 y nivel-N-carcelero-2, category guard, nivel creciente desde 12 hasta 45). Sin los jefes canon (Magellan, Hannyabal, Sadi-chan, Domino, Saldeath, Blugori, Minochihuahua, Minorhinoceros, Minozebra, Minokoala), que ya existen."
          : isl.factionControl
            ? `Esta isla la controla ${isl.factionControl}: su gente (soldados, capataces, lugartenientes menores) debe estar en el reparto junto a los habitantes normales.`
            : undefined;
      let got = null;
      for (let attempt = 0; attempt < 3 && !got; attempt++) {
        got = await generateIslandRoster({ name: isl.name, description: isl.description, arcHook: isl.arcHook, danger: isl.dangerLevel, control: isl.factionControl, forbidden: [...forbidden], extra });
      }
      if (!got) {
        console.log(`FAILED ${isl.name}`);
        continue;
      }
      const entries: SeedRosterEntry[] = got.map((n) => ({ island: isl.name, slot: n.slot, name: n.name, title: n.title, category: n.category, level: n.level, description: n.description, personality: n.personality, weapon: n.weapon, abilities: n.abilities }));
      for (const e of entries) forbidden.add(e.name);
      rows.push(...entries);
      save(rows);
      console.log(`OK ${isl.name}: ${entries.length} (${entries.map((e) => e.name).join(", ")})`);
    }
  };
  await Promise.all(Array.from({ length: PARALLEL }, worker));
  console.log(`done: ${rows.length} residents`);
}
main().finally(() => prisma.$disconnect());
