import fs from "fs";
const f = "src/lib/engine/island-npc.ts";
let s = fs.readFileSync(f, "utf8");
const crlf = s.includes("\r\n");
const lines = s.replace(/\r\n/g, "\n").split("\n");
const i = lines.findIndex((l) => l.startsWith("const INTRO_RE"));
const fixed = String.raw`const INTRO_RE = new RegExp(String.raw` + "`" + String.raw`\b${"$"}{PERSON}\b[^.!?\n]{0,40}?\b(?:llamad[oa]s?|apodad[oa]s?|conocid[oa]s? como|de nombre)\s+(?:["“«'])?([A-ZÁÉÍÓÚÑ][\wáéíóúñü'’-]{2,}(?:\s+[A-ZÁÉÍÓÚÑ][\wáéíóúñü'’-]{2,})?)` + "`" + String.raw`, "gi");`;
lines.splice(i, 2, fixed);
s = lines.join("\n");
if (crlf) s = s.replace(/\n/g, "\r\n");
fs.writeFileSync(f, s);
